### PR TITLE
Reuse session in rest requests

### LINKED ISSUE #14794: [bug] Session is not reused in ConanRequester
### What is your suggestion?

Hi! :-)

In `ConanRequester:__init__()` a `requests.Session` is created to reuse the connection later (https://github.com/conan-io/conan/blob/develop2/conans/client/rest/conan_requester.py#L80).
Unfortunately in `_call_method` always a new request is created: https://github.com/conan-io/conan/blob/develop2/conans/client/rest/conan_requester.py#L174

Most probably this was not an intentional change from Conan 1 where the `self._http_requester` is used: https://github.com/conan-io/conan/blob/develop/conans/client/rest/conan_requester.py#L140

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

### PR DESCRIPTION
**Pull request by hackenbergstefan**
Changelog: BugFix: Reuse session in ConanRequester to speed up requests.
Docs: omit

fixes #14794

### CODE REVIEW

**Comment by memsharded** [comment]
Hi @hackenbergstefan 

Thanks for your contribution. 
If this is to be considered for 2.0.X releases, please target the ``release/2.0`` branch in your PR.

It seems that the change broke some integrations tests that have some mocking, if you can please try to have a look, and if it makes sense to fix the mocking for the tests to pass, or something else is happening. If not, don't worry, we can try to have a look ourselves.

I am curious, how did you get that deep into the Conan code to realize this? What effects were you seeing, like slower than expected http calls?

**Comment by hackenbergstefan** [comment]
Hey!
First of all, thank's for the quick reply! 👍 

> I am curious, how did you get that deep into the Conan code to realize this? What effects were you seeing, like slower than expected http calls?

I'm currently using Conan 1 migrating to Conan 2. During this migration I realized that Conan 2 was much slower. This disappointed me and my colleagues and so I started digging into ;-)

**Comment by hackenbergstefan** [comment]
> Thanks for your contribution. If this is to be considered for 2.0.X releases, please target the `release/2.0` branch in your PR.

Should I open two PRs? One for `develop2` and one for `release/2.0`?

**Comment by memsharded** [comment]
Interesting! That much slower than caching the session really makes a big difference?
Besides some slowness introduced by the ``compatibility`` checks of ``cppstd`` Conan 2.0 shouldn't be slower than 1.X (and of course besides this possible bug). The cppstd thing it is in our todo-list.

If this bugfix improves noticeable the speed, that would be great, thanks again for looking into this!

**Comment by memsharded** [comment]
> Should I open two PRs? One for develop2 and one for release/2.0?

Not necessary, we merge ``release/2.0``->``develop2`` regularly.

**Comment by hackenbergstefan** [comment]
> If this bugfix improves noticeable the speed, that would be great, thanks again for looking into this!

On my client and infrastructure I had these differences:
- Conan 1 (Session): 0.4-0.1ms per `ConanRequester._call_method`
- Conan 2 (no Session): 100-300ms per `ConanRequester._call_method`

**Comment by AbrilRBS** [comment]
This is great! Thanks a lot for going above and beyond and investigating the root cause of the slowdown :)

**Comment by hackenbergstefan** [comment]
> This is great! Thanks a lot for going above and beyond and investigating the root cause of the slowdown :)

Sure! This is how Open-Source should work in my opinion ;-)

**Review by AbrilRBS — APPROVED** [review]
Seeing a (subjective) improvement in compatibility resolution with this change too, linking #14799 to not lose track of improvements on that area

**Comment by memsharded** [comment]
Amazing. Installing some large graph (only recipes + package_id computation), reduced from 22 seconds to 11 seconds.

Thanks again for contributing this! It will be in next 2.0.12

**Comment by SpaceIm** [comment]
Thanks a lot, it's way way way faster when conan checks new RREV, PREV and compatible packages.

**Pull request merged**
