### PR TITLE
possible fix for develop attribute with export-pkg

### PR DESCRIPTION
**Pull request by memsharded**
Changelog: BugFix: Set the ``self.develop=True`` attribute for recipes when they are used with ``conan export-pkg``, in all methods, it was previously only setting it for the ``package()`` method.
Docs: Omit

Fix https://github.com/conan-io/conan/issues/6583

This is a **exploratory** PR, to see if something breaks. Not guaranteed it will be merged, need to understand better if it could break something.

### CODE REVIEW

**Comment by memsharded** [comment]
> I see it is a small change, but it modifies the graph that is created: from a consumer one to a test_package one. I can imagine an scenario where expanding the graph to the test_package will download more recipes or even fail if using a graphlock.

No, it is not true. The graph is not modified at all, only the ``loader.dev_reference`` is assigned, that is the only effective change.

**Comment by jgsogo** [comment]
What I see is that, from the `_load_root_node` we start to call 

```
return self._load_root_test_package(path, create_reference, graph_lock, profile)
```

instead of 

```
root_node, ref = self._load_root_consumer(path, graph_lock, profile, graph_info.root)
```

but yes, having a look to the sources it looks like there is not much difference between those two functions.

Ok then

**Comment by memsharded** [comment]
> What I see is that, from the _load_root_node we start to call

Nop. Check the conditional.

**Comment by jgsogo** [comment]
OMG, there is another `if` before to call a different `_load_xxx`! :cold_sweat: 

Now I see, this is almost changing nothing :+1:

**Pull request merged**
