### PR TITLE
requests-2.14.2

### PR DESCRIPTION
**Pull request by tivek**
bump requests version

### CODE REVIEW

**Comment by memsharded** [comment]
Is this urgent, to be incorporated to release 0.23? There is already a RC for it, can it wait until 0.24? Thanks!

**Comment by tivek** [comment]
Hi, I don't think it is urgent. I have to apply this patch to the release in order to test and package for Arch Linux, but it is not a big issue.

However, we should discuss some guidelines when to bump the requirements.txt and when to keep them fixed, as pointed out in #1245. That would really help with maintaining Conan releases for different OSs.

**Comment by lasote** [comment]
Requests follow semantic versioning, the minor versions shouldn't break backwards compatibilty, so I suggest to change it to:

`requests>=2.7.0, <3.0.0`

About the #1245, let's go case by case, if any other library needs a bump let's check it's versioning schema and take a decision. WDYT?

**Comment by tivek** [comment]
Sounds perfect. Will update this pull request then, and whenever a library bump comes along I will first check its versioning schema.

**Pull request closed without merging**
