### PR TITLE
Implements #2420 : --update option should not ignore local packages

### PR DESCRIPTION
**Pull request by jrickman**
RequireResolver initializer now takes a `local_first` parameter, indicating priority searching between local and remote versions.

The remote search code has been extracted to its own function, `RequireResolver._resolve_remote()`, which parallels the existing `_resolve_local()` function.

ConanManager now always provides the `_search_manager` object to RequireResolver, and instead uses the `update` argument to determine how to set the `local_first` value.

### CODE REVIEW

**Comment by memsharded** [comment]
This seems a good contribution, thank you!

However, this is not a minor change, as it is changing behavior. Some new integration tests that check this behavior are needed, and we would also need to do a careful analysis of what could break backwards compatibility. It looks good, and I think it will be possible, but better check. Thanks again!

**Comment by memsharded** [comment]
I am proposing and contributing some tests myself.

**Comment by jrickman** [comment]
Thanks. Let me know if there's anything I can do to help.

**Comment by memsharded** [comment]
Thanks very much for your contribution and fixing this!

**Comment by jrickman** [comment]
Glad to help. I think conan is a great tool, and you guys are doing great work.

**Pull request merged**
