### PR TITLE
Pure refactor CMakeToolchain

### PR DESCRIPTION
**Pull request by lasote**
Changelog: omit
Docs: omit

I find it a bit uncomfortable to have all the cmake toolchain code in a single file, I propose to move the blocks into another module and everything in a toolchain package.

### CODE REVIEW

**Review by czoido — APPROVED** [review]

**Review by franramirez688 — APPROVED** [review]

**Review by memsharded — COMMENTED** [review]
While I agree and this refactor is good and improves the code in 1.X, we need to consider the merging of develop->develop2, this one might be painful, the diff between develop and develop2 for this file is already quite large:

> 1 file changed, 53 insertions(+), 124 deletions(-)

Changed:
- removed ``six`` things
- removed support for ``compiler.base``
- removed ``check_using_build_profile(self._conanfile)``
- changes related to now ``settings_build`` is always defined, no checks
- removed a few ``"host_build_paths_root`` and all the "build" context temporary things added to 1.X not applicable in 2.0 anymore
- removed ``build_build_paths``
- refactors/simplifications around apple tools
- big changes in ``libcxx_flag(self._conanfile)``

The creation of new files and such moving of big chunks, typically the merge will fail, and do all those changes manually will be painful. I'd probably try to wait for this kind of refactor and do it in develop2 directly a bit later.

**Comment by lasote** [comment]
The merge to develop2 has to be done by concept. Not by diff.

**Comment by lasote** [comment]
Now that develop2 and develop are up to date, I'll merge this under my responsibility and will replicate it in develop2.

**Comment by lasote** [comment]
done. develop2 updated.

**Comment by memsharded** [comment]
Perfect, many thanks!

**Pull request merged**
