### PR TITLE
Feature/workspace local detection

### LINKED ISSUE #3403: [workspaces] Packages are not detected as local/development
Hello,

When using `conan install .. -if=.` in a Conan workspace, Conan detects the packages as being installed/consumed, which is not the case.

Furthermore, `self.develop` is `False`, while `self.in_local_cache` is `True`. I would expect the opposite to be correct.

I'm using Conan 1.6.1 on macOS High Sierra

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

### PR DESCRIPTION
**Pull request by theodelrieu**
Changelog: Fix: `self.develop` and `self.in_local_cache` are respectively `True` and `False` for workspace packages.

Fixes #3403.

There must be a better way to test the expected behavior than what I did here... Please let met know!

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [x] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. Also adding a description of the changes in the ``changelog.rst`` file. https://github.com/conan-io/docs

### CODE REVIEW

**Comment by lasote** [comment]
Relaunched CI, it was a non-related error.

**Comment by theodelrieu** [comment]
Is it still the same error?

**Comment by lasote** [comment]
Yes. Looks like it is somehow related to the failing `shutil.rmtree` in the test. I don't know if replacing it with `tools.rmdir(os.path.join(client.current_folder, "build"))` will improve or maybe some `time.sleep()` before it... :S Windows crap...

**Comment by theodelrieu** [comment]
@lasote Seems it did the trick :)

**Comment by lasote** [comment]
Hi, @theodelrieu sorry because the workspaces feature (still experimental) is totally blocked. We decided to start with the concept of "editable packages" that will be released in the next release. We will try to build workspaces in the top of it so it is very likely the workspaces feature change A LOT. So we don't want to evolve workspaces right now. Sorry, developing Conan is very hard sometimes.

**Comment by theodelrieu** [comment]
No problem, I'm working with my custom Conan version meanwhile. I can be a beta-tester for the new workspaces version :)

**Comment by memsharded** [comment]
This might be a bit outdated wrt the current work of Editable packages and workspaces https://github.com/conan-io/conan/pull/4481. 

There, the ``in_local_cache`` variable was already defined, and I have made sure in the last commit that ``develop`` is also True for Editable (and Workspace) packages. 

Thanks for raising this issue and the fix! It will be hopefully released in next Conan 1.13

**Pull request closed without merging**
