### PR TITLE
Fix broken `cpp_info.location` deduction due to unsanitized regex

### PR DESCRIPTION
**Pull request by valgur**
Changelog: Fix: Fix broken `cpp_info.location` deduction due to unsanitized regex.
Docs: Omit

Using `grpc` with `-c tools.cmake.cmakedeps:new=will_break_next` currently fails with:
> ConanException: grpc/1.67.1: Cannot obtain 'location' for library 'grpc++_alts' in ['/home/martin/.conan2/p/b/grpcad62ea78a9235/p/lib']. You can specify 'cpp_info.location' directly or report in github.com/conan-io/conan/issues if you think it should have been deduced correctly.

This PR fixes the location detection failure due to the unsanitized `+` symbols in the library name.

### CODE REVIEW

**Comment by valgur** [comment]
The location detection could be improved further, still. It should fall back to the fuzzy regex only if an exact match is not found.
> grpc/1.67.1: WARN: There were several matches for Lib grpc: ['lib/libgrpc.so.44.0.0', 'lib/libgrpc_authorization_provider.so.1.67.1', 'lib/libgrpc_plugin_support.so.1.67.1', 'lib/libgrpc_unsecure.so.44.0.0']

> grpc/1.67.1: WARN: There were several matches for Lib grpc++: ['lib/libgrpc++.so.1.67.1', 'lib/libgrpc++_alts.so.1.67.1', 'lib/libgrpc++_error_details.so.1.67.1', 'lib/libgrpc++_reflection.so.1.67.1', 'lib/libgrpc++_unsecure.so.1.67.1']

**Comment by valgur** [comment]
Unrelated, but too minor for a separate issue - using `grpc` with the new CMakeDeps still fails after this fix with
```
  File "/home/martin/libs/conan/conan/tools/cmake/cmakedeps2/target_configuration.py", line 169, in _get_cmake_lib
    self._conanfile.output.warning("frameworks not supported yet in new CMakeDeps generator")
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConanFileInterface' object has no attribute 'output'
```

**Review by memsharded — COMMENTED** [review]
Thanks for your contribution.

We would like to start first with some unit test that would fail without this change. This is the best way to move forward without breaking the addressed issue because is not properly covered.

**Comment by memsharded** [comment]
> Unrelated, but too minor for a separate issue - using grpc with the new CMakeDeps still fails after this fix with

Agree, if you want you can just replace that with a ``ConanOutput(scope=str(self.conanfile)).warning()`` or something like that, this doesn't require test coverage yet, as it is just a temporary warning until the frameworks are implemented.

**Review by franramirez688 — APPROVED** [review]

**Review by memsharded — APPROVED** [review]

**Comment by memsharded** [comment]
Merged, thanks for the contribution, it will be in next Conan 2.11

**Pull request merged**
