### PR TITLE
Added excludes to copy command

### PR DESCRIPTION
**Pull request by claasd**

### CODE REVIEW

**Comment by memsharded** [comment]
This might help with the implementation of ``exports_excludes``: https://github.com/conan-io/conan/issues/810

**Comment by claasd** [comment]
I added your PR.
Additionally, i made a small change that excludes can be either a string or a tuple

**Comment by memsharded** [comment]
Thanks, great job!

**Comment by DmitrySokolov** [comment]
FYI, [docs](http://docs.conan.io/en/latest/reference/conanfile/methods.html#package) are not updated.

**Comment by memsharded** [comment]
Added docs: https://github.com/conan-io/docs/commit/4a8d1cc60d29053b2673057d00efede08982ec09

Thanks for noticing and telling!

**Pull request merged**
