### PR TITLE
#4696 (Part 2) - Pattern-checking is case-sensitive now

### PR DESCRIPTION
**Pull request by monsdar**
This is an addition to the existing (already merged) PR #4787. It adds case-sensitive pattern matching and a few tests for that.

### CODE REVIEW

**Comment by lasote** [comment]
So the previous behavior (before your previous PR) was case-insensitive right?
In that case we should keep it.

**Comment by monsdar** [comment]
Correct. The already merged code is case-insensitive. So `conan install ... --build=BOOST*` will lead to a rebuild of `boost/1.69.0@conan/stable`. The changes in this PR change that to case-sensitive, where the user needs to do `conan install ... --build=boost` in order to have the package rebuilt.

Not sure what's the current behaviour to be honest, I just went with your comment in the other PR and changed the code accordingly :D

**Comment by monsdar** [comment]
So feel free to close this PR as invalid.. it was 5 minutes of code changes, so no worries about any hurt feelings ;)

**Comment by lasote** [comment]
Sorry for the confusion. We just wanted to add a test to verify the current behavior. I thought it was case sensitive, but now I see that it was not. Could you revert the `fnmatch` and reuse the test asserting the opposite? Thanks!

**Pull request closed without merging**
