### PR TITLE
automatic export on test_package command

### PR DESCRIPTION
**Pull request by memsharded**
This will solve the issue: https://github.com/conan-io/conan/issues/302

### CODE REVIEW

**Comment by lasote** [comment]
There is some issue with python3 and a file locking

**Comment by memsharded** [comment]
This seems that it is passing CI now. I am just thinking that maybe it would need an option to NOT export before a test_package. Is this a use case? To test a recipe from a remote? It could be an obsolete version, different to the one contained in the package repo.

**Comment by lasote** [comment]
Yes, I'm sure I've done things like have 2 different directories and test the other conanfile etc.

**Comment by lasote** [comment]
I've made a PR with the new option.

**Pull request merged**
