### PR TITLE
Declare the target only if it does not exist

### PR DESCRIPTION
**Pull request by traceon**
When including cmake/cmake_multi-generated scripts multiple times in the same `CmakeLists.txt` (for example, in scenarios where dependencies are added incrementally and `conan` is being re-run and the script is being included each time), some target definitions will repeat, and it is not allowed by CMake (while this is not the case with simple vars, obviously.) This PR modifies cmake/cmake_multi generators to define each target only if it hasn't been defined yet in the outputting script.

### CODE REVIEW

**Comment by memsharded** [comment]
The thing is that multiple inclusion of the files might produce other unexpected issues, like the script is "appending" some variables like:

```cmake
set(CMAKE_CXX_FLAGS ${CONAN_CXX_FLAGS} ${CMAKE_CXX_FLAGS})
```
While this might be harmless many times, I think it would be preferred to avoid the multiple inclusion, with some global flag check before the inclusion.

**Comment by traceon** [comment]
Only these are set on inclusion (when conan_basic_setup() is not called yet):
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CONAN_CMD_CXX_FLAGS}")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${CONAN_CMD_C_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${CONAN_CMD_SHARED_LINKER_FLAGS}")
```
But I haven't seen them defined anywhere.

**Comment by memsharded** [comment]
No, sorry, my mistake. ``CMAKE_XXX`` variables are not defined at all at inclusion time. The variables that are actually defined, and appended are:

```cmake
set(CONAN_CXX_FLAGS "<some flags> ${CONAN_CXX_FLAGS}")
```
Also CONAN_C_FLAGS, CONAN_EXE_LINKER_FLAGS, CONAN_SHARED_LINKER_FLAGS

This is necessary to be able to process command line arguments too. But the issue is still the same, one generated ``conanbuildinfo.cmake`` shouldn't be included more than once.

I would suggest some construct like this (not tested):

```cmake
if(NOT CONAN_BUILD_INFO_LOADED)
    include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    set(CONAN_BUILD_INFO_LOADED True CACHE INTERNAL "loaded conanbuildinfo")
    conan_basic_setup()
endif()
```

**Comment by SSE4** [comment]
@memsharded in general, I find these PR very useful addition, because there are situations when more than one CMakeLists.txt files can invoke conan_basic_setup(). for instance, if you're building some aggregation project that combines several git submodules/subtrees, and several of them are using conan. 
so it's good to have some kind of "include guards" for conan-generated CMake targets.

**Comment by memsharded** [comment]
I am not opposed to some kind of include guards, but the currently proposed ones are not enough, because multiple inclusion will duplicate, triplicate... many conan variables values, which are later translated to targets and could have unexpected effects

**Comment by memsharded** [comment]
Hi @traceon !

Are you still wanting to have guards against multiple inclusion? I think a solution could be to add guards to the whole ``conanbuildinfo.cmake`` file, what do you think? 

I am concerned about the file being included at different scopes, so there will be variables at different scopes, but the targets are always at the root scope? If that is the case, maybe there is no other solution than leaving the guards for the consumer who is including conanbuildinfo.cmake many times.

**Comment by traceon** [comment]
Hi @memsharded ,

The use scenario is when I incrementally add third party dependencies and rerun `conan`, and each time a fresh `conanbuildinfo.cmake` is generated. So it's not that only the first should be included, but each time the last one.

**Comment by memsharded** [comment]
I think that is not a problem, I think I do it often, and it just works. As the file is being included by CMakeLists, changes in it are already processed and managed. So when I add deps, re-run ``conan install`` then build, and it is fine.

What do you mean? That if we put an include guard over the whole file, it won't be processed for changes? Maybe I misunderstood something.

**Comment by traceon** [comment]
If you put a guard around the whole file, when you include it second time, the second inclusion will be ignored, so you won't have variables of the new third party dependencies defined in your CMakeLists.txt.

**Comment by traceon** [comment]
Also, adding new dependencies [may] happen several times during the same configuration step, and not after CMake configure is done.

**Comment by memsharded** [comment]
This diff is very large now, it seems that github might not be using the correct base commit. Maybe close this PR and open a new one if necessary.

**Pull request closed without merging**
