### PR TITLE
Assuming os_build and arch_build as settings

### LINKED ISSUE #4060: Search query handles os_build and arch_build as options
When searching for the packages of a receipe os_build and arch_build are not take into account correctly. Even if a package matches, it is not included in the resulting list. From what I can see, only specific strings in the query are treated as settings, all others as options.

### PR DESCRIPTION
**Pull request by kolrami**
Changelog: Bugfix: Take into account ``os_build`` and ``arch_build`` for search queries.

Accoding to issue https://github.com/conan-io/conan/issues/4060 os_build and arch_build are not handled as options. This tries to fix it, but maybe further things are needed?

Close #4060

### CODE REVIEW

**Comment by memsharded** [comment]
Hi @kolrami 

Thanks for detecting and fixing this issue. It would be great to add a unit test to make sure it is covered and doesn't break in the future. Do you want to try it yourself, would you need help?

**Comment by kolrami** [comment]
Hi @memsharded, yes I will give it a try :)

**Comment by kolrami** [comment]
Hi @memsharded, I now have added some unit tests for the _build settings. Maybe you can have a look? Thank you very much.

**Comment by kolrami** [comment]
Hi @memsharded, while this fixes the problem for now, a question for the future could be if we need this hard-coded list at all. What do you think of a more generic way:
- First look into the `info_settings`. If the given `prop_name` is found we compare against it.
- If `prop_name` is not found in `info_settings`, we look into the options.
- To still have settings and options with the same name (maybe we do not want that at all) allow something like `settings.` and `options.` in a query to explicitly specify if we want to look for a setting or an option?

**Comment by memsharded** [comment]
Nice job! You even detected a duplicate test. And your tests are also very good, perfect, many thanks!

**Comment by memsharded** [comment]
I also agree with your view, and that it could be improved in the future for using different settings. 
The truth is that we would like to improve the settings model for cross-building. While this might take a while, it is in our roadmap. It will be a good moment to revisit this issue. Thanks for the feedback!

**Comment by kolrami** [comment]
Sounds cool :) Thank you for the support!

**Pull request merged**
