### PR TITLE
conan copy symlinks

### PR DESCRIPTION
**Pull request by memsharded**

### CODE REVIEW

**Comment by SSE4** [comment]
@memsharded sorry for the dumb question, but will it allow to copy symbolic links on Windows as well?

**Comment by memsharded** [comment]
@SSE4 that is not a dumb question. Indeed, this will only work on non Windows machines. 
So users relying on ``conan copy`` for multi-platform packages including symlinks, should be careful to execute it in non Windows machines. I have thought of adding some check to warn Windows users, but I don't know it how to do it without a manual file by file copy, which would be much slower. Wdyt?

**Comment by SSE4** [comment]
@memsharded looking into the code, it seems like conan itself doesn't deal with the symbolic links, everything is done by python shutil module. so, yeah, warning would be nice for Windows users, at least prior to Creators Update.

**Comment by memsharded** [comment]
@SSE4 the issue is that to display a warning, conan would need to walk and check everything it is copying for symlinks, which will be slower. I am merging this, it is already a quick improvement to be released in the minor 0.26.1. @lasote, @SSE4, any suggestions to improve this for 0.27?

**Pull request merged**
