### PR TITLE
[2.0] [Refactor] Remove check_updates

### PR DESCRIPTION
**Pull request by lasote**
According to some TODO comments, it is possible that the argument `check_update` is not used anymore and the `update` is enough. Opened draft to see the CI opinion.

Changelog: omit
Docs: omit

### CODE REVIEW

**Review by memsharded — COMMENTED** [review]
``check_update`` is actually used in ``conan info`` command, to know where there will be updates for recipes and packages, without actually retrieving them. A different thing is if this is a valuable use case that we want to maintain or not.

**Comment by lasote** [comment]
we could say then that the tests are not complete or maybe not checking that the recipe hasn't been downloaded?

**Comment by memsharded** [comment]
> we could say then that the tests are not complete or maybe not checking that the recipe hasn't been downloaded?

Yes, it is likely that some tests have been disabled or removed during all the previous changes in develop2.

**Comment by lasote** [comment]
Tests and check_updates functionality for conan info recovered at: #9838

**Pull request closed without merging**
