### PR TITLE
Feature: add venv command

### PR DESCRIPTION
**Pull request by SSE4**
Changelog: Feature: Add venv command.
Docs: TODO

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [ ] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by uilianries** [comment]
Good idea!

**Review by memsharded — COMMENTED** [review]
I would like to learn a bit better the use case for this PR:

- What would be some real life use cases for this command
- User requests that would be satisfied with this feature
- Why not using virtualenv generators

**Comment by SSE4** [comment]
> I would like to learn a bit better the use case for this PR:
> 
> * What would be some real life use cases for this command
> * User requests that would be satisfied with this feature
> * Why not using virtualenv generators

the use case is the same as `VirtuanEnv` itself, basically. actually, it's more likely a syntax sugar on top of `VirtualEnv`.
right now, to get cmake and execute command with it I need 4 conan commands:
```
conan install cmake/3.19@ -g virtualenv
./activate.sh (or ps1, or bat)
cmake --version
./deactivate.sh (or ps1, or bat)
```
with new feature, it would be just:
```
conan venv cmake/3.19@ -- cmake --version
```
it's easier to remember just one command than 4 commands, right?
also, it is shell-agnostic, so you don't need to always check which script to execute.
further, I can use this command as an alias, or environment variable, like:
```
alias cmake=conan venv cmake/3.19@ --
```
```
export CONAN_CMAKE_PROGRAM=conan venv cmake/3.19@ --
```
so the similar one-liner could be easily used everywhere I need to pass for instance CC/CXX.

**Comment by memsharded** [comment]
Thanks very much for describing this in detail, now I understand better.

I think you described this accurately: ``it's more likely a syntax sugar on top of``. As such, I think this is not the right time to introduce it. We are just starting the process of the new toolchains, and moving there Autotools and also managing build-requires will probably require some big efforts in managing virtualenvs. We will put the foundations first, which, at the moment they will be based on files (Virtualenv generator like), and we will consider higher level commands later.

Despite its apparent simplicity, some of the usages that you are already commenting reads to me like a Pandora box waiting to be opened, like ``export CONAN_CMAKE_PROGRAM=conan venv cmake/3.19@ --`` means that now when you launch Conan to install something, it might launch Conan itself as a subprocess. What if ``cmake/3.19`` doesn't have a binary, will it build it from source? Some of the locking mechanisms of the cache might fail, as they are not prepared to be recursive. I am not sure we want to open this right now, I recommend reviewing this later down the road, at least after maturing the whole build system new toolchain integrations and having a clear view of how the environments look like in general.

**Comment by memsharded** [comment]
Created issue in https://github.com/conan-io/conan/issues/8393, and assigned it for checking later, lets close this PR at this moment, we will revisit later following the issue.

**Pull request closed without merging**
