### PR TITLE
Add support for Xcode 13

### LINKED ISSUE #9641: [feature] Support for Xcode 13
Conan 1.40.1 does not support Xcode 13.0. To fix it, "13.0" must be added to the list of apple_clang versions.

OS: macOS 11.6, Xcode: 13.0m, conan --version: 1.40.1, cc --version: "Apple clang version 13.0.0 (clang-1300.0.29.3)"

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

### PR DESCRIPTION
**Pull request by janosvitok**
Changelog: Bugfix: Add support for Xcode 13/Apple clang 13.0
Docs: omit

Closes #9641

- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by czoido** [comment]
Hi @janosvitok,
I'm opening a new PR: https://github.com/conan-io/conan/pull/9643 that includes you as a contributor as well, we are in a little rush because we want to release a 1.40.2 minor with these changes ASAP and we need to change the branches.
Thanks a lot for the contribution. I'm closing this one in favor of: https://github.com/conan-io/conan/pull/9643

**Comment by janosvitok** [comment]
@czoido, I don't mind how you do it, as long as conan supports Xcode out of box :)

Cheers!

**Comment by H-G-Hristov** [comment]
How is this supposed to work. Upgrading conan I mean.

I did `pip3 install conan --upgrade`

I got the latest conan but when I tried to build. I still got:

>-- Conan executing: /usr/local/bin/conan install . -s build_type=RelWithDebInfo -s compiler=apple-clang -s compiler.version=13.0 -s compiler.libcxx=libc++ -s compiler.cppstd=14 -s arch=arm64 -s arch_build=arm64 -s os.version=10.12 -g=cmake --build=missing
ERROR: Invalid setting '13.0' is not a valid 'settings.compiler.version' value.
Possible values are ['5.0', '5.1', '6.0', '6.1', '7.0', '7.3', '8.0', '8.1', '9.0', '9.1', '10.0', '11.0', '12.0']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"

So I still had to manually add: `"13.0"` to `~/.conan/settings.yml` as before:
>     apple-clang: &apple_clang
        version: ["5.0", "5.1", "6.0", "6.1", "7.0", "7.3", "8.0", "8.1", "9.0", "9.1", "10.0", "11.0", "12.0", "13.0"]

**Comment by memsharded** [comment]
If you had previously modified settings.yml, the Conan migration will not overwrite your existing, modified settings.yml to avoid destroying your modifications. Try removing the ``settings.yml`` from the cache, run Conan again (any ``conan install`` command) and it will regenerate it with 13.0 in it.

**Pull request closed without merging**
