### PR TITLE
Change progress bars to tqdm library

### LINKED ISSUE #3536: Add progress bars to improve UX
A progress bar will indicate the user that something is running and he must wait until completion. Some operations in Conan can take a long time (uploading, unzipping,...) and the user can Ctrl+Break it if there is no feedback.

We may develop/reuse a progress bar component (even for parallel jobs) that could be used anywhere inside Conan. This component may replace also existing code.

Here it is a list with the places where a progress bar can fit (list updated with comments):

### PR DESCRIPTION
**Pull request by czoido**
Changelog: Feature: Change progress bar output to tqdm to make it look better
Docs: Omit

Closes #3536

Hi!, I have been making some changes to use the same the same progress bars everywhere.
In this branch [tqdm ](https://github.com/tqdm/tqdm) library is used for progress bars and
when the bar finishes a `[done]` message will appear replacing the bar.
Here is the comparison between them:

current_progress
new_progress

- [X] Refer to the issue that supports this Pull Request.
- [X] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [X] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by jgsogo** [comment]
I reallly like it and I think these changes are needed, I'm just wondering if we can take into account a couple of details, feel free to comment and/or discard any of them before trying to make any modification:
 * Console width. I think it should be taken from the actual console width, otherwise the progress bars start to write several lines and the output is a mess.
 * Example of output:
   ```
   Downloading conanmanifest.txt
   conanmanifest.txt [done]                                                            
   Downloading conanfile.py
   conanfile.py [done]                                                                 
   Downloading conan_sources.tgz
   conan_sources.tgz [done]                                                            
   Decompressing conan_sources.tgz [done]
   ```
    Last `[done]` is in the same line as the description. I prefer this option (more compact) for every line or, if we use a new line I prefer to show the statistics (`[size, time to do action]`)
 * Piping to a file:
   ```
   boost/1.70.0@conan/stable: Package installed 6b889d4de82254d8e4d5006bdf79e52e2af2c88c
   boost/1.70.0@conan/stable: Downloading boost/1.70.0@conan/stable:c43a78d3e0e0c6199b377d00bd5385c6d7716729
   boost/1.70.0@conan/stable: Retrieving package c43a78d3e0e0c6199b377d00bd5385c6d7716729 from remote 'conan-center' 
   Downloading conanmanifest.txt
   
   Downloading conaninfo.txt
   
   Downloading conan_package.tgz
   
   ....

   ```
    Can we get rid of those blank lines? I think that a compact output is desired.
 * I'm also trying to check the output of the `run_to_file`, but I cannot make it work. 🤷‍♂

**Comment by czoido** [comment]
Yes, I'm going to give a try to the output you suggest as I think It will be cleaner. 
I'm also having a look at the output when not in terminal mode to see if we can get rid of the blank lines.
Thanks a lot for your feedback!

**Comment by czoido** [comment]
Cleaner output:
modified_bars

**Comment by uilianries** [comment]
@czoido Have you tried using CI services? (Gitlab, Travis, Appveyor, Azure...) ?

**Comment by czoido** [comment]
Hi @uilianries . 
I think that It should not be a problem because It always checks that `output.is_terminal` before putting the progress bar so the change shouldn't affect CI or tests. Conan Jenkins CI has no problems with it for the tests.

**Comment by uilianries** [comment]
I see.

Anyway, I made some validation using your changes with CI services. It's working fine:

https://ci.appveyor.com/project/uilianries/test-conan-new-bar/builds/25614601
https://gitlab.com/uilianries/test-conan-new-bar/-/jobs/242056013
https://travis-ci.com/uilianries/test-conan-new-bar/builds/117301465

There is no progress bar, but it's the expected behavior, as you said.

**Comment by czoido** [comment]
That's great! Thanks a lot!

**Comment by memsharded** [comment]
This is looking good. 
Just one quick question, because it was a problem in CI. In CI, it is not only necessary that it doesn't appear a progress bar, but a dot "." should be printed every X (15-30) seconds, because otherwise some CIs automation consider the job stalled. I think this was already a feature of some of our custom progress bars, please @uilianries and @czoido, check with the changes.

I think I would go with this approach to get the functionality with minimal changes, but in a future PR, will try to factor the "is_terminal" checks, and have some abstract "progress-bar" that abstract away the details for different terminals, etc.

**Comment by uilianries** [comment]
@czoido you can use https://speed.hetzner.de/ to download bigger files which requires more time and printing the progress dots.

**Comment by czoido** [comment]
Hi @memsharded , The CI output is the same than It was before but in one case I have just changed
when uploading files. Now a dot is written for aproximately each uploaded MB. I think It shouldn´t be 
a problem but I will do further tests with @uilianries suggestions.
I completely agree to go ahead with minimal changes and factor everything in the near future. 
I think we should should homogenize all file operations.
The output now should be like this for the CI:
dots_output_ci

**Comment by lasote** [comment]
Agree, let's do it!

**Pull request merged**
