### PR TITLE
[MesonToolchain] Added tools.build:defines conf to 'conan list'

### PR DESCRIPTION
**Pull request by paulharris**
Changelog: Omit
Docs: Omit

Addition to documentation, follow up to docs#3709

No need to add further info to documentation.

### CODE REVIEW

**Review by AbrilRBS — APPROVED** [review]
Good catch, thanks a lot for noticing and taking the time to create the PR :)

**Comment by AbrilRBS** [comment]
Seems like it'd be best if you could rebase this into the `release/2.3` branch to be released for the next 2.3.1 release, thanks!

**Comment by paulharris** [comment]
Rebased!

**Review by AbrilRBS — APPROVED** [review]
Thanks a lot! The docs will get updated automatically once the new update lands :)

**Pull request merged**
