### PR TITLE
[Fix #6079] Use native APIs for reliable interprocess (shared) locking

### LINKED ISSUE #6079: [bug] Repo advisory locks fail to release on process termination
I am occasionally seeing Conan get stuck trying to obtain the advisory locks on the repository or packages within the repository. I have dug through the code and I have a hard time understanding how this issue can possibly occur. Perhaps someone else can figure out what is happening, or maybe know's the next place to look? Here's what I know so far:

I have seen issue #2071, but I do not believe it to be fixed on all platforms, and I do not understand how PR #2996 could have "fixed" the issue:

- Conan, as far as I can tell, uses the "correct" system interprocess locking mechanism (not the naive method using `open` and `O_EXCL`).
- On Unix systems, this will use `fcntl()` to implement shared/exclusive locking with the support of the operating system.
- On Windows, this will use the `msvcrt.locking` Python function, which (AFAICT) is implemented in terms of Win32 `LockFileEx`.
- Regardless of platform, the operating system will guarantee that it will automatically release any open locks in case that the owning processes are terminated, regardless of termination method.
- For this reason, even if a lock owner is hard-killed with `SIGKILL` or `::TerminateProcess()`, the advisory locks will be released by the operating system. Thus I cannot see how handling `SIGTERM` could have had any effect on the locking behavior.
- What's more, I don't see how this could possibly be an issue _at all_. By my understanding of the Win32 and POSIX documentation, there should be no way that the hold on the locks can possibly outlive a Conan process!
- I'm currently debugging on Windows, although I have seen (but cannot reproduce) the issue on Linux (I wouldn't worry about Linux ATM).
- I opened ProcExp to try and see what process is holding open a handle to the package lock (`foo.count.lock`), and... nothing. No one has the file open! AFAIK, if no one has the file open, the operating system will release the lock. What gives?

I've opened the code to the MSVCRT, `locking.cpp`, upon which `msvcrt.locking` is implemented. It all looks like completely valid usage of `::LockFileEx`, and I cannot see how the locks can outlive the process.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows Server 1903 Core
  * Conan version: 1.20.2
  * Python version: Python 3.8.0

### Steps to reproduce (Include if Applicable)
1. Begin a conan operation to install/build/export a package into the local repository.
2. While an advisory lock is held, non-gracefully terminate the Python process. On Windows, there are no 'signals' quite like POSIX, although there is limited emulation of SIGINT. I cannot be certain what termination mechanism is in use, as this termination is going through "Stop build" in a Bamboo dashboard, of which the documented behavior on Windows is somewhat confusing. However, the termination mechanism should not matter (See above).
3. Attempting to re-run the process will cause Conan to deadlock when trying to re-obtain access to the same advisory locks.

### PR DESCRIPTION
**Pull request by vector-of-bool**
This changeset removes the dependency on `fasteners` and adds code and utilities based on the platform's native filesystem advisory locking. Rather than implementing shared locks atop exclusive locks, this code now uses OS-supported shared locking, giving perfectly reliable cleanup of locks regardless of cause of unexpected process exit (`SIGKILL`, `TerminateProcess`, or a user tripping over a power cable). This fixes #6079.

Changelog: (Bugfix): Interprocess locking is now cleaned up by the operating system reliably, and the functionality to manually remove locks has been deprecated (is now a no-op). If no Conan process is running, it is guaranteed by the OS that the locks will not be held.

- [x] Refer to the issue that supports this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.

### CODE REVIEW

**Comment by vector-of-bool** [comment]
Hello. I know what is happening in the tests. I was running them incorrectly before I pushed and the failing tests were not appearing locally. I'm working on fixing them now. The current goof is that tests are expecting to lock files to be removed and the parent directories also cleaned out. I'll have to move the path for the lock files out of `data/`.

I was thinking about putting in a fix for `fasteners`, but I'm unsure of how responsive it is to merging changes (there are a few open from the past few months).

**Comment by vector-of-bool** [comment]
Got the tests green and I squashed out some of the trivial commits. Should be all ready now?

**Comment by memsharded** [comment]
Hi @vector-of-bool 

Great job that you are doing here. It is looking good so far.

My main concern about it is the risk of breaking, specially in the non mainstream platforms. I have added the "help wanted" label and I am going to share on social too, to ask other users to run the test suite for those platforms:

- FreeBSD
- SunOS
- AIX

Both Python27 and Python36+ would be very useful.
It would be great to have feedback from non-mainstream linux distros too.

Also, if what you did is really based on ``fasteners`` I guess we would be mostly good, though the changes can still be risky in other platforms. Is your work branched from fasteners, or totally new implementation?

I am copying here people that were involved in adding those settings, according to ``git blame``. Could you please help us with this? Many thanks!

cc/ @tivek @anton-matosov @scddev @madduci

**Comment by memsharded** [comment]
Thinking again about the risk of this (the problem is that we have many users stuck with different variants of the OSs, for example in Windows, down to Windows 95, NT, Server, etc... and the behavior of the locks might be different in different platforms), I believe that the best way to achieve proper validation and testing of this feature from a much wider community  is to upstream it to ``fasteners``. We might get some feedback from our users, but still might be not enough.

I would strongly recommend to submit a PR there to ``fasteners``, we will support it, lets try it and see what happens. Please let us know what you think.

**Comment by madduci** [comment]
My two cents, Python 2.7 will be End-Of-Life very soon, while Python 3.x is here to stay.

In Solaris, the latest Python binary available is 2.7, Python 3.6+ must be compiled from sources and I'm not sure it is a trivial task / the platform is still supported. I think we can cut out Solaris from the supported platforms in new versions of conan. 

I believe this change qualifies conan for a version tagging like 2.x.x

**Comment by vector-of-bool** [comment]
All of my own local dev and testing has been within Python 2.7. For what it's worth, the non-Windows is implemented as-per POSIX, not Linux, so if a platform is "POSIX compliant," then it should "just work" (including Solaris).

It shouldn't be much work to port a lot of this work into `fasteners`, as none of it is Conan-specific. Simply transplanting the source files should be sufficient. I'll get on that and send them a PR.

**Comment by vector-of-bool** [comment]
Created: https://github.com/harlowja/fasteners/pull/41

**Comment by memsharded** [comment]
This PR is outdated. A brief summary:

- Most of the changes here were upstreamed to https://github.com/harlowja/fasteners/pull/41, and implemented in https://github.com/harlowja/fasteners/pull/57
- This was never properly reviewed and considered for merge, because it had quite a complexity of something outside of the maintainers expertise and scope, so the liability and risk for future maintenance would be relatively high. It is much better in the upstream ``fasteners``
- Conan 2.0 is already out, and it had to do a step-back in concurrency, currently eliminating all locks and synchronization. But also did some big effort in trying to provide a more decoupled storage model in the cache, that will hopefully allow easier implementation of concurrency in the conan cache
- The implementation of concurrency of Conan cache is planned as a 2.X roadmap feature. It is planned that it will use latest fasteners version.

I am closing the PR as outdated, but thanks very much for all the effort, the contributions and the feedback, very appreciated and I am positive that with the upstream latest version we will be able to implement more solid concurrency in the 2.X future.

**Pull request closed without merging**
