### PR TITLE
passlib 1.7.0 is out, bump passlib version

### PR DESCRIPTION
**Pull request by tivek**
Passlib 1.7.0 is out on pypi and Arch Linux. Conan 0.16.0 passes all tests with the new passlib on Travis CI, hopefully the develop branch will too.

By the way, I can't find any code that references or uses passlib, am I missing something?

### CODE REVIEW

**Comment by tivek** [comment]
AppVeyor's Python 3.3 tests fail with `nose.proxy.AssertionError: 'Hola Hello0' not found in Project: WARN: conanbuildinfo.txt file not found in c:\users\appveyor\appdata\local\temp\1\tmp2cg6umconans\path with spaces`, does this have to do with passlib?

**Comment by memsharded** [comment]
An important question for @lasote. Is passlib actually being used by conan? I cannot find references to it in the codebase. Might be unused?

**Comment by lasote** [comment]
You are right. Passlib is not needed anymore. @tivek could you update the PR removing it? :smiley_cat:

**Comment by tivek** [comment]
The PR is squashed and ready.

**Comment by memsharded** [comment]
Many thanks!

**Pull request merged**
