### PR TITLE
Feature/solaris sparc

### PR DESCRIPTION
**Pull request by memsharded**
This is my rebase of @mropert work in https://github.com/conan-io/conan/pull/1019 to develop, with two minor fixes so the tests pass in Win too.

Submitting it for checking CI.

### CODE REVIEW

**Comment by mropert** [comment]
I'm away this week, I won't have access to Solaris machines to test until next monday.

**Comment by memsharded** [comment]
Ok, no worries @mropert. I will try to have CI passing for my rebase, and we can check next Monday, there is still time enough before the release, thanks!

**Comment by memsharded** [comment]
So @mropert, the build for this PR is green.
For your rebase, have you pushed your changes somewhere? I can try to fetch your failing tests or whatever and work on them.

**Comment by mropert** [comment]
I'm afraid I don't have access to my work here.
In any case, the failing tests were only reproducible on systems where ```CONAN_COMPILER``` is not compatible with GCC flags and scripts (such as Solaris' sun-cc).

**Comment by memsharded** [comment]
I see, thanks for your feedback, I will try to have a look and figure out, maybe mock the behavior to force it. Sorry for disturbing, I don't bother you more until next Monday :)
Cheers!

**Comment by memsharded** [comment]
Hi @mropert, this has been merged to develop, so if on Monday you could test it running from develop, that would be great. Also, this PR already contained your commits, so I think https://github.com/conan-io/conan/pull/1019 could be closed if everything ok. Thanks!

**Comment by mropert** [comment]
Tests run on Solaris SPARC, everything OK except the config test that only works on x86 so I'd say it's good

**Pull request merged**
