### PR TITLE
allow negotiated conditions for build_requires in profiles

### PR DESCRIPTION
**Pull request by thorsten-klein**
Changelog: (Bugfix): Allow negotated conditions for build_requires in profiles (#10193)
Docs: https://github.com/conan-io/docs/pull/2328

- [x] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [x] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Review by memsharded — COMMENTED** [review]
Hi @thorsten-klein 

I have reviewed this, and contributed a commit, simplifying a bit the test and removing some unnecessary bits.

I have checked the proposal, and I am not sure it will be useful in the general case. The issue with ``!tool1*:tool2/1.0`` is that it is very difficult to control to what packages the ``tool2`` package will be applied as build_require. Once you negate ``!tool1``, it will be applied to all packages, except ``tool1``. If there is some other package that shouldn't get it as build_require, there is no way with this approach to represent it.

With the positive approach, as it is additive, it can be represented, one condition at a time. In the provided test it is as simple (without requiring any other change) with specifying the profile:

```
            [build_requires]
            tool2*:tool1/1.0
            consumer*:tool2/1.0
```
will make the test pass.

We are considering other approaches of specifying build_requires for Conan 2.0, that might help with this case.

**Comment by thorsten-klein** [comment]
Thanks a lot! :)
Yes, this is the disadvantage of the approach: in case of more than 2 tools it does not scale anymore. I also opened some issue for conan 2. I suggest to use some &+ pattern.

As you wrote consumer*, this does not work for bigger projects, since we do not know the name of all requirements. So we cannot find a pattern matching them all. 

What do you think about a &+ pattern?

**Comment by thorsten-klein** [comment]
How shall we proceed with this PR? Do we merge it this way nevertheless? Or what is your plan?

**Comment by thorsten-klein** [comment]
How shall we proceed with this PR? Do we merge it this way nevertheless? Or what is your plan?

**Comment by thorsten-klein** [comment]
Outdated. No need to fix it anymore.

**Pull request closed without merging**
