### PR TITLE
Some docstrings for version class

### LINKED ISSUE #4164: Make Version class importable from conans
To help us debug your issue please explain:

We already expose the Version class to the interface of the users in recipes, for example in the `get_version()` method of CMake and MSBuild build helpers. It is also useful to check and compere versions in `configure()` and there are some examples of its use like this
https://docs.conan.io/en/latest/howtos/check_conan_version_in_conanfile.html#id1

Importing from an internal module (`from conans.model.version import Version`) is something that could brake recipes in case we want to refactor the code and move that class to other place.

My suggestion is to make the import possible like this in recipes: `from conans import Version`.

### PR DESCRIPTION
**Pull request by danimtb**
Changelog: omit
Docs: omit

### CODE REVIEW

**Comment by memsharded** [comment]
Yes, if we are going to make the class public, we first need to make sure about the api it is exposing, and its behavior, and that will require some study.

**Comment by jgsogo** [comment]
Thinking about usages:
 * build his own object: `v = Version("string", loose=True|False)` (will raise if not valid string)
 * store and object returned by MSBuild, CMake,...: `v1 = CMake.get_version()`
 * compare with another one (spaceship operator):
    - `v1 == v2`
    - `v1 ~= v2`: equality not considering prerreleases? not considering `patch` release (if we include it)? applying some global policy?
    - `v1 < v2`: strict less/greater than
 * dump to string
 * divide into chunks (something like `urlparse`?) to do a custom comparaison?

**Comment by danimtb** [comment]
Exposing the version class through the ``conans`` module makes no sense now according to #4875. However, the doctrings in this PR might be useful.

Should I remove the import modification to move this forward or just close this PR?

**Comment by lasote** [comment]
Sure, clean the import and we can merge it. Also the new tests add value.

**Comment by lasote** [comment]
Renamed PR :laughing:

**Comment by danimtb** [comment]
Removed import!

**Pull request merged**
