### PR TITLE
[tools] import tools as object

### PR DESCRIPTION
**Pull request by uilianries**
Related to #7105

/cc @memsharded 

* Import an object (hacking a bit the import system):

Pretty similar to #7396, however, I see it like "sweep tools under the rug".

* PROS
  * Tools is virtually coupled only, no longer require the prefix self.

* CONS
  * We will need to move all from conans/tools.py (e.g. os_info) to avoid any possible name collision

### CODE REVIEW

**Comment by uilianries** [comment]
@memsharded I've update Tools import as object. The test that I've updated here, they are working and can be used as example.

**Comment by jgsogo** [comment]
I really like the outcome of this approach, but there is an issue here that is not taken into account: the `output` object used by the tools should be the one corresponding to the `conanfile` object (with the reference as prefix), we cannot use the one from the API. And this introduces some complexity if we consider parallelism (different recipes require different `output` object).

Same happens with the `conanfile` object itself. Some tools require it, if we are no longer passing it as the first argument, then we need to store it inside the `tools` object.

Nevertheless, after having a look to the PR it should be easy to create and inject a different `tools` object per recipe... getting rid of globals/singletons 🙌 

---

I don't like:
 * We need some more effort if we want to keep using the tools outside a Conan-loaded python module.
 * Tools that use data from the `conanfile` object will be magical:

   ```python
   def build(self):
       if tools.is_crossbuild():  # No arguments, no `self`,... where are settings coming from?
          ...
   ```

**Comment by uilianries** [comment]
> I really like the outcome of this approach, but there is an issue here that is not taken into account: the `output` object used by the tools should be the one corresponding to the `conanfile` object (with the reference as prefix), we cannot use the one from the API. And this introduces some complexity if we consider parallelism (different recipes require different `output` object).
> 
> Same happens with the `conanfile` object itself. Some tools require it, if we are no longer passing it as the first argument, then we need to store it inside the `tools` object.
> 
> Nevertheless, after having a look to the PR it should be easy to create and inject a different `tools` object per recipe... getting rid of globals/singletons raised_hands
> 
> I don't like:
> 
>     * We need some more effort if we want to keep using the tools outside a Conan-loaded python module.
> 
>     * Tools that use data from the `conanfile` object will be magical:
>       ```python
>       def build(self):
>           if tools.is_crossbuild():  # No arguments, no `self`,... where are settings coming from?
>              ...
>       ```

Thanks for checking it, indeed I didn't consider parallel operation and it's problem, true.

> Tools that use data from the conanfile object will be magical:

We would need to add new method interfaces, removing the Conanfile parameter. But I like the idea having it magically, however, I don't know if would couple both Tools and Conanfile implicitly.

**Comment by jgsogo** [comment]
Somehow I like (I understand) that magic too.... but not sure if it is expected by everyone.

Tools and conanfile are coupled, just because we pass the conanfile as the first argument, or because the tools take attributes from a conanfile under the hood.

**Comment by lasote** [comment]
Had we agree on the interface we want for Conan 2.0? Should it be a ‘self.tools’ or similar? Should we remove any global import? Personally as user I would like to avoid any import (if possible) in a recipe.

So for me instead of trying to improve or ease or trick the current approach I would write how we want it and implement it on the 2.0 branch when the time comes.

**Comment by jgsogo** [comment]
This is the aim of the 3 PRs @uilianries has opened, and alternatives are listed in https://github.com/conan-io/conan/issues/7105, new alternatives can be considered, for sure.

**Comment by lasote** [comment]
Oh! I see. Thanks. The build helpers are also something we are importing that would be useful to discuss how we prefer it.

**Comment by memsharded** [comment]
A decision in https://github.com/conan-io/conan/issues/7105#issuecomment-724295225 has been taken, we are not following this approach.

**Pull request closed without merging**
