### PR TITLE
Import configparser from six for Python2 compatiblity

### PR DESCRIPTION
**Pull request by danimtb**
Changelog: omit
Docs: omit

@PYVERS: py27

- [x] Refer to the issue that supports this Pull Request: Conan CI Preflight Develop broken -> https://conan-ci.jfrog.info/blue/organizations/jenkins/Preflight_develop/detail/Preflight_develop/71/pipeline/16#step-107-log-1880
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by danimtb** [comment]
Seems doiung `from six.moves import configparser` is not enough as that only handles the casing issue (it was renamed from `ConfigParser` to `configparser`)

However, it does not cover the case when you want to use the new features of the class like `configparser.ConfigParser(delimiters=)` in this case, so you have to import the *backported* `configparser` instead.

**Comment by memsharded** [comment]
> However, it does not cover the case when you want to use the new features of the class like configparser.ConfigParser(delimiters=) in this case, so you have to import the backported configparser instead.

That is bad news. Please assess with @jgsogo if it could be easier to not use that feature, to use the backport, or what.

**Comment by memsharded** [comment]
Oh, or you mean that just using that import is ok? Then good!

**Comment by danimtb** [comment]
Yes, this PR makes it work.

What I meant is that `from six.moves import configparser` is not enough for both Py2 and Py3 because you want to use also the new `ConfigParser` params (not available in Py2 by default),

So for python 2 you have to use `from backports import configparser` and in python 3 a simple `import configparser` works fine.

**Comment by jgsogo** [comment]
Just a question: before merging the PR, it was working in the CI, and we are running Linux py2... why does it fail in the preflight? 

image

**Comment by danimtb** [comment]
🤔 I thought it was only tested in Python 3... In my my machine the tests for python 2 were failing due to this same error. Let's wait for the next preflight_ develop and see what happens 🍿👀

**Comment by memsharded** [comment]
Yes, this is very weird, it seems it should have failed before. Btw, this error also happened to me the other day, while running tests in py36 in Windows.

**Pull request merged**
