### PR TITLE
Fix bug in virtualenv deactivate script that causes PS1 to go unset

### PR DESCRIPTION
**Pull request by brianembry**
Currently deativate.sh script will unset PS1, which will cause environment issues.  Clean up script generation to not unset PS1, and restore the old PS1 correctly.

Before:
brian@dev:~build$ cat activate.sh
OLD_PS1="$PS1"
export OLD_PS1
PS1="(conanenv) $PS1"
export PS1
PATH="/home/brian/.conan/data/cmake_installer/3.11.3/conan/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin":$PATH
export PATH
CMAKE_ROOT="/home/brian/.conan/data/cmake_installer/3.11.3/conan/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830"
export CMAKE_ROOT
CMAKE_MODULE_PATH="/home/brian/.conan/data/cmake_installer/3.11.3/conan/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/share/cmake-3.11/Modules"
export CMAKE_MODULE_PATH

brian@dev:~build$ cat deactivate.sh
unset OLD_PS1
unset PS1
PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/brian/.fzf/bin"
export PATH
unset CMAKE_ROOT
unset CMAKE_MODULE_PATH

After:
$ cat deactivate.sh
export PS1=$OLD_PS1
unset OLD_PS1
PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/brian/.fzf/bin"
export PATH
unset CMAKE_ROOT
unset CMAKE_MODULE_PATH

### CODE REVIEW

**Comment by memsharded** [comment]
Hi @brianembry 

Thanks very much for your contribution fixing this. I think it makes sense.
It seems that some tests are failing in other platforms rather than Windows, could you please have a look to the CI, and try to fix them? If need, don't hesitate to ask for help, we will fix them.

**Comment by brianembry** [comment]
A further enhancement could be made here in that they could set a $CONANENV variable (or something, OLD_PS1 could is sufficient too) to prevent a user from double sourcing or calling deactivate without a environment setup first.

Also would be cool if you could specify a venv_name from the conanfile.

**Comment by memsharded** [comment]
> A further enhancement could be made here in that they could set a $CONANENV variable (or something, OLD_PS1 could is sufficient too) to prevent a user from double sourcing or calling deactivate without a environment setup first.

Yes, agree, this could be a nice enhancement

> Also would be cool if you could specify a venv_name from the conanfile.

I think that using the package name would be good, and that could be easily done.

**Comment by lasote** [comment]
Hi @brianembry please check this pr including your changes: https://github.com/conan-io/conan/pull/3391 and let me know if it makes sense the changes I introduced.

**Comment by brianembry** [comment]
Looks good

**Pull request merged**
