### PR TITLE
feat: add build_triplet on conf

### LINKED ISSUE #14962: [feature] Add `tools.gnu:build_triplet` to conf
### What is your suggestion?

Related to https://github.com/conan-io/conan/issues/14947

Instead of changing the recipe, it'd be great to have a conf mechanism to change the build triplet like:

```
[conf]
tools.gnu:build_triplet="build_triplet"
```
For now, it's only used by AutotoolsToolchain. The question is: Should the rest of the toolchains read that conf/s too?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

### PR DESCRIPTION
**Pull request by ErniGH**
Changelog: Feature: Add `tools.gnu:build_triplet` to conf.
Docs: Omit

Close: #14962

### CODE REVIEW

**Review by juansblanco — APPROVED** [review]
Looks good!

**Review by jcar87 — APPROVED** [review]
LGTM!

**Review by franramirez688 — APPROVED** [review]

**Comment by jcar87** [comment]
For context: 
for https://github.com/conan-io/conan/issues/14962 and https://github.com/conan-io/conan/issues/14947

From the documentation:
https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.72/html_node/Specifying-Target-Triplets.html#Specifying-Names

* When `os` and `arch` are both the same - Conan does not pass neither `--host` nor `--build` in Autotools toolchain 
* When cross building (`os`/`arch` are different for build and host), Conan will autoguess some values for _both_ `--host` and `--build`, but these are based on the most "default" cases and may not cover specifics. I can't think of a specific  where one may only one to override the guessed `build` triple - so long as it differs from the host one, autotools will be in cross-compilation mode anyway - but it's good to give the option in case Conan's guess is not the most accurate.
* There can be cases where we have "incompatible" Linux flavour were `os` and `arch` are the same. This could be modelled by a separate setting (e.g. a  subsetting in `os`) or not modelled at all (not recommended!). 
 
@franramirez688, for the third case -  I think there may be a case for replicating what we did in https://github.com/conan-io/conan/pull/15616/files here - in case anyone wants to "force" autotools into cross-building mode (this is telling autotools: do not try to run the executables you are building for the host platform) - that is, force Conan to pass `--build` and `--host` even when `os` and `arch` are the same. It would be around this line https://github.com/ErniGH/conan/blob/35b9792a257c5b4701038d6600ea9fb66d39bc4d/conan/tools/gnu/autotoolstoolchain.py#L71

Arguably the same goes for CMake - CMake assumes cross-compilation (or at least, `CMAKE_CROSSCOMPILING` evaluates to true) when `CMAKE_SYSTEM_NAME` is manually defined. We already have this as a _conf_, so technically it's already possible without touching recipes - but  we may want to listen to `tools.build.cross_building:cross_build` and "force" it as well (I saw a case recently in an issue :D ) Just a thought!

**Comment by franramirez688** [comment]
> @franramirez688, for the third case - I think there may be a case for replicating what we did in https://github.com/conan-io/conan/pull/15616/files here - in case anyone wants to "force" autotools into cross-building mode (this is telling autotools: do not try to run the executables you are building for the host platform) - that is, force Conan to pass `--build` and `--host` even when `os` and `arch` are the same. It would be around this line https://github.com/ErniGH/conan/blob/35b9792a257c5b4701038d6600ea9fb66d39bc4d/conan/tools/gnu/autotoolstoolchain.py#L71

@jcar87 I don't understand this comment correctly. That PR introduced a new conf in the `conan.tools.build.cross_building` function, i.e., available for all the toolchains, so they could use it right now. Did you mean to perform new tests using that conf through those toolchains?

**Pull request merged**
