### PR TITLE
[develop2] drop legacy test folder name for test_package

### PR DESCRIPTION
**Pull request by memsharded**
Close https://github.com/conan-io/conan/issues/5429

### CODE REVIEW

**Review by AbrilRBS — APPROVED** [review]

**Review by czoido — APPROVED** [review]

**Comment by czoido** [comment]
I can't see any tests in develop2 testing this, maybe we should add one

**Comment by memsharded** [comment]
> I can't see any tests in develop2 testing this, maybe we should add one

Because nowhere else in our codebase we were using ``test`` as a ``test_package`` folder, this is many years old legacy.
Is it possible to add some test testing that local folders ``test``, ``tests``, ``testing``, etc are not taken as a ``test_package``, but seems a bit overkill to test this no-feature?

**Comment by czoido** [comment]
> > I can't see any tests in develop2 testing this, maybe we should add one
> 
> Because nowhere else in our codebase we were using `test` as a `test_package` folder, this is many years old legacy. Is it possible to add some test testing that local folders `test`, `tests`, `testing`, etc are not taken as a `test_package`, but seems a bit overkill to test this no-feature?

I meant that we are not testing anywhere (or I could not find at least) the error message that appears if you do a `conan create . -tf=nonexistent_or_without_conanfile_folder` I thought that it would be tested, but it's not so related with this PR, so no problem

**Comment by memsharded** [comment]
> I meant that we are not testing anywhere (or I could not find at least) the error message that appears if you do a conan create . -tf=nonexistent_or_without_conanfile_folder I thought that it would be tested, but it's not so related with this PR, so no problem

Ok, that makes sense. It is working fine:
```
(conan2_36) λ conan create . -tf=kk
ERROR: test folder 'kk' not available, or it doesn't have a conanfile.py
```
but it could be covered by one test too, I'll try to add it later.

**Pull request merged**
