### PR TITLE
Add search in all remotes option

### PR DESCRIPTION
**Pull request by kaidokert**
Address #2161

### CODE REVIEW

**Comment by memsharded** [comment]
Hi @kaidokert 
Any question about the above review? Would you like help to move this PR forward?
Many thanks!

**Comment by kaidokert** [comment]
Hi, no all clear. Just havent had a chance to look at this at all again - in a few days.

**Comment by kaidokert** [comment]
Updated the code: not sure if it looks much better, tbh. I'll leave good output formatting to wiser heads :)

**Comment by memsharded** [comment]
Hi @kaidokert 
Thanks very much for updating the code. Good job, I think it is much better now. As next release is 1.0 and the betas are already there, we are not adding new features, only bug fixes. So lets merge it for 1.1, we will be further reviewing, and trying to help with tests, etc. Cheers!

**Comment by memsharded** [comment]
This PR commits are included in https://github.com/conan-io/conan/pull/2348

Such https://github.com/conan-io/conan/pull/2348 adds:
- Testing
- Refactoring internal search implementation
- Handle the backwards compat corner case of someone calling their remote "all"

https://github.com/conan-io/conan/pull/2348 will not be squashed to maintain your commits and acknowledge your contribution. Please follow up there. Thanks very much for your help!

**Comment by memsharded** [comment]
This has been merged and your commits are now part of the develop branch. Thanks!
It will be released in 1.1

**Pull request closed without merging**
