### PR TITLE
Visual studio multi toolset

### PR DESCRIPTION
**Pull request by jeroendv**
slighly modified visual_studio_multi generator that uses the Visual studio toolsets information instead of the visual studio version information.

This way a user can work on a project compiled against the v120 toolset using the latest visual studio 2017 IDE

### CODE REVIEW

**Comment by jeroendv** [comment]
this is a very very heavy copy and past of the original visual_studio_multi generator.
Not sure of the use-cases of the original one, so I didn't want to change it without community review.

**Comment by memsharded** [comment]
Yes, yes, go ahead and propose the refactor too. Not only for future code maintenance, it also really help in the review, to check what are the real differences between them, and understanding the proposed new generator

**Comment by SSE4** [comment]
I am not sure additional generator is needed. why not just add one more option to the existing generator?

**Comment by memsharded** [comment]
@SSE4 generators cannot have options controlled by user, there is no interface for that.

**Comment by SSE4** [comment]
@memsharded oh, I wasn't accurate, sorry. I was talking about extending current **visual_studio** multi generator to consider toolset.  e.g. currently it generates:
```conanbuildinfo_<configuration>_<platform>_<version>.props```
but it can be extended to:
```conanbuildinfo_<configuration>_<platform>_<version>_<toolset>.props```

**Comment by memsharded** [comment]
Ah, yes, that makes more sense, thanks :)

**Comment by jeroendv** [comment]
Actually, no the point is to replace the version with the toolset info, not
add the toolset info.

**Comment by memsharded** [comment]
Could you please try to formalize the problem you are trying to solve? I am missing some context here. 
Now, the package_id() has some default logic for toolsets, which might be enough for your purpose.

**Comment by jeroendv** [comment]
I have refactored the current 'visual_studio_multi' generator splitting it into two.

The original 'visual_studio_multi' generator is extended with the toolset info generating
`conanbuildinfo_<configuration>_<platform>_<version>_<toolset>.props`
as @SSE4 suggested
With an import/@condition attribute equal to for example
`$(Configuration)' == 'Release' And '$(Platform)' == 'x64' And '$(VisualStudioVersion)' == '14.0' And '$(PlatformToolset)' == 'v140'`

The drawback of this approach is that when conan.settings.compiler.version=14 is used to install some dependencies, then the dev is also forced to work on that particular project using Visual Studio 14.

the new 'visual_studio_toolset_multi' generator will generate a
`conanbuildinfo_<configuration>_<platform>_<toolset>.props`

Note the absence of the IDE version in the filename. The Visual Studio IDE version is also no longer present in the import/@condition attribute
`$(Configuration)' == 'Debug' And '$(Platform)' == 'win32' And '$(PlatformToolset)' == 'v110'`

This means that the following command can be invoked 
`$ conan install ./ -o settings.compiler.version=11 -o settings.compiler.toolset=v110 -g visual_studio_toolset_multi`
to install my project dependencies. this will work because the v110 toolset was first released with Visual Studio 2012, a.k.a. visual studio 11.0. ([version map info](http://marcofoco.com/microsoft-visual-c-version-map/) )

At this point I can however choose to make use of the new nice features that Visual Studio 2017 offers to work on my project. Because: 
* Visual Studio 2017 is capable of building a project against  the v110 toolset
* the import/@condition does not mention the Visual Studio version  that was used to install the conan dependencies.

If I were to use  the visual_studio_multi generator
`$ conan install ./ -o settings.compiler.version=11 -o settings.compiler.toolset=v110 -g visual_studio_multi`
then this would mean that I am restricted to working on my project in Visual Studio 2012, a.k.a. version 11. Opening my project in Visual Studio 2017 will succeed (i.e. the IDE does not complain) but the generated property files will not be imported due to the version mismatch. Any subsequent build will therefor fail.

I hope this explains my use-case.

**Comment by memsharded** [comment]
I have suggested some refactors to the PR in https://github.com/jeroendv/conan/pull/1

While doing them, I have realized that maybe we want to have just 1 generator, the previous ``visual_studio_multi`` and have it automatically use toolsets if they are defined as settings. @SSE4 you were the contributor of  ``visual_studio_multi``, what do you think?

**Comment by SSE4** [comment]
@memsharded yep, using toolset sound logical - e.g. user won't need to re-install conan libraries if he switched Visual Studio version, but used the same toolset.

**Comment by memsharded** [comment]
Thanks for the feedback @SSE4 

So the proposal would be:
- Just one ``visual_studio_multi`` generator
- If the setting ``self.settings.compiler.toolset`` is None or undefined, just use the old behavior, with ``VisualStudioVersion``
- If the setting ``self.settings.compiler.toolset`` is defined, then use it instead of the ``VisualStudioVersion``

We could go one step further, and create always the file for toolsets, not for ``VisualStudioVersion`` taking the default toolset for each compiler version. What do you think @jeroendv @SSE4 ? Thanks!

**Comment by SSE4** [comment]
default toolset sounds reasonable

**Comment by jeroendv** [comment]
yup I would go all the way and use the default toolset. 
In my opinion there is no reason to include the visual studio version at all in the generator. It does not impact the ABI.

**Comment by memsharded** [comment]
Merged! Will be in 0.30, many thanks!

**Pull request merged**
