### PR TITLE
Add filter for extract tools

### PR DESCRIPTION
**Pull request by MathPlayer**
- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [x] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. Also adding a description of the changes in the ``changelog.rst`` file. https://github.com/conan-io/docs

This pull request implements #2938 
The pull request for documentation is conan-io/docs#689

### CODE REVIEW

**Comment by memsharded** [comment]
CI looks good, it should have finished already, but the Windows machines seem to be frozen. We will have a look when possible, don't worry about that.

**Comment by lasote** [comment]
It looks like the test is failing in Windows. Thanks for your contribution!!!

**Comment by MathPlayer** [comment]
I used `/` as a path separator which is not converted to `\`, so the test was failing on Windows environments.
I added another commit to fix this problem.
Unfortunately, I don't have a Windows machine at hand, so I hope the problem was only with the test and not with the fnmatch wildcard.

**Comment by memsharded** [comment]
And merged! I will run now a quick check, I wonder if it is possible that a zip in Windows or something might have the forward slash and fail. I might add a test directly to develop.

Thanks again for this good contribution!

**Pull request merged**
