### PR TITLE
Do not modify slashes on env variables (EnvValues)

### LINKED ISSUE #3827: Conan replaces backslashes with forward slashes in env_info variable in activate.bat
Conan replaces all backslashes with forward slashes in activate.bat (and activate.ps1 and activate.sh). This means that to use a variable to pass the path to an executable, we have to manually convert the forward slashes back to backslashes.

I am using Conan 1.8.4 on Windows on Python 3.6. I have created a conanfile.py which contains the following:
```python
from conans import ConanFile
import os.path

class TestPkgConan(ConanFile):
    name = "TestPkg"
    version = "0.0.1"
    description = "A test package"
    settings = "os", "arch"

    def package_info(self):
        self.env_info.testpkg_root = self.package_folder
        self.env_info.testpkg_normalized = os.path.normpath(self.package_folder)
        self.env_info.testpkg_test = 'AC\\DC'
```
and I get the following activate.bat from the virtualenv generator
```cmd
@echo off
SET PROMPT=(conanenv) %PROMPT%
SET testpkg_root=C:/.conan/data/TestPkg/0.0.1/adam/testing/package/ca33edce272a279b24f87dc0d4cf5bbdcffbc187
SET testpkg_normalized=C:/.conan/data/TestPkg/0.0.1/adam/testing/package/ca33edce272a279b24f87dc0d4cf5bbdcffbc187
SET testpkg_test=AC/DC

```
I would expect the environment variable to be set verbatim to the value I chose. And the job of doing path separator conversion to be the packagers, however given that conan seems to do path separator conversion I would at least expect it to output windows native paths for files which are supposed to be consumed by Windows native tools, i.e. activate.bat and activate.ps1.

### PR DESCRIPTION
**Pull request by jgsogo**
Changelog: Fix: environment variables are passed verbatim to generators.

- [x] closes #3827 
- [ ] feedback about windows subsystems

Green CI, but I'm sure we are going to break something... 😰

### CODE REVIEW

**Comment by danimtb** [comment]
Might this be breaking for windows subsystems when the virtualenv generator is used?

**Comment by jgsogo** [comment]
It's worth a test, @danimtb 🙄

**Comment by danimtb** [comment]
This might require some expertise on the topic. @SSE4 WDYT? We are are a bit worried as this PR might brake env variables in Windows subsystems

**Comment by SSE4** [comment]
I didn't use VirtualEnv generator(s) with Windows subsystems, so this need to be tested (manually or automatically)

**Comment by jgsogo** [comment]
This changes the behavior or `EnvValues` class, it is not restricted to `virtualenv` generator. That's the reason it scares us so much.

**Comment by danimtb** [comment]
I did the test of virtualenv manually inside a windows subsystem and calling activate.ba with \\ in env vars worked well. However, using those env vars to call a subsytem utility might be the breaking thing. That's why this does not only applies to virtualenv generator but to env vars used in builds running inside a windows subsystem

**Comment by lasote** [comment]
So, let's merge it.

**Comment by jgsogo** [comment]
@lasote! @danimtb says:

> However, using those env vars to call a subsystem utility might be the breaking thing. That's why this does not only applies to virtualenv generator but to env vars used in builds running inside a windows subsystem

We need to check not just the `virtualenv` generator, but the `subsystem` utility, as it is marked in the checklist of the PR.

Revert and open again.

**Comment by lasote** [comment]
If I'm merging this is because obviously, replacing a char in a variable that it is not a path, is a bug. I'm totally sure we are breaking something, with the subsystems and much more. When the problems arise we will need to provide a better interface or simply will say to the user "do a replace in your variable manually". So anyway this should be merged. Keep the subsystems investigation to investigate the possible fix ASAP if needed. WDYT @memsharded @danimtb

**Comment by danimtb** [comment]
I have just build ffmpeg with this change and seems unaffected but it might be not using env vars for include paths or other things, so I agree with @lasote. Modifying env vars implicitly is something we should not be doing

**Comment by memsharded** [comment]
There are 2 opposed bugs here in this case: one bug is changing the slash, and the other one is not changing it when it is a path. I am not 100% sure, but I'd tend to favor the case we can reproduce in tests and we are sure it is a real bug (reported by user), instead of the case we don't fully know and can't reproduce yet, and when we reproduce it, the solution should be probably elsewhere rather in this automatic replace of slashes. Lets keep this merged and will come with a proper solution for the paths when possible/necessary.

**Comment by jgsogo** [comment]
Ok, agree with it. But this PR does not pay Goikos :x:🍔

**Pull request merged**
