### PR TITLE
Fix #5924 3. Extra separator in Windows

### LINKED ISSUE #5924: [bug] Minor fixes to virtualenv generators
Although there is a major refactor related to Conan virtualenvs (https://github.com/conan-io/conan/issues/5821) there are some minor issues that can be addressed in advance, **they have been marked with a `FIXME` keyword in https://github.com/conan-io/conan/pull/5828/files**

 1. `PS1` is not properly handled in MacOS: https://github.com/conan-io/conan/blob/4217bb326e02e14c8168b080ef1e7a07c18795c8/conans/test/functional/generators/virtualenv_test.py#L188

 2. Trailing blanks with lists: https://github.com/conan-io/conan/blob/4217bb326e02e14c8168b080ef1e7a07c18795c8/conans/test/functional/generators/virtualenv_test.py#L220

 3. Extra separator for list of paths in Windows: https://github.com/conan-io/conan/blob/4217bb326e02e14c8168b080ef1e7a07c18795c8/conans/test/functional/generators/virtualenv_test.py#L245

All of them should be easy to fix and there are tests already available to check they work properly.   **Better if they are fixed in different PRs**.

### PR DESCRIPTION
**Pull request by nicememory**
Changelog: (Feature | Fix | Bugfix): Describe here your pull request
Docs: https://github.com/conan-io/docs/pull/XXXX

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by jgsogo** [comment]
I'd have thought that the implementation would be easier... I thought that the line originating the problem was [`value = path_sep.join(value + [placeholder])`](https://github.com/conan-io/conan/pull/6007/files#diff-27295679c78347c910d20b9e59c47849R70) with an empty `placeholder`. So it would be easier to check for an empty value in that variable than implement the if/else's in the resulting script.

I need to have a closer look at the problem, and probably check-out your branch.

**Comment by nicememory** [comment]
I thought so. But the contexts the generated scripts run with and the python code generating the scripts run with may totally different. For example, when I run the unit test from PyCharm, the python code 
 "PROMPT" in os.envron is false, but the generated scripts show me that PROMPT=$P$G.
At last, I decided to do the checks in generated scripts. It's quirky but works.

**Comment by jgsogo** [comment]
Hi, @nicememory . Sorry for the delay having a look into this...

First of all, it is better if the changes for #5818 go to a different PR, those are easy changes and can be merged right away.

---

About the _extra separator_: I see the problem and the way you have fixed it, it is a really smart one. 

Before anything else, let me add more context: we are working on a PR related to the way we are declaring and using the environment variables for these virtualenvs (https://github.com/conan-io/conan/pull/5989), as you can see the idea is to declare the variables in a separate file and use the scripts to read them and activate. Having the variables in a different file makes it easier to use them from other tools like the IDE plugins we maintain ([Visual Studio](https://github.com/conan-io/conan-vs-extension), [CLion](https://github.com/conan-io/conan-clion-plugin)).

With that PR we will have a for-loop in the script so we cannot have `:{name}L1` and `:{name}L2` in the cmd, we will need a workaround like the one implemented for PowerShell. It should be possible with something like the following [around these lines](https://github.com/conan-io/conan/pull/5989/files#diff-27295679c78347c910d20b9e59c47849R52):

```bash
    FOR /F "usebackq tokens=1,* delims={{delim}}" %%i IN ("{{ environment_file }}") DO (
        if "%%j:~-1%" eq ";"  ....
    )
``` 

I think that the original changes of this PR would be better added on top of #5989.

Thanks a lot!

**Comment by nicememory** [comment]
Got it, I'll improve the code and request a new PR.

**Pull request closed without merging**
