### PR TITLE
Fixing diamonds with alias

### PR DESCRIPTION
**Pull request by memsharded**
- [x] Refer to the issue that supports this Pull Request.

Might address:
- https://github.com/conan-io/conan/issues/2583
- https://github.com/conan-io/conan/issues/2576

Alternative to PR: https://github.com/conan-io/conan/pull/2586/files

### CODE REVIEW

**Comment by fourbft** [comment]
Fixes the problem in my test scenario for me. Will check in the real world scenario, where the problem originally occurred - but this will take some time, as I have to migrate several conanfiles from conan 0.29 to 1.1.

**Comment by memsharded** [comment]
Thanks @fourbft for testing. Maybe, I think the patch is still valid for 0.29, you can try to apply those lines in your code, and run with 0.29 with those lines changed.

Please let me know how it goes, many thanks!

**Comment by fourbft** [comment]
Warning: Check in real world scenario did **not** succeed! Same problem persists:  Incompatible requirements obtained in different evaluations of 'requirements'. I'll try to extend my test scenario to reproduce the situation. (The real world scenario has two more levels of dependency than my first test scenario).

**Comment by memsharded** [comment]
Thanks @fourbft 
Looking forward your feedback. Any hint that helps to reproduce is very welcome.

Also take into account that if you have conditional requirements in your ``requirements()`` method, and they are conditioned on different options with different values in the branches that form the diamond problem, you might have a valid error of incompatible requirements, and the input configuration has to be changed to account for it. Not saying that this will be, but just a possibility you have in mind while checking.

Many thanks!

**Comment by fourbft** [comment]
Ok, was hard to reproduce. Only after mimicking our real world dependency structure in the demo scenario and only after rearranging the requires-calls to the same order as in the real world scenario, did the bug appear. So, there still seems to be a problem with the order of the self.requires() calls. In my first attempt, the demo scenario worked! Only after rearranging the order of the self.requires calls to that of the real world scenario did the bug appear. Its probably possible to strip the demo down further, but as the faulty behavior is hard to reproduce, I hope, you can find the problem with this scenario (even though it already has quite a complex structure). I'll attach a tar.gz file again, like my first demo, only with a "few" more components and a dependencies.
[conan_alias_bug_demo2.tar.gz](https://github.com/conan-io/conan/files/1807425/conan_alias_bug_demo2.tar.gz)

**Comment by fourbft** [comment]
Oh, and @memsharded you're welcome! After all, you are fixing bugs that block the advancement of our CI environment. The least I can do is to try to make the faulty behavior clear. For contributing a bugfix, my insights into conan are not deep enough, unfortunately.

**Comment by memsharded** [comment]
Some quick questions:

- ``exports = "conanfile.py"            #sets the correct exports for conan`` You know this is not necessary?
- Are you sure you want to massively use **alias** in your code? I think alias has some utility for decoupled teams, when you want to isolate some components... but within the same project, I think it is better to use explicit versioning.

I am trying to replicate that in a test, will keep you updated.

**Comment by memsharded** [comment]
Try to switch in CL:

```python
        self.requires( "CK/ALIAS@user/testing")
        self.requires( "CH/ALIAS@user/testing")
```
to
```python
        self.requires( "CH/ALIAS@user/testing")
        self.requires( "CK/ALIAS@user/testing")
```

**Comment by memsharded** [comment]
I think I have identified what was failing. Your project files were really useful, it took a long time to strip down things and get to understand the core issue, but I think it might be solved now.

Could you please update the branch and try again? Thanks!

**Comment by fourbft** [comment]
Great @memsharded !!
Will test new branch.
About using alias or fixed versions: We are operating a CI-Environment with several hundred components. We've been using fixed versions up to now, but that is a real nightmare with handling version numbers. Each time a component changes, you have to update version numbers in the conanfiles of all downstream packages. Even though we do this automatically (scripted), it is not ideal in several respects: you get new source commits each time, even though the software itself doesn't change. This commit results in a minor version increase, which again triggers downstream version updates and so on. Its hard to track, failing/faulty packages (that break downstreams) are (need to be) uploaded to the conan server, and the origin of a problem is hard to track down. That's why we want to switch to using aliases. They are absolutely ideal for this case: the sources of downstreams don't change when an upstream component is updated, but still the CI can build a chain of updated conan packages (which contain the build number as part of the version) and conan packages can be promoted to a release channel on the conan server only when the complete build chain succeeds (and only then, are the alias packages updated to point to the new, proven to work, packages).
I am quite aware, that we are stressing the alias-feature in conan. But then, a feature that only works in "simple cases" is not really a feature. :-)

**Comment by memsharded** [comment]
Thanks very much @fourbft for your detailed feedback.

It is a very interesting setup, indeed. I would say that also there are other users that highly value NOT building against the latest upstream package, but they want to be all version upgrades to be quite explicit. So when they bump an upstream version, it is not automatically used until consumers decide to use it. But highly depends on the flow, frequency, etc, sure.

I am going to share and discuss your feedback internally, there are valuable insights to be considered for future development.

**Comment by fourbft** [comment]
Good news @memsharded!
Your latest patch seems to work. Tested with my test scenario, a modified test scenario (order of require statements changed) and also in the real world case: local package creation (which failed before) and also inside the CI test environment. All works like a charm now. So: problem seems to be fixed!
Thanks a lot for the quick bugfix! It's really great work, you are doing there!!!

About fixed versions: of course, there is a use for fixed version specification. Especially in the open source world. I am not saying in the least, that you should drop that feature or prefer alias. Both have their use cases.
But within a Continuous Integration environment, you always want to pick up the latest versions of all components, compile and test them against each other and if successfull, deploy them. For this scenario, the alias feature of conan is ideal.

**Comment by memsharded** [comment]
Excellent!!!

Thanks again once more for the help and feedback.

**Pull request merged**
