### PR TITLE
[WIP] Conanfile external references

### PR DESCRIPTION
**Pull request by redradist**
This PR adds possibility to install package from external resource:
```conanfile
[requires]
nlohmann_json/3.10.2
icc/1.0.0 { git = "git@github.com:redradist/Inter-Component-Communication.git" }
```

- [x] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by madebr** [comment]
This is probably too early, but it would be nice if this could enable fetching recipes from subdirectories too.
That way, it would be much easier for people to try out pull requests or suggest fixes in issue tickets.
e.g.
```
conan create https://github.com/conan-io/conan-center-index.git:/recipes/boost/all boost@1.77.0
conan create https://github.com/conan-io/conan-center-index/tree/master/recipes/boost/all boost@1.77.0
```
I'll leave it up to you what syntax to use.

A syntax to specify the branch/subdirectory/commit should be determined.

**Comment by redradist** [comment]
@madebr @prince-chrismc @memsharded Initial draft implementation is done

I was able to implement parsing the conanfile and install package from git by url ...
Unfortunately, I do not know very well architecture of conan and I implemented it with bypassing ConanAPI class and also monkey-patching Profiler class

It would be nice if some experienced conan developer looked at this implementation and suggest some improvements

Here is my test conanfile:
```conanfile
[requires]
icc/1.0.0 { git = "git@github.com:redradist/Inter-Component-Communication.git" }
```

**Comment by memsharded** [comment]
As commented previously in the closed issue https://github.com/conan-io/conan/issues/7289: 

> I am sorry, but this is not possible. Not only Conan communicates with its own api to services, but there are many core things in Conan that cannot be implemented: the separation but complete connection between package recipes and package binaries, representation of different users and channels, resolution of version ranges, resolution of package revisions, searching for recipes, searching for binaries...

This relatively small change broke 1600 tests, basically half of the test suite. Fixing this would be a massive effort. This initial PR doesn't even scratch the surface of the issue, not even the model. Using the URL only is not enough in the majority of cases, because it is not using a fixed commit or tag to retrieve a pinned, fixed snapshot of the code. This breaks immutability, which will be core paradigm in Conan 2.0 (about to enter alpha stage).

Implementing something like this would be a huge effort that we don't have the resources to implement, not to say document, support and maintain in the future. It is not just the model that breaks, but tons of other features will be broken once the first model and basic recipe-download functionality is there, and there will be multitude of rough edges, and Conan codebase will gain a lot of extra complexity that will have a very bad negative impact on overall evolution efforts. We will revisit this concept later down the road, after 2.0, but at the moment, I am sorry, trying to introduce this is a massive risk that we cannot afford, so I am closing this PR. Thanks very much for contributing to Conan.

**Comment by redradist** [comment]
@memsharded 
> Implementing something like this would be a huge effort that we don't have the resources to implement, not to say document, support and maintain in the future. It is not just the model that breaks, but tons of other features will be broken once the first model and basic recipe-download functionality is there, and there will be multitude of rough edges, and Conan codebase will gain a lot of extra complexity that will have a very bad negative impact on overall evolution efforts. We will revisit this concept later down the road, after 2.0, but at the moment, I am sorry, trying to introduce this is a massive risk that we cannot afford, so I am closing this PR. Thanks very much for contributing to Conan.

You are saying that you do not have time and resources ... but who I am then ?
If I am interested in such feature and also other guys like @madebr also interested in it then probably it is deserve to be solved otherwise I start thinking that you are going to make `conan` centralized around `conan-center` and `JFrog` infrastructure that violates original idea

Also tests was broken because it was marked like `WIP` and I asked for suggestion about how to implement it properly, it has been already worked on my machine, but with some issues

**Comment by memsharded** [comment]
> You are saying that you do not have time and resources ... but who I am then ?

Implementing a feature is the fun, easy and quick part. Maintaining the feature, supporting thousands of users, responding thousands of tickets, talking (many times including videoconfs) with users to pair-debug something that is failing, obligated refactors of the codebase and test suite that are necessary during development and evolution of the tool, attending derivative works, testing, docs, that result from the initial idea in the next 3-6 years is like 95% of the job, something that we, the maintainers have to do.


> If I am interested in such feature and also other guys like @madebr also interested in it then probably it is deserve to be solved. I start thinking that you are going to make conan centralized around conan-center and JFrog infrastructure that violates original idea.

More than 80% of Conan usage comes from other servers rather than ConanCenter. Most big players besides Artifactory, like Sonatype Nexus, Gitlab and others like CloudSmith support Conan packages. Conan is massively decentralized, and we are very happy about it, and we will keep promoting such de-centralization. We were happy when @grafikrobot launched last week Barbarian https://github.com/bfgroup/barbarian, and we happily re-shared it in our social.

This feature is a very big technical risk for the project, it will have a negative impact on a majority of users, will drag and make slower and unhappier the development team over time, and will make the tool more difficult to develop and maintain, and we don't want to pursue this idea at this moment.

We of course understand how frustrating it is to get a PR rejected, but please don't overstep the line. Throwing accusations of us having a hidden agenda to centralize Conan is aggressive and completely uncalled for. Please check our [Code of Conduct](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md#code-of-conduct) to read more about the expected behaviour between the members of the Conan Community.

**Comment by redradist** [comment]
@memsharded 
> This feature is a very big technical risk for the project, it will have a negative impact on a majority of users, will drag and make slower and unhappier the development team over time, and will make the tool more difficult to develop and maintain, and we don't want to pursue this idea at this moment.

This feature is not risky, other package managers like cargo has it and it is proved by time.
Also this feature will make `conan` even more decentralized and I consider it as a good idea.
Not only it make it more decentralized, but it also will work for private github repository without need to run custom `conan-server` ...
There are lots of advantages of implementing this feature

**Comment by redradist** [comment]
@memsharded 
> We of course understand how frustrating it is to get a PR rejected, but please don't overstep the line. Throwing accusations of us having a hidden agenda to centralize Conan is aggressive and completely uncalled for. Please check our [Code of Conduct](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md#code-of-conduct) to read more about the expected behaviour between the members of the Conan Community.

Yes, it is frustrated that PR with working recipe need to be changed due to some internal rules should be applied that are not written in documentation ...

First of all it is necessary to simplify process of submitting recipe, CI should resolve all issues, if it is working, merge bot should merge it ... otherwise adding new library is a pain and it not the same experience like `npm`, `cargo` and other tools

Second, this feature should be added for example for private repositories ... postponing this feature you will only increase a technical depth for implementing it, and then when you will see that it is needed, it will be even harder to implement

**Comment by redradist** [comment]
@memsharded Also this feature could be useful in case of single `conan` file but different package providers:
```conanfile
[requires]
nlohmann_json/3.10.2
icc/1.0.0 { git = "git@github.com:redradist/Inter-Component-Communication.git" }
stx/1.0.0 { conan = "<conan server package repository>" }
```

**Comment by redradist** [comment]
@madebr Do you have some opinion on this topic ?

**Comment by redradist** [comment]
@memsharded Even thought you do not like this solution, I've created it as separate package:
https://github.com/redradist/conanex
https://pypi.org/project/conanex

@madebr I hope you at least will appreciate it
Also I created discussion on reddit https://www.reddit.com/r/cpp/comments/ucoyjs/conanex_conan_extended

**Comment by redradist** [comment]
@madebr
@prince-chrismc
@memsharded
I have updated `conanex` with support for `md5`, `sha256` and `sha512`, see README.md in https://github.com/redradist/conanex

I strongly suggest to add the similar feature to `conan`, because I'd like to see this feature in main `conan` and do not what to support external tool if implementation is too simple and it could be added in original `conan`

**Pull request closed without merging**
