### PR TITLE
Added root certificate for Let's encrypt

### LINKED ISSUE #9695: [question] Unable to connect to conancenter=https://center.conan.io
## Env
OS: Windows 10
conan: 1.40.2

## Log
```
λ conan search boost -r conancenter
ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))

Unable to connect to conancenter=https://center.conan.io
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```

```
λ conan create . # for local recipe
...
rapidjson/cci.20200410: Not found in local cache, looking in remotes...
rapidjson/cci.20200410: Trying with 'conancenter'...
ERROR: Failed requirement 'rapidjson/cci.20200410' from 'cppjieba/2.0.0'
ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

Unable to connect to conancenter=https://center.conan.io
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```

## More Info
It worked well several days ago, but failed today.

### PR DESCRIPTION
**Pull request by lasote**
Changelog: Bugfix: Added root certificate for Let's encrypt.
Docs: omit

More info [here](https://docs.certifytheweb.com/docs/kb/kb-202109-letsencrypt/#:~:text=From%20Sept%2030th%202021%20Let's,the%20ones%20for%20your%20website).

Clos[e] #9695

### CODE REVIEW

**Review by memsharded — APPROVED** [review]

**Review by memsharded — CHANGES_REQUESTED** [review]
A migration is needed removing cacert.pem, so it installs the new one.

**Review by memsharded — APPROVED** [review]

**Comment by Hrungnir** [comment]
And you just broke everyone that added self-signed certs in the cacerts.pem file

**Comment by memsharded** [comment]
> And you just broke everyone that added self-signed certs in the cacerts.pem file

Everyone adding self-signed certs in the cacert.pem file should just add the new certificate to their cacert.pem file and let their ``conan config install`` update it. Custom changes to files in the cache, (including cacert.pem) have been recommended to be managed with ``conan config install`` since a long time ago.

**Comment by Hrungnir** [comment]
makes sense, I appreciate the reply, perhaps the TLS section of the docs or conan config install just need a update regarding best practices here.

**Comment by memsharded** [comment]
> makes sense, I appreciate the reply, perhaps the TLS section of the docs or conan config install just need a update regarding best practices here.

Yes, it is very likely that the docs could be improved, thanks for pointing it out.

**Pull request closed without merging**
