### PR TITLE
Add GCC 9 to default settings.yml

### PR DESCRIPTION
**Pull request by Croydon**
Changelog: Feature: Add GCC 9 to default settings.yml
Docs: conan-io/docs#1257

- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.

I'm assuming that no separated issue is required for such a small change. Please correct me if I'm wrong with that assumption

### CODE REVIEW

**Comment by uilianries** [comment]
@Croydon please, add to the PR description:

Docs: https://github.com/conan-io/conan/pull/5046

**Comment by lasote** [comment]
The default stdcpp version has to be adjusted if needed and also search for any other specific flag etc

**Comment by lasote** [comment]
I can't find yet information about the default `-std` parameter for `gcc9`. It is very likely it is going to be the same as `gcc8` (gnu14), but I would prefer to have a confirmation before merging this. @Croydon @uilianries please try to gather that info.

**Comment by uilianries** [comment]
The GNU team has not yet provided GCC 9 [manual](https://gcc.gnu.org/gcc-9/), only the [changelog](https://gcc.gnu.org/gcc-9/changes.html).

But reading the [cxx-status](https://gcc.gnu.org/projects/cxx-status.html) pages:

> C++14 Support in GCC
>
> GCC has full support for the previous revision of the C++ standard, which was published in 2014.
>
> This mode is the default in GCC 6.1 and above; it can be explicitly selected with the -std=c++14 command-line flag, or -std=gnu++14 to enable GNU extensions as well.

So it should be C++14 ...

To make sure, I've used `conan new` to create a simple test with *conanio/gcc9*:

```cpp
#include <iostream>
int main() { std::cout << __cplusplus << std::endl; }
```

The result is: **201402**

YES, I can confirm it is C++14 by default.

**Pull request merged**
