### PR TITLE
Some more small code fixes

### PR DESCRIPTION
**Pull request by jputcu**
Changelog: Omit
Docs: Omit

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one.

### CODE REVIEW

**Review by memsharded — APPROVED** [review]
Fantastic, thanks!

**Review by AbrilRBS — APPROVED** [review]
TIL about NotImplementedError vs NotImplemented, great catch!
Need to double check that nothing os trying to catch the wrong one, but the changes look good

**Comment by jputcu** [comment]
This time, I can't take any credit, I just unleashed `pylint` and `pyflakes` source directories.
There are lots of warnings/hints, so perhaps it is worth a CI/CD step?

**Comment by memsharded** [comment]
> There are lots of warnings/hints, so perhaps it is worth a CI/CD step?

We might add it at some point, but we have been prioritizing testing over linting, typically because of the noise of false positives it can get a bit annoying (or nobody really looks at them as warnings in CI, only hard failures are paid attention...)

So I think at some point we want a quality build that includes linting, coverage, etc, but not sure how to introduce it in a way that it is not too annoying for the current status and dev flow.

**Comment by jputcu** [comment]
One way would be to only activate them for certain files or directories, especially new ones.
I understand you have a lot of work to do, so I won't try to bother you with the smaller ones.

**Pull request merged**
