### PR TITLE
Extended vs generator

### PR DESCRIPTION
**Pull request by claasd**
This PR adds individual fields for each requirement to the generated .props file.

These properties can be used in other visual studio files, e.g. as fixed path variable.

### CODE REVIEW

**Comment by memsharded** [comment]
Looks good, but sorry for my ignorance, but what would be the flow of using those variables? What problems are they solving? I mean, they are totally fine, very happy to have per-package variables like the CMake generator. Just wondering what do you mean they can be consumed "in other visual studio files, e.g. as fixed path variable.", read a bit about it, not evident to me. Thanks!

**Comment by claasd** [comment]
I solve two problems that I actually encounter:
First: I want to distribute common options for visual projects using conan. I package my_settings.props and install the via conan. With this feature, I could use 
```xml
<Import Project="$(Conan.MySettings.Root)/props/my_settings.props" />
```
Second: we are using not only pure C++, but also .NET ind CLR (Interop) Projects. These projects reference not the library, but the DLL (and directly, not via name and a list of pathes).
```xml
<Reference Include="nunit.framework">
  <HintPath>$(Conan.NUnit.Root)\bin\nunit.framework.dll</HintPath>
</Reference>
```
For both use cases, I just need the Root pathes. I added the others for completeness. Strictly speaking, this violates the YAGNI pattern. 
So I would suggest to remove everything but the root pathes, as the solve a use case that is currently not solved.

**Comment by memsharded** [comment]
Thanks for your explanation, understood.
Regarding the YAGNI, it is up to you, if you are >90% sure nobody will need them, remove the unused. If you think there is a chance that they are useful for someone else rather than you, I am not opposed to leave them. Please tell me so I can merge or wait for the changes.

**Comment by claasd** [comment]
I removed anything but the *.Root variables.

**Comment by memsharded** [comment]
Excellent, merged. Thanks!

**Pull request merged**
