### PR TITLE
unzip progress updated each seconds

### PR DESCRIPTION
**Pull request by ericLemanissier**
Beforehand it was updated for each file extracted,
leading to hudge console traffic for big archives

### CODE REVIEW

**Comment by memsharded** [comment]
Thanks for the contribution!
What do you mean with "leading to hudge console traffic"? Not sure about the problem with the current implementation

**Comment by ericLemanissier** [comment]
The very concrete problem is [failure to unzip the Qt sources on travis](https://travis-ci.org/ericLemanissier/conan-qt/jobs/287504965), because the log is too long:

    [==================================================] 565.1MB/565.1MB  
    Unzipping 1.57GB, this can take a while
    Unzipping 32 %                                                        
    The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
    The job has been terminated

**Comment by memsharded** [comment]
Oh! I see. Because the command line overwrites itself, but logging appends. Make sense, thank you!

**Comment by memsharded** [comment]
Have you considered using % increments, instead of time? In that way, the output length can be bounded, irrespective of the zip size. Just an idea

**Comment by ericLemanissier** [comment]
It occurred to me yes, and then I remembered the travis error "No output has been received in the last 10 minutes". I am not sure each percent takes less than 10 minutes in the CI context.
The best solution is probably to combine both approach, and update the progress if one of the following is true:
- 1 minutes happened since last update
- percentage changed since last update

**Comment by memsharded** [comment]
Great, many thanks!

**Pull request merged**
