### PR TITLE
Use 'revision' as the SVN's 'peg_revision' (broken for an edge case)

### LINKED ISSUE #5017: svn scm bug when using a tag
conan 1.14.3

We have a component that has a recipe called 'conanfile_policy.py' in a sub directory called 'policy'. See:
sophosmanager_dir

As part of our test build process this component gets tagged at the component root level ie above the policy dir, after the recipe was changed so a build can be done from the tag. The SVN revision graph showing this is:
sophosmanager_svn_tag

As part of our build process, Jenkins checks out the policy subdir using the tag and exports the recipe, this is preparation for doing a `conan create` on our 'product' recipe to build our entire product.

The url gets deduced incorrectly by scm auto in this export, which means Jenkins can’t `conan create` from the recipe for this component breaking the build. The exported recipe looks like:
```
scm = {"revision": "126",
           "type": "svn",
           "url": "svn+ssh://svnserver/svncmake/sophosmanager/tags/CONAN_REL_3.0.0-2/policy@125"}
```
The `conan create` fails because the tag does not exist at rev 125, only 126.

I think the issue might be how scm auto deduces the svn revision to create the url, it appears to use Last Changed Rev rather than the Revision attribute from the svn info. With a subdir under the tag, the Last Changed Rev doesn’t include the tag, as the tag didn’t occur in the subdir, but at the level above it.

### PR DESCRIPTION
**Pull request by jgsogo**
Changelog: Fix: Use `revision` as the SVN's `peg_revision` (broken for an edge case)
Docs: omit

closes #5017 

@TAGS: svn, slow

### CODE REVIEW

**Comment by jgsogo** [comment]
Motivated by https://github.com/conan-io/conan/issues/5017 we are thinking about changing `get_last_changed_revision` by `get_revision` to retrieve the _peg_revision_ for the URL. It is required for a use-case where it is being checked out a subtree of a tag to create the package (more details in the issue, and the test in this PR).

IMO, although it could lead to a different `peg_revision` it would still be valid, and we will _solve_ this use case. I'm pinging our _SVN users_ @climblinne, @aalmann, just in case they can point out some unexpected behavior due to this change. Thanks!

**Comment by lasote** [comment]
@Aalmann could you take a look? Thanks!

**Comment by Aalmann** [comment]
Looks good to me.
@ahauan4 can you test it with one of your repos? #5017 describes a similar layout to yours.

**Comment by ahauan4** [comment]
@Aalmann We had not a problem so far, because we check out the trunk/branches/tag directory directly on Jenkins.
Our setup is: `repo_root/category_name/module_name/<trunk|branches|tags>/conanfile.py`

One disadvantage of using `get_revision` instead of `get_last_changed_revision` could be, that if we build the same thing twice after the revision counter increased (because of checkins in a different module), we would get different revisions published in the final package. But as long as this won't affect the hash, it would be ok from my side.

**Comment by lasote** [comment]
@Aalmann @ahauan4 Are you using the [package revisions](https://docs.conan.io/en/latest/mastering/revisions.html?highlight=revisions) mechanism? In that case, if you export the recipe again you will get new package revision because of the captured URL with change with the new (svn) revision counter. But the `package_id` won't change in any case.
Are you ok then?

**Comment by jgsogo** [comment]
The change from `get_last_changed_revision` to `get_revision` is done only for the `peg_revision` but not for the revision to checkout, so in your case, @ahauan4, the _problem_ was there and will still be. 

About the `hash`: each time the recipe is exported (if there is any `"auto"` in the SCM dictionary) those `"auto"` will be resolved and substituted. If there are new commits, then the `peg_revision` and the `revision` will change (the second one for sure, and the first one since this PR) and the `hash` of the recipe will change (but it was changing before too).

**Comment by ahauan4** [comment]
@lasote We don't use the package revisions feature.
I meant `package_id` instead of hash. Sorry for beeing unclear.
So as long as the `package_id` won't change, we should be ok.

**Comment by Aalmann** [comment]
@lasote and @jgsogo 
We are not using the package revisions at the moment. So everything is fine. Go for it.

**Comment by jgsogo** [comment]
Thanks all for your feedback!  😸 

@keithrob91, if it is not blocking you, we will release it with `1.16`, is it ok?

**Comment by keithrob91** [comment]
That is fine. Thank you.

**Pull request merged**
