### PR TITLE
Feature/conan app

### PR DESCRIPTION
**Pull request by memsharded**
Changelog: Omit
Docs: Omit

From the user point of view this seems a pure refactor, nothing changed for users. but:

- This PR manages to create a completely new sets of architectural collaborators for each conan_api call (the ones decorated with api_method), to make it match the behavior of the conan command line.
- It also uses exactly the same construction logic for production and testing uses
- It removes the "invalidating cache" methods from some components that were necessary to avoid caching issues
- This PR opens the door to pass the "app" object as argument instead of a miriad of collaborators to methods, and also to do lazy creation of collaborators, to create them only when strictly necessary (some users were requesting to lazy loads "python-requests", because it is slow)
- Changes in tests are strictly format or architecture, not behavior.

@tags: slow, svn

@jgsogo. the problem with the warnings was the cacert.py module doing logging.captureWarnings(True). The order of importing thing mattered.

### CODE REVIEW

**Comment by memsharded** [comment]
Hi @jgsogo I need your help here. There are 4 tests failing because of the ``catch_deprecation_warnings``:
The warning is being called, but the final list is empty

**Comment by jgsogo** [comment]
A couple of insights:
 * if you run all the tests in a file, only **the first one fails**
 * first time in `warnings._showwarnmsg` function (called from `warnings.warn(...)`), the memory address of `warnings.showwarning` is different

 🤷‍♂

**Comment by jgsogo** [comment]
[Nice catch](https://github.com/conan-io/conan/pull/5517/commits/b925fafa700ce8b8a0dad7258d999707ce2a7330)!! 🙌 

Nevertheless, I think it would be better to `captureWarnings` just for the scope of the request, not at module level... that way we won't have the problem again.

**Comment by memsharded** [comment]
Yes, I agree, but the problem is that such captureWarnings is kind of global now for the whole logging module, isn't it? I am not aware that it can be applied per module.
I didn't want to change it in this PR, it doesn't belong to it, and it already has a big FIXME in it, it will certainly deserve more time. If you know an easy fix to apply it per module, please tell, otherwise I think it can wait.

**Comment by jgsogo** [comment]
According to [these docs](https://docs.python.org/3.7/library/logging.html#integration-with-the-warnings-module), it should be enough to call `logging.captureWarnings(True/False)` in the `try/finally` block of the `_call_method` function. 

I agree it is not for this PR, I can make a tentative one with just this change to see what happens.

**Comment by lasote** [comment]
I'm merging this, please tell me if further stuff related with the warns is needed to be merged for 1.18.

**Comment by jgsogo** [comment]
I'm opening a related issue here for that detail: https://github.com/conan-io/conan/issues/5550

**Pull request merged**
