### PR TITLE
Changed package requirements to include distro version 1.5.0

### LINKED ISSUE #7455: Enable support for 'distro 1.5.0'
When upgrading `conan` (command `sudo pip3 install conan --upgrade`),  the pre-existing package `distro` is downgraded from version 1.5.0 to 1.1.0, see log snippet below. 

```
Installing collected packages: distro
  Attempting uninstall: distro
    Found existing installation: distro 1.5.0
    Uninstalling distro-1.5.0:
      Successfully uninstalled distro-1.5.0
Successfully installed distro-1.1.0
```

Unfortunately, downgrading `distro` will break projects that depends on `distro` version 1.5.0. Would it be possible to make `conan` also support `distro` version 1.5.0 or higher?

### Environment Details
* Operating System: **macOS**
* Operation System Version: **Catalina**
* Conan version: **conan 1.27.1**
* Python version: **python 3.8.5**

### Steps to reproduce 
1. Install `distro` 1.5.0:<br> `sudo pip3 install distro`
2. Upgrade `conan`:<br> `sudo pip3 install conan --upgrade`
3. Observe `distro` getting downgraded from version 1.5.0 to 1.1.0.

### Build logs 
Full log:
```
Requirement already up-to-date: conan in /usr/local/lib/python3.8/site-packages (1.27.1)
Requirement already satisfied, skipping upgrade: Jinja2<3,>=2.3 in /usr/local/lib/python3.8/site-packages (from conan) (2.11.2)
Requirement already satisfied, skipping upgrade: future<0.19.0,>=0.16.0 in /usr/local/lib/python3.8/site-packages (from conan) (0.18.2)
Collecting distro<1.2.0,>=1.0.2
  Downloading distro-1.1.0-py2.py3-none-any.whl (16 kB)
Requirement already satisfied, skipping upgrade: PyJWT<2.0.0,>=1.4.0 in /usr/local/lib/python3.8/site-packages (from conan) (1.7.1)
Requirement already satisfied, skipping upgrade: pyOpenSSL<19.0.0,>=16.0.0; sys_platform == "darwin" in /usr/local/lib/python3.8/site-packages (from conan) (18.0.0)
Requirement already satisfied, skipping upgrade: fasteners>=0.14.1 in /usr/local/lib/python3.8/site-packages (from conan) (0.15)
Requirement already satisfied, skipping upgrade: patch-ng<1.18,>=1.17.4 in /usr/local/lib/python3.8/site-packages (from conan) (1.17.4)
Requirement already satisfied, skipping upgrade: node-semver==0.6.1 in /usr/local/lib/python3.8/site-packages (from conan) (0.6.1)
Requirement already satisfied, skipping upgrade: bottle<0.13,>=0.12.8 in /usr/local/lib/python3.8/site-packages (from conan) (0.12.18)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.4,!=1.25.5 in /usr/local/lib/python3.8/site-packages (from conan) (1.25.10)
Requirement already satisfied, skipping upgrade: colorama<0.5.0,>=0.3.3 in /usr/local/lib/python3.8/site-packages (from conan) (0.4.3)
Requirement already satisfied, skipping upgrade: deprecation<2.1,>=2.0 in /usr/local/lib/python3.8/site-packages (from conan) (2.0.7)
Requirement already satisfied, skipping upgrade: tqdm<5,>=4.28.1 in /usr/local/lib/python3.8/site-packages (from conan) (4.48.0)
Requirement already satisfied, skipping upgrade: cryptography<2.4.0,>=1.3.4; sys_platform == "darwin" in /usr/local/lib/python3.8/site-packages (from conan) (2.3.1)
Requirement already satisfied, skipping upgrade: pygments<3.0,>=2.0 in /usr/local/lib/python3.8/site-packages (from conan) (2.6.1)
Requirement already satisfied, skipping upgrade: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.8/site-packages (from conan) (2.8.1)
Requirement already satisfied, skipping upgrade: pluginbase<1.0,>=0.5 in /usr/local/lib/python3.8/site-packages (from conan) (0.7)
Requirement already satisfied, skipping upgrade: requests<3.0.0,>=2.8.1 in /usr/local/lib/python3.8/site-packages (from conan) (2.24.0)
Requirement already satisfied, skipping upgrade: six<=1.14.0,>=1.10.0 in /usr/local/lib/python3.8/site-packages (from conan) (1.14.0)
Requirement already satisfied, skipping upgrade: idna==2.6; sys_platform == "darwin" in /usr/local/lib/python3.8/site-packages (from conan) (2.6)
Requirement already satisfied, skipping upgrade: PyYAML<6.0,>=3.11 in /usr/local/lib/python3.8/site-packages (from conan) (5.3.1)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /usr/local/lib/python3.8/site-packages (from Jinja2<3,>=2.3->conan) (1.1.1)
Requirement already satisfied, skipping upgrade: monotonic>=0.1 in /usr/local/lib/python3.8/site-packages (from fasteners>=0.14.1->conan) (1.5)
Requirement already satisfied, skipping upgrade: packaging in /usr/local/lib/python3.8/site-packages (from deprecation<2.1,>=2.0->conan) (20.4)
Requirement already satisfied, skipping upgrade: asn1crypto>=0.21.0 in /usr/local/lib/python3.8/site-packages (from cryptography<2.4.0,>=1.3.4; sys_platform == "darwin"->conan) (1.3.0)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.7 in /usr/local/lib/python3.8/site-packages (from cryptography<2.4.0,>=1.3.4; sys_platform == "darwin"->conan) (1.14.0)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests<3.0.0,>=2.8.1->conan) (2020.6.20)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/site-packages (from requests<3.0.0,>=2.8.1->conan) (3.0.4)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /usr/local/lib/python3.8/site-packages (from packaging->deprecation<2.1,>=2.0->conan) (2.4.7)
Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.8/site-packages (from cffi!=1.11.3,>=1.7->cryptography<2.4.0,>=1.3.4; sys_platform == "darwin"->conan) (2.20)
Installing collected packages: distro
  Attempting uninstall: distro
    Found existing installation: distro 1.5.0
    Uninstalling distro-1.5.0:
      Successfully uninstalled distro-1.5.0
Successfully installed distro-1.1.0
```

### PR DESCRIPTION
**Pull request by DominikDeak**
Changelog: Fix: Changed _requirements.txt_ to include distro package version 1.5.0.
Docs: Omit

Close #7455 

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
Hi @DominikDeak ! Thanks for your contribution! Could you please sign the [CLA](https://github.com/conan-io/conan/pull/7461#issuecomment-666863160).

**Comment by jgsogo** [comment]
Hi! We need a policy for this kind of external dependencies. Changing the version can change the output of some Conan _autodetect_ features. This is very related to the compiler detection @SSE4 implemented, almost same situation.

**I agree to update this library**, but maybe we should add a disclaimer to the docs associated with the affected functions to tell the users that we are using `distro` under the hood and, depending on the version used, the results can be different. If this is not ok, then we shouldn't add a range for these dependencies, but a fixed version.

We need to be aligned, wdyt @conan-io/barbarians ?

**Comment by uilianries** [comment]
> depending on the version used, the results can be different

@jgsogo why not improving our regression tests instead? So we can predict any change from external packages.

**Comment by jgsogo** [comment]
> > depending on the version used, the results can be different
> 
> @jgsogo why not improving our regression tests instead? So we can predict any change from external packages.

Same problem as with the compiler detection, how many different docker images we need to run? How many different OS x platforms x ...? And those docker images... are they available or do we need to maintain them ourselves?

**Comment by memsharded** [comment]
I think we should work with this ideas in mind:

- Try to minimize the external dependencies and surface area. Embed when possible. Delegate to the user space when possible. Fork under different name when it makes sense. In general be more aware when introducing dependencies.

- Testing is indeed difficult. We will never cover all the cases with enough confidence, as the space is huge.

- Agree that it is necessary to document it correctly in the docs. I lean to accepting the range and documenting than being strict on the range and having users complaining because of conflicting distro versions.

**Review by danimtb — APPROVED** [review]

**Comment by jgsogo** [comment]
I'm adding a warning to the docs [here](https://github.com/conan-io/docs/pull/1812) (almost a disclaimer)

**Review by memsharded — APPROVED** [review]

**Pull request merged**
