### PR TITLE
Add a test to ensure that #6288 is reverted in v1.22

### PR DESCRIPTION
**Pull request by jgsogo**
Replace https://github.com/conan-io/conan/pull/6292

Changelog: omit
Docs: omit

This test ensures that changes introduced in #6288 won't be deployed in Conan v1.22:
 * The test fails with changes introduced in that PR
 * The test fails if the version is >=1.22.0

Rationale: https://github.com/conan-io/conan/issues/6269#issuecomment-570182130

### CODE REVIEW

**Comment by jgsogo** [comment]
After merging https://github.com/conan-io/conan/pull/6429, this PR should pass (we can then safely close it)

**Comment by memsharded** [comment]
I think this can be closed now that https://github.com/conan-io/conan/pull/6429 has been merged

**Comment by jgsogo** [comment]
Let's do it the right way, let's check that after merging `develop`, the tests pass

**Comment by memsharded** [comment]
> Let's do it the right way, let's check that after merging develop, the tests pass

Oh, I already did that. I merged develop and ran the tests locally, it was all good. I just didn't want to burn more CI cycles for such a quick test.

Good, it seems CI says it is green, we can close it now.

**Pull request closed without merging**
