### PR TITLE
If retrieving the url with user agent set fails, try without

### PR DESCRIPTION
**Pull request by mathieu**
I was getting 401 on simple downloads : http://zlib.net/zlib128.zip with the user agent set and not without. 

This is a simple patch, maybe a bit too simple, but made my conan works. What do you think ?

### CODE REVIEW

**Comment by lasote** [comment]
I'm not sure about that. I think at least it should check that the error is a 401, It gives you some text with the 401? I would like to try directly with requests library and check what it happens. Despite this it's a good think that you have noticed this problem.

**Comment by mathieu** [comment]
Here is a log of a fork of lib@lasote build on a CI (bamboo) I do get 401 from time to time...

```log
11-Jan-2016 18:33:11	
11-Jan-2016 18:33:11	It seems to be the first time you run conan
11-Jan-2016 18:33:11	Auto detecting your dev setup to initialize conan.conf
11-Jan-2016 18:33:11	Found gcc 4.2
11-Jan-2016 18:33:11	Found apple-clang 7.0
11-Jan-2016 18:33:11	CC and CXX: ,  
11-Jan-2016 18:33:11	Default conan.conf settings
11-Jan-2016 18:33:11	        os=Macos
11-Jan-2016 18:33:11	        arch=x86_64
11-Jan-2016 18:33:11	        compiler=apple-clang
11-Jan-2016 18:33:11	        compiler.version=7.0
11-Jan-2016 18:33:11	        build_type=Release
11-Jan-2016 18:33:11	*** You can change them in ~/.conan/conan.conf ***
11-Jan-2016 18:33:11	*** Or override with -s compiler='other' -s ...s***
11-Jan-2016 18:33:11	
11-Jan-2016 18:33:11	
11-Jan-2016 18:33:11	WARN: Conanfile doesn't have a 'license'.
11-Jan-2016 18:33:11	It is recommended to add the package license as attribute
11-Jan-2016 18:33:11	A new conanfile.py version was exported
11-Jan-2016 18:33:11	conanfile.py exported as zlib/1.2.8@cstb/stable.
11-Jan-2016 18:33:11	Folder: /Users/bamboo/.conan/data/zlib/1.2.8/cstb/stable/export
11-Jan-2016 18:33:12	Requirements
11-Jan-2016 18:33:12	    zlib/1.2.8@cstb/stable
11-Jan-2016 18:33:12	Packages
11-Jan-2016 18:33:12	    zlib/1.2.8@cstb/stable:3d700f06773ee4223af06e70e8e550d302626107
11-Jan-2016 18:33:12	Installing requirements
11-Jan-2016 18:33:12	WARN: Forced build from source: "zlib/1.2.8@cstb/stable"
11-Jan-2016 18:33:12	Building your package in /Users/bamboo/.conan/data/zlib/1.2.8/cstb/stable/build/3d700f06773ee4223af06e70e8e550d302626107
11-Jan-2016 18:33:12	Configuring sources in /Users/bamboo/.conan/data/zlib/1.2.8/cstb/stable/source
11-Jan-2016 18:33:12	ERROR: zlib: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x1058f8ef0>)
11-Jan-2016 18:33:12	Error while executing:
11-Jan-2016 18:33:12	         conan test -s arch=x86 -s build_type=Debug -o zlib:shared=False
11-Jan-2016 18:33:12	Failing task since return code of [/usr/bin/python build.py] was 1 while expected 0
```

I'm not sure what you meant by 
>  I would like to try directly with requests library and check what it happens.

**Comment by lasote** [comment]
Ok, thanks for the log. 
I meant that this request is done with urllib directly, maybe using "requests" library works better (maybe the author of requests library know the way to set the correct headers to avoid 401)

**Comment by mathieu** [comment]
I added a first shot using requests, It works, but I'm pretty sure that the reporting happens after the whole file has been downloaded not on the fly...

**Comment by lasote** [comment]
Hey! thanks for try it. I'm glad to know that SF redirect its handled directly. 
About the reporting, yes, I remember I read about some problems with progress in file download, in your code I think it first download the code and then write to file with the chunks, the result is that there is no visible report. 
Anyway, its a good job, I will try to fix that progress.

Thanks again!

**Comment by mathieu** [comment]
hi @lasote !Long time no see :-) I've looked the way pip did to report download and indeed they do the same I proposed in the PR (in a more complicated way since they uses caches and hashes to verify the downloads are correct). I think that the progress report is correctly reporting the download progress.

**Comment by memsharded** [comment]
Hi Mathieu,
Sorry, we didn't have time to check this, things are becoming quite busy, which is a good thing :)
We will try to check this soon. Thanks again for your contribution and your patience!
Cheers

**Comment by lasote** [comment]
Solved here #161 Thank you so much, your solution with "requests" library works good!
I used a Downloader class that we already had (I forgot we had it) and this class its almost your PR.
Now the download function is much more clean and robust. :+1:

**Pull request closed without merging**
