### PR TITLE
check usage f urllib3

### LINKED ISSUE #8041: [bug] Conan 1.31.1 does not work since urllib3 1.26.0 release
### Environment Details (include every applicable attribute)
  * Operating System+version: Centos 7.8
  * Compiler+version:
  * Conan version: 1.31.1
  * Python version: 3.6.8

### Steps to reproduce (Include if Applicable)

pip3 install conan

```
Collecting conan
  Using cached https://files.pythonhosted.org/packages/77/2b/8359311c80c1fb61a8e6b93303d278d8282057f8ae632b8d5931449d83e1/conan-1.31.1.tar.gz
Requirement already satisfied: PyJWT<2.0.0,>=1.4.0 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: requests<3.0.0,>=2.8.1 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: urllib3!=1.25.4,!=1.25.5 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: colorama<0.5.0,>=0.3.3 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: PyYAML<6.0,>=3.11 in /usr/local/lib64/python3.6/site-packages (from conan)
Requirement already satisfied: patch-ng<1.18,>=1.17.4 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: fasteners>=0.14.1 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: six<=1.15.0,>=1.10.0 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: node-semver==0.6.1 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: distro<=1.5.0,>=1.0.2 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: future<0.19.0,>=0.16.0 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: pygments<3.0,>=2.0 in /usr/local/lib64/python3.6/site-packages (from conan)
Requirement already satisfied: deprecation<2.1,>=2.0 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: tqdm<5,>=4.28.1 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: Jinja2<3,>=2.9 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: bottle<0.13,>=0.12.8 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: pluginbase>=0.5 in /usr/local/lib/python3.6/site-packages (from conan)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests<3.0.0,>=2.8.1->conan)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests<3.0.0,>=2.8.1->conan)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests<3.0.0,>=2.8.1->conan)
Requirement already satisfied: monotonic>=0.1 in /usr/local/lib/python3.6/site-packages (from fasteners>=0.14.1->conan)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from deprecation<2.1,>=2.0->conan)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib64/python3.6/site-packages (from Jinja2<3,>=2.9->conan)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/site-packages (from packaging->deprecation<2.1,>=2.0->conan)
Installing collected packages: conan
  Running setup.py install for conan ... done
Successfully installed conan-1.31.1

```

conan --version

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.26.0 (/usr/local/lib/python3.6/site-packages), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/conan", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.26.0 (/usr/local/lib/python3.6/site-packages), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})

```

Just for check:
pip3 list | grep -E 'conan|urllib|requests'

I get

```
conan (1.31.1)
requests (2.24.0)
urllib3 (1.26.0)
```

### PR DESCRIPTION
**Pull request by memsharded**
Changelog: Bugfix: Recent ``liburl3`` 1.26 library updates is breaking the constraints in Conan ``requirements.txt``  as ``requests`` 2.24 has a limitation for ``liburl3``. This PR constrains ``liburl3`` version to be less than 1.26, so it does not break with requests 2.24.
Docs: Omit

Close https://github.com/conan-io/conan/issues/8041

Note: we might need to backport this to older Conan releases that might also break in prod.

#tags: slow, svn
#revisions: 1

### CODE REVIEW

**Review by jgsogo — COMMENTED** [review]
1.25.4 and 1.25.5 contained a bug that was affecting us. New requests 2.25.0 (to be released today) will be compatible with new urllib3 1.26. 

OTH, the new `pip` resolution algorithm 2020-resolver (should be the default very soon, it says October 2020) won't resolve to the conflicting dependencies, it looks like there is some metadata in the packages. This works for me:

```
pip install --use-feature=2020-resolver -U -r conans/requirements.txt
```

**Comment by lasote** [comment]
It is a bit weird because it should be able to resolve the conflict. The restriction we provide block only two versions (buggy versions).
Actually using the new pip resolver works.

- If I don't use the new resolver:

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.                                                                                                                                                    
requests 2.24.0 requires urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you'll have urllib3 1.26.0 which is incompatible.                                                     

```
- Using the new resolver (pip install conan --upgrade --use-feature=2020-resolver)

```
Collecting urllib3!=1.25.4,!=1.25.5
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Requirement already satisfied: pyparsing>=2.0.2 in /home/luism/.virtualenvs/kk/lib/python3.7/site-packages (from packaging->deprecation<2.1,>=2.0->conan) (2.4.7)
Requirement already satisfied: six<=1.15.0,>=1.10.0 in /home/luism/.virtualenvs/kk/lib/python3.7/site-packages (from conan) (1.15.0)
Installing collected packages: urllib3
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.0
    Uninstalling urllib3-1.26.0:
      Successfully uninstalled urllib3-1.26.0
Successfully installed urllib3-1.25.11
```

**Comment by jgsogo** [comment]
It is the new algorithm, no metadata, `requests` already says `urllib3<1.26`:

https://github.com/psf/requests/blob/0797c61fd541f92f66e409dbf9515ca287af28d2/setup.py#L47

**Comment by jgsogo** [comment]
`pip` changelog says new algorithm will be the default in version 20.3 (expected)

https://pip.pypa.io/en/stable/news/

**Review by lasote — CHANGES_REQUESTED** [review]
So, @jgsogo do we agree we shouldn't remove these constraints but introduce `<1.26`?

**Review by jgsogo — APPROVED** [review]

**Comment by charliekang** [comment]
pip added `--use-feature=2020-resolver` which worked

**Pull request merged**
