### PR TITLE
Modernize conan.tools.qbs

### PR DESCRIPTION
**Pull request by Psy-Kai**
Changelog: (Fix): Modernize conan.tools.qbs #9702

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by Psy-Kai** [comment]
I have some questions about this: How should I properly change my tests? The new conan 2.0 `ConanFile` features are not available in `MockConanfile` nor in `ConanFileMock`.
I also need a proper way to query `vcvars`. The `conan.tools.VCVars` class only write a script which calls another script. But I need to pass the compilers filepath to `qbs-setup-toolchains`. So I need the proper `cl.exe` or `clang-cl.exe` in `PATH` (this is how its currently implemented) or I need the full path to the compiler.

**Comment by memsharded** [comment]
Hi @Psy-Kai 

Thanks for attending this so fast.

I would try something in the line:
- Use ``conan.tools.VCVars`` like ``VCVars(self).generate(group=None)`` to generate the file
- Call ``self.run("qbs-setup-toolchains ...", env=["conanvcvars"])``
- Remove the generated file (might not be necessary, but maybe to keep things clean)

**Comment by Psy-Kai** [comment]
Hi @memsharded,

I still don't really know how to fix my tests properly. Will the Mocks get updated? How should I update the tests otherwise?

**Comment by Psy-Kai** [comment]
Hello again @memsharded. I hope this changes will satisfy the issue.

I also tweaked the `QbsProfile` generators behaviour a little bit (no worry, I have not broken anything). I try to mimic the [transparent integration of CMake](https://blog.conan.io/2021/10/19/New-CMake-Transparent-Integration-Guide.html),

For your understanding: as you might already guessed, the equivalent of a CMakeToolchain file is the Qbs profile. But normally these profile is not passed as a file. It is stored as a config in a separate settings directory. Before my latest changes I used Qbs to detect some profile values, extracted them from the qbs config, added more information provided by conan (like build_type) and create a file containing a profile. Using this approach a transparent integration is not possible because the project as to reference to file containing the profile manually.  
Now the generator will apply the values provided by conan to the qbs config (hence the `QbsProfile._set_qbs_config_value`). For transparent integration the settings dir just has to be passed with "--settings-dir <path>" (will be added later to the qbs build helper). Since I did not want to break already existing projects the generated still generated the `conan_toolchain_profile.qbs` file. But its just containing the config from the settings dir.

I hope I understood correctly the goal of transparent integration and how the `conan.tools` stuff should be implemented.

**Comment by Psy-Kai** [comment]
Will solve a part of #10033

**Comment by Psy-Kai** [comment]
@memsharded I just wanted to bump this MR, because I really want to finish the work on it. But I need some information if it is any good or if I need to change something (in regards to conan 2.0 way of doing things).

**Comment by memsharded** [comment]
Sorry we didn't manage to help moving this forward.
Now the Qbs integration has been pushed by @ABBAPOH in Conan 2, I am closing this PR, please lets follow on the Conan 2 latest version. Many thanks for your contribution in any case, really appreciated!

**Pull request closed without merging**
