### PR TITLE
Added integration test for mixing aliases and fix versions

### PR DESCRIPTION
**Pull request by Doome161**
Changelog: Omit
Docs: Omit

Added integration test for the bug described in #8966 

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [x] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one.

### CODE REVIEW

**Comment by memsharded** [comment]
Hi @Doome161,

Thanks very much for doing this PR and reproduce this issue, really helpful.

I am investigating this, seems complex to fix, I am on it. But what I can suggest meanwhile is try to minimize the usage of the ``requirements()`` method and use plain ``requires`` class attribute whenever possible, this helps to minimize conflicts. Have you tried that?

In your example just changing ``client.save({"conanfile.py": GenConanfile("cb", "1.0").with_requires("ca/1.0@user/testing")})`` will make the test pass.

**Comment by memsharded** [comment]
I have been able to understand a bit what is happening. Indeed very complex to fix, at least in Conan 1.X, as the risk of breaking something will be probably too high.

The thing is that alias are way more complicated from the implementation point of view than it seems, and makes things challenging compared with other requirements. Even more than version_ranges, the main challenge is that when you do see a require, you don't know it is an alias at all, until you resolve the recipe, but that comes later. So you can well have 2 different requires, like ``pkga/somealias`` and ``pgka/otheralias``, that might conflict or not, but until both of them are resolved, it is impossible to know.

As I would like to improve the processing of alias for Conan 2.0, I am going to propose to make them explicit, same as version ranges. Lets say an alias could always be like ``pkga/(somealias)``, and in this way, it will be very evident that it is, understanding what is happening, also from the consumer point of view will be nicer, and it could greatly improve the internal processing that Conan needs to do, maybe even resulting in faster dependencies resolution. What do you think?

**Comment by monsdar** [comment]
> As I would like to improve the processing of alias for Conan 2.0

I'd like to hear the opinions of the swarm in this regards. Having aliases explicit helps in a lot of ways, but there will be downfalls as well I guess.

> Indeed very complex to fix, at least in Conan 1.X, as the risk of breaking something will be probably too high.

Can we support this somehow? Perhaps by providing additional testcases? We use Aliases extensively and lately found that this issue in particular is breaking our local developer workflow. In most cases it's just warnings, but in others developer can't compile because Conan is not able to resolve the dependencies in the right order.

**Comment by memsharded** [comment]
Hi @monsdar 

I have prepared a proposal for the Tribe, to gather the feedback.

> Can we support this somehow? Perhaps by providing additional testcases? We use Aliases extensively and lately found that this issue in particular is breaking our local developer workflow. In most cases it's just warnings, but in others developer can't compile because Conan is not able to resolve the dependencies in the right order.

I am not sure, I have tried a couple of things and failed to come up with something that wouldn't have risk. I also tried in ``develop2`` branch, where I have more freedom to not break things, and even there I struggled to come up with something that made sense. Then I experimented a bit with the explicit approach, and at the moment it seems the only viable thing.

I will give it another try and let you know. In the worst case, I think we can look for other workarounds, many times these alias problems are solved just by changing order of declarations of ``requires``, or putting things in ``requires`` attribute instead of a method.

**Comment by monsdar** [comment]
It looks like there is nobody arguing against having explicit aliases in the Tribe request. Given that there is nothing coming up in the next days could we implement explicit aliases in Conan 1.x and solve the above issue with these? Then we could already migrate to explicit aliases in our codebase and have our problems resolved.

In Conan 1.x this could be an extension to the existing alias implementation. With Conan 2.x the non-explicit alias implementation would then be removed.

**Comment by memsharded** [comment]
> Given that there is nothing coming up in the next days could we implement explicit aliases in Conan 1.x and solve the above issue with these? Then we could already migrate to explicit aliases in our codebase and have our problems resolved.

As much as I would like that, it would be breaking behavior, and I don't think it is possible in Conan 1.X because it will break other users. We will add the syntax to help the transition to Conan 2.0, but we cannot force it and make compulsory or fail because it will be breaking.

I have still not given up, and I plan to try a couple of things more. But in any case, I would like to suggest to explore some other possible workarounds, there might be something doable that won't require a lot of effort on your side. 
This is the original failing test:

```python
def test_mixing_aliases_and_fix_versions():
    # cd ----------------------------------> cb/latest -(alias) -> cb/1.0 -> ca/1.0
    #  \--> cc/latest -(alias) -> cc/1.0  ----/                               /
    #                               \   ---> ca/latest -(alias) -------------/
    client = TestClient()

    client.save({"conanfile.py": GenConanfile("ca", "1.0")})
    client.run("create . ")
    client.run("alias ca/latest@ ca/1.0@")

    client.save({"conanfile.py": GenConanfile("cb", "1.0").with_requirement("ca/1.0@")})
    client.run("create .")
    client.run("alias cb/latest@ cb/1.0@")

    client.save({"conanfile.py": GenConanfile("cc", "1.0")
                .with_requirement("cb/latest@")
                .with_requirement("ca/latest@")})
    client.run("create . ")
    client.run("alias cc/latest@ cc/1.0@")

    client.save({"conanfile.py": GenConanfile("cd", "1.0")
                .with_requirement("cb/latest@")
                .with_requirement("cc/latest@")})
    client.run("create . ")
```

Changing the ``requirement()`` method for a plain ``requires = "xxxx"`` definition will make the test pass:

```diff
@@ -502,7 +502,7 @@ def test_mixing_aliases_and_fix_versions():
     client.run("create . ")
     client.run("alias ca/latest@ ca/1.0@")

-    client.save({"conanfile.py": GenConanfile("cb", "1.0").with_requirement("ca/1.0@")})
+    client.save({"conanfile.py": GenConanfile("cb", "1.0").with_requires("ca/1.0@")})
     client.run("create .")
     client.run("alias cb/latest@ cb/1.0@")
```

Making the dependency from cb to ca use the alias too, will make the test pass (what is problematic is to merge alias with explicit requires in the same diamond of the graph):
```diff
@@ -502,7 +502,7 @@ def test_mixing_aliases_and_fix_versions():
     client.run("create . ")
     client.run("alias ca/latest@ ca/1.0@")

-    client.save({"conanfile.py": GenConanfile("cb", "1.0").with_requirement("ca/1.0@")})
+    client.save({"conanfile.py": GenConanfile("cb", "1.0").with_requirement("ca/latest@")})
     client.run("create .")
     client.run("alias cb/latest@ cb/1.0@")
```

Changing the order of the downstream declaration, will also make the test pass (the order of the declaration matters, if the alias is resolved first or not):
```diff
@@ -513,6 +513,6 @@ def test_mixing_aliases_and_fix_versions():
     client.run("alias cc/latest@ cc/1.0@")

     client.save({"conanfile.py": GenConanfile("cd", "1.0")
-                .with_requirement("cb/latest@")
-                .with_requirement("cc/latest@")})
+                .with_requirement("cc/latest@")
+                .with_requirement("cb/latest@")})
     client.run("create . ")
```

Maybe some of these alternatives is a long hanging fruit that would solve your issue?

**Comment by monsdar** [comment]
My idea would be to add the explicit format in addition to the current non-explicit way. That should be non-breaking, but for the explicit aliases one could already implement better resolution mechanisms. The following could be legal in Conan 1.3x:

```
def requirements( self):
        self.requires("MyCompA/1.0.0@core/release")
        self.requires("MyCompB/[~=1.0]@core/release")
        self.requires("MyCompC/MyAlias@core/release")
        self.requires("MyCompD/(MyAlias)@core/release")
```

This could work in Conan 1.x, where in Conan 2.0 then the declaration for MyCompC would be invalid.

**Comment by monsdar** [comment]
If that is not an option we'll investigate how to automatically find a valid order for the requirements. Our dependency tree is too complex to find this manually, but perhaps (with some magic) we can provide a tool that outputs the optimal order for any developer encountering this issue.

**Comment by memsharded** [comment]
Hi @Doome161 @monsdar 

I am trying in https://github.com/conan-io/conan/pull/9217 to implement this feature. It might be possible to consider it for Conan 1.X as the new syntax ``pkg/(alias)`` is an opt-in apparently at all levels, so it wouldn't be breaking. 

I have added already a few tests, so far it seems fine, but if you want to experiment with this feature, that would be extremely helpful, you might run Conan from source from my branch. Thanks!

**Comment by Doome161** [comment]
Hi @memsharded ,

sounds great! I will experiment around with the feature in the next few days and will share my experience here

**Comment by Doome161** [comment]
Hi @memsharded ,

I have been experimenting with the explicit aliases now and it works great! I was able to build huge trees with mixed aliases and fixed versions without problems.

I do have one small comment though:

We also use aliases for python_requires. But there you get an error if you use the explicit aliase syntax; 
```shell
Unable to find python_requires("comp/(LATEST)@user/channel") in remotes
```

Beside that, I would be very happy if this feature would be included in one of the next conan releases. It would help our developers a lot. Our current workaround for this bug is very dirty and often leads to confusion and a lot more work.

**Comment by memsharded** [comment]
@Doome161 

Added in the PR support for python-requires alias, if you want to try that too. Thanks!

**Comment by memsharded** [comment]
@Doome161 did you manage to try the ``python_requires`` support in my PR?
If we aim to release this in Conan 1.39, ti would be great to have feedback by this week, as this will require some internal discussion about the architecture and risks.

**Comment by Doome161** [comment]
Hi @memsharded ,

sorry for the late feedback. I tried it on my system and I still get the error shown above

**Comment by memsharded** [comment]
Which ``python_requires`` are you using? The class attribute or the global function?

**Comment by Doome161** [comment]
The global function

**Comment by memsharded** [comment]
> The global function

That explains it. It has only be implemented in the class attribute, it superseded the global function long time ago. Only the class attribute will be maintained in Conan 2.0: https://docs.conan.io/en/latest/extending/python_requires_legacy.html

It is unlikely that we can port this thing to the global function, it is being removed because it always made things extra-complicated, because of the inversion of control (the python requires are resolved directly by the python interpreter, not Conan).

**Comment by Doome161** [comment]
Ok, I think we can live with that 👍

**Comment by memsharded** [comment]
Hi all!

We have merged https://github.com/conan-io/conan/pull/9217, to be released in Conan 1.39.
This should be enough for this case, so we can close it, but please create a new issue or PR to report any problem with the new syntax. We hope this enable a smooth transition to Conan 2.0, and also allows to solve all the alias related issues earlier, from 1.39.

Many thanks!

**Pull request closed without merging**
