### PR TITLE
"ANY" is also matching "None" within settings

### PR DESCRIPTION
**Pull request by thorsten-klein**
Changelog: Feature: There can be used [None, ANY] within settings.yml file to point out that a setting can be set to any value or that it can be unset.
Docs: https://github.com/conan-io/docs/pull/1152

In settings.yml you can set any setting to allowed value ANY. This points out that every value is okay, which should also include value "None" (or <not defined>).

- [ ] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [x] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one.

### CODE REVIEW

**Comment by memsharded** [comment]
Thanks for the PR. We need to carefully consider it, not sure if it would be breaking. Because so far the idea is that if you defined ANY, it should have a value defined.

So maybe the non-breaking solution would be  ``[None, ANY]``
Seems more conceptually correct, as ANY is literally "any" value, but a value indeed. ``None`` is not having a value defined. What do you think? Do you think you could update your PR to implement this behavior? Many thanks!

**Comment by jgsogo** [comment]
I have to link here these tables https://github.com/conan-io/conan/issues/3620 for reference.

**Comment by memsharded** [comment]
Hi @thorsten-klein 

Not necessary to change the PR, please wait a little bit, I am going to check it twice first, and probably discuss with the team. Thanks.

**Comment by thorsten-klein** [comment]
Hello,
please tell me if I shall change to suggested other solution `[None, ANY]`, which is a check for `if "ANY" in self._definitions`.

Thank you for your really fast feedback!

**Comment by lasote** [comment]
Start allowing the None as a valid ANY value is changing the behavior and it will break someone. I think might be a good idea the @memsharded suggestion of [None, ANY]

**Comment by thorsten-klein** [comment]
Hello,
Thank you for Feedback. 
I will adapt it and add unit tests.

**Comment by thorsten-klein** [comment]
I made all according changes and added unit tests for All cases :-)

**Comment by lasote** [comment]
Looks like something is not working correctly.

**Comment by thorsten-klein** [comment]
@lasote I adjusted the `remove()` method and added `self.validate()` in the end. By this current `_value` is checked if it is valid for current `self._definition`.

In all failing test cases this check is failing since current `_value==None` but `self._definition` does not allow `None`.
Shall I revert this `self.validate()` in the end of `remove()` method so that there is no check of `_value` at the end?

**Comment by memsharded** [comment]
Hi @thorsten-klein 

I have submitted a PR to your branch in https://github.com/thorsten-klein/conan/pull/1, with some changes I think are worth before merging and releasing this. Please have a look there, thanks!

**Comment by memsharded** [comment]
Good, thanks!

Please note that you need to edit the lines:

```
Changelog: (Feature | Fix | Bugfix): Describe here your pull request
Docs: https://github.com/conan-io/docs/pull/XXXX
```

In the first comment, because it is necessary for the changelog (the changelog is extracted automatically from that). It will be a feature, is enabling a new behavior. The PR to the docs can be very simple, maybe just 2 lines with a small snipped of such setting with [None, ANY].

**Comment by memsharded** [comment]
Merged, many thanks!

It will be released in Conan 1.15

**Pull request merged**
