### PR TITLE
Test and fix for read only files from `svn:needs-lock` attribute (#3638)

### PR DESCRIPTION
**Pull request by climblinne**
- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [x] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

Write test case to check, that read-only are writeable, before SCM auto elements are written.  This links to #3638.

### CODE REVIEW

**Comment by climblinne** [comment]
This should already work with a remote repository. There is still a problem, with a local repository, when it tries to merge back the changes inside `_fetch_scm`.

**Comment by climblinne** [comment]
It would be nice to get this bugfix into the next minor release of conan, because it prevents the usage of SVN with locking active.

**Comment by jgsogo** [comment]
I think that this PR has no other effect than changing permissions to be able to override files (with ``shutil.copy2``), so it should have no collateral effects. Let's ask the team to review it.

**Comment by danimtb** [comment]
Changing file permissions always scares me a little bit but now that upload diffs are done using manifest it is less dangerous

**Comment by memsharded** [comment]
I have had a look, and I am concerned about this PR. There are users that are packaging files with certain permissions they care, changing them to 0777 might be problematic (and breaking) for them.

I don't have enough understanding of SVN behavior to think of an approach, but I believe we should think this PR twice.

**Comment by jgsogo** [comment]
@memsharded, SVN has the ability to _lock_ files (+docs: https://tortoisesvn.net/docs/release/TortoiseSVN_en/tsvn-dug-locking.html). One user can **lock** a file to make it only editable by himself, the locking mechanism ensures that noone can modify that file. How does SVN manage to do it? Clients change permissions of that file to read-only for every other working copy.

Said that, we have to know why this happens only for SCM as @climblinne says (https://github.com/conan-io/conan/issues/3638#issuecomment-429736445):
> It looks like, that it only happens for SCM (Git & SVN) modules. I tried it with a normal local file system and had no success to get an exception. But I am still no expert on Conan...

**Comment by climblinne** [comment]
> @memsharded, SVN has the ability to _lock_ files (+docs: https://tortoisesvn.net/docs/release/TortoiseSVN_en/tsvn-dug-locking.html). One user can **lock** a file to make it only editable by himself, the locking mechanism ensures that noone can modify that file. How does SVN manage to do it? Clients change permissions of that file to read-only for every other working copy.
> 
> Said that, we have to know why this happens only for SCM as @climblinne says ([#3638 (comment)](https://github.com/conan-io/conan/issues/3638#issuecomment-429736445)):
> 
> > It looks like, that it only happens for SCM (Git & SVN) modules. I tried it with a normal local file system and had no success to get an exception. But I am still no expert on Conan...

There are really to important things:
1. Conan copies the `conanfile.py` and then replace the auto values inside. Question: Why need the copy of `conanfile.py` be readonly?
2. Conan tries to merge the repository to another directory (only if repository is locally available). Merging is hard, when the destination files are read-only. Already existing files need to be replaced / changed, but this will not worked, because they have read-only flag. Why not clean the whole directory before?

**Pull request merged**
