### PR TITLE
Add htpasswd and authorize middleware

### PR DESCRIPTION
**Pull request by d-schiffner**
Creating a htpasswd compatible middleware to allow authentication against secure files

To allow multiple authorizations, a middleware is added. On instantiation, the authenticators get the server_config and the parameter defined in the config.

### CODE REVIEW

**Comment by memsharded** [comment]
Hi @d-schiffner ,

Your PR seems interesting. Maybe a bit specific for a particular use case. I like some of the abstractions, I am thinking about some way to have them as possible extension points, so the htpsswd (and others) could be easily connected (and then, not necessary to provide support for all platforms, for example, such the Win tests failing). We are working on it, will keep you updated. Thanks very much for your efforts.

**Comment by memsharded** [comment]
Related https://github.com/conan-io/conan/issues/920

**Comment by d-schiffner** [comment]
Hi memshareded,

maybe AppVeyeor doesn't want to build anymore.

http://help.appveyor.com/discussions/problems/4830-stuck-on-appveyor-was-unable-to-build-non-mergeable

**Comment by memsharded** [comment]
Just got the same on one of my PR. Fixed it closing and opening a new one. Pushing new commits to the old PR didn't fix it. Not sure if something github related.

**Comment by d-schiffner** [comment]
Hi @memsharded,

are there any plans to merge this? Are refactorings required?

**Comment by memsharded** [comment]
Hi Daniel.
Yes, sorry for the delay in handling this. Actually we have been reviewing your PR together with the work from https://github.com/conan-io/conan/issues/920 from @uilianries, which aims to provide LDAP support. As there is so much common ground, and most likely this will be a common pattern, we have decided to design a plugin system, and we think that your interface is the way to go, it is well designed, so it will be the basis for the extension point. Sorry we didn't manage to get it into 0.20, but will schedule it for next 0.21. Thanks again!

**Comment by d-schiffner** [comment]
Hi James,

you're welcome. If you need something, just tell me. Keep up the awesome work

**Comment by memsharded** [comment]
Hi @d-schiffner 

We have already merged to develop the plugin system for custom authenticators. It will allow easy plugin of any Authenticator, while not cluttering the main conan_server with specific implementations that won't be used by most users, or that are not supported in all OSs, or that cannot be redistributed under the same license terms as conan. 

In its current implementation, only 1 authenticator is supported at a time, we believe that iteratively trying different authenticators would be a security and maintenance issue, so unless it is explicitly requested and argued, we will use 1 authenticator.

Adding a custom authenticator can be done creating a python module in ``~/.conan_server/plugins/authenticator/my_authenticator.py``

Example:

```python
 def get_class():
     return MyAuthenticator()

 class MyAuthenticator(object):
     def valid_user(self, username, plain_password):
         return username == "foo" and plain_password == "bar"
```

This module can have its own configuration in its own file, so you can model for example the ``htpasswd_file`` argument there (though I wouldn't mind to have such configuration directly in python code, ala django "settings").

So I guess the best now would be to locate the ``HttpPasswordAuthenticator`` in its own github repo, and add the interface to work as a plugin. Would you like help with this? Thanks very much once more for your contribution.

Hi @uilianries, same would apply for the LDAP plugin. Now it doesn't matter if it doesn't provide support for Win, as it can be distributed in its own repo, and it won't affect the testing, development and release cycles of conan.

**Comment by uilianries** [comment]
Great support! Thanks!

**Comment by d-schiffner** [comment]
@memsharded,

thx. I'm surely open to help you with the implementation of the middleware. Just ping me, if you need me to do something

**Pull request closed without merging**
