### PR TITLE
fixing application of build_requires to host context build_requires

### PR DESCRIPTION
**Pull request by memsharded**
Changelog: Bugfix: When using ``build_requires`` defined in a profile that is passed as ``profile_host``, it was not being applied to ``build_requires`` that live in the host context (with ``force_host_context=True``).
Docs: Omit

#tags: slow

Reported by @jasal82

### CODE REVIEW

**Review by jgsogo — COMMENTED** [review]
I haven't looked at the implementation, but I'd say that the test makes sense (I suggested a change to be 100% sure that the BR belongs to the _build_ context).

Do you know the previous PR that changed this behavior? Maybe https://github.com/conan-io/conan/pull/7169?

**Comment by memsharded** [comment]
yes, this was introduced in Conan 1.26, in https://github.com/conan-io/conan/pull/7169. The idea behind the change is correct, but it didn't fully covered the case of ``force_host_context=True``. If the CI is green, I'll try to simplify/refactor the implementation, too much copy & paste

**Review by jgsogo — APPROVED** [review]
Not a trivial change 😄 

---

With this change, do you know what happens if the `profile:build` declares a build-requires and the `profile:host` declares another build-requires. Will the BR from the `profile:build` be applied to the BR from the `profile:host`? It was something _broken/undecided_ in #7169

**Comment by memsharded** [comment]
> With this change, do you know what happens if the profile:build declares a build-requires and the profile:host declares another build-requires. Will the BR from the profile:build be applied to the BR from the profile:host? It was something broken/undecided in #7169

I have added a new test. Indeed there is a limitation, and the ``build_requires`` required in the *profile_build* do not apply to other ``build_requires`` that come from a *profile_host*, because the algorithm does not propagate build requires from profiles, as otherwise they easily induce infinite recursion.

I think we should probably leave this limitation in place, trying to improve that has a high chance to break something.

**Review by jgsogo — APPROVED** [review]

**Comment by jasal82** [comment]
Verified release branch against our cross build, works fine!

**Pull request merged**
