### PR TITLE
Implement tools.Version (based on SemVer)

### PR DESCRIPTION
**Pull request by jgsogo**
Changelog: Feature: Create `tools.Version` with _limited_ capabilities
Docs: https://github.com/conan-io/docs/pull/1253

 * I'm using `loose=True` to allow incomplete versions like `1.2` (no _patch_ component) or "2" (no _minor_ nor _patch_)

closes https://github.com/conan-io/conan/issues/4875

_Note.- Supersedes https://github.com/conan-io/conan/pull/4949_

### CODE REVIEW

**Comment by danimtb** [comment]
I like the ``loose=True`` by default.

Regarding the prerelease, I 'd go for the implementation of the semver library. Maybe just adding another attribute so people can choose (same as version ranges)?

**Comment by lasote** [comment]
Ok about the `loose`. 
About the comparison, I would say `Version("1.2.3-dev90")  !=  "1.2.3"` cannot be `True`.  So `"1.2.3-dev90" < 1.2.3` but `"1.2.3-dev90" == "1.2.3"`?? How it could be even possible?

**Comment by jgsogo** [comment]
> Ok about the `loose`.
> About the comparison, I would say `Version("1.2.3-dev90") != "1.2.3"`. So `Version("1.2.3-dev90") < Version("1.2.3")` but `Version("1.2.3-dev90") == Version("1.2.3")`?? How could it be even possible?

I don't understand your comment, sorry. Just to make it clear: if we don't take into account things like prereleases/microversion/build/meta/... (like it is implemented right now), then:

```python
        v1 = Version("1.2")
        v2 = Version("1.2-dev0")

        # Compare ALL the components
        self.assertTrue(v1.major == v2.major)
        self.assertTrue(v1.minor == v2.minor)
        self.assertTrue(v1.patch == v2.patch)
        # ... nothing more to compare

        # So...
        self.assertTrue(v1 == v2)
        self.assertFalse(v1 > v2)
        self.assertFalse(v1 < v2)
```

It makes sense because this `Version` object is "limited", it only exposes `major`, `minor` and `patch` components, the user cannot retrieve other components of the full string they used to create the object, those components are _lost_.

**Comment by lasote** [comment]
> It makes sense because this Version object is "limited", it only exposes major, minor and patch components,

For me, it doesn't make sense at all. One thing is exposing some getters and a different thing is comparing incorrectly on purpose. But let's make sense for everyone, it is a wrapper so it's very easy, implement the getters for the "prerelease" and the "build" and make the comparison correct for these fields too.

**Comment by jgsogo** [comment]
It should be ok now, also with docs

**Pull request merged**
