### PR TITLE
add option for build target to make

### PR DESCRIPTION
**Pull request by weatherhead99**
- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [X ] I've read the [Contributing guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ ] I've followed the PEP8 style guides for Python code.
- [X ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. Also adding a description of the changes in the ``changelog.rst`` file. https://github.com/conan-io/docs

This adds an option to select the target to the autotools make command. This is very useful e.g. to either do an install "make install" or build shared libraries, in the case where the project creates a separate targets (e.g. "make shared")

### CODE REVIEW

**Comment by memsharded** [comment]
Sounds good, thanks!
But I think it might deserve at least a small test, and documenting in the docs repo. Please ask for guidance or help if necessary.

**Comment by weatherhead99** [comment]
ok, there is now a test case and a documentation update :-)

**Comment by memsharded** [comment]
Thanks, that is great, good job!
We will review it for inclusion in next release 1.1

**Comment by weatherhead99** [comment]
should I attempt to rebase this back onto develop? Looks like a very tiny conflict so far

**Comment by memsharded** [comment]
Thanks very much for your contribution!

**Pull request merged**
