### PR TITLE
Keep raw text in command description

### PR DESCRIPTION
**Pull request by jgsogo**
Changelog: omit
Docs: https://github.com/conan-io/docs/pull/1285

We are using the _docstring_ from the function as the description text for the help message of all the Conan commands, I think it could be useful to preserve endlines for the command description. See images attached:

Source...
image

... now it will generate ...

```bash
⇒  conan install --help
usage: conan install [-h] [-g GENERATOR] [-if INSTALL_FOLDER] [-m [MANIFESTS]]
                     [-mi [MANIFESTS_INTERACTIVE]] [-v [VERIFY]]
                     [--no-imports] [-j JSON] [-b [BUILD]] [-e ENV]
                     [-o OPTIONS] [-pr PROFILE] [-r REMOTE] [-s SETTINGS] [-u]
                     path_or_reference [reference]

Installs the requirements specified in a recipe (conanfile.py or conanfile.txt).

It can also be used to install a concrete package specifying a
reference. If any requirement is not found in the local cache, it will
retrieve the recipe from a remote, looking for it sequentially in the
configured remotes. When the recipes have been downloaded it will try
to download a binary package matching the specified settings, only from
the remote from which the recipe was retrieved. If no binary package is
found, it can be build from sources using the '--build' option. When
the package is installed, Conan will write the files for the specified
generators.

positional arguments:
  path_or_reference     Path to a folder containing a recipe (conanfile.py or
...
```

before, it was just a single line...

```bash
⇒  conan install --help
usage: conan install [-h] [-g GENERATOR] [-if INSTALL_FOLDER] [-m [MANIFESTS]]
                     [-mi [MANIFESTS_INTERACTIVE]] [-v [VERIFY]]
                     [--no-imports] [-j JSON] [-b [BUILD]] [-e ENV]
                     [-o OPTIONS] [-pr PROFILE] [-r REMOTE] [-s SETTINGS] [-u]
                     path_or_reference [reference]

Installs the requirements specified in a recipe (conanfile.py or
conanfile.txt). It can also be used to install a concrete package specifying a
reference. If any requirement is not found in the local cache, it will
retrieve the recipe from a remote, looking for it sequentially in the
configured remotes. When the recipes have been downloaded it will try to
download a binary package matching the specified settings, only from the
remote from which the recipe was retrieved. If no binary package is found, it
can be build from sources using the '--build' option. When the package is
installed, Conan will write the files for the specified generators.

positional arguments:
  path_or_reference     Path to a folder containing a recipe (conanfile.py or
                        conanfile.txt) or to a recipe file. e.g.,
...
```

Do you find it interesting/useful? is it an improvement?

### CODE REVIEW

**Comment by jgsogo** [comment]
It also changes the `conan --help` output, now it show all the lines until the first blank (see `new` and `inspect` commands):

```txt
⇒  conan
Consumer commands
  install    Installs the requirements specified in a recipe (conanfile.py or conanfile.txt).
  config     Manages Conan configuration.
  get        Gets a file or list a directory of a given reference or package.
  info       Gets information about the dependency graph of a recipe.
  search     Searches package recipes and binaries in the local cache or in a remote.
Creator commands
  new        Creates a new package recipe template with a 'conanfile.py' and optionally,
             'test_package' testing files.
  create     Builds a binary package for a recipe (conanfile.py).
  upload     Uploads a recipe and binary packages to a remote.
  export     Copies the recipe (conanfile.py & associated files) to your local cache.
  export-pkg Exports a recipe, then creates a package from local source and build folders.
  test       Test a package consuming it from a conanfile.py with a test() method.
Package development commands
  source     Calls your local conanfile.py 'source()' method.
  build      Calls your local conanfile.py 'build()' method.
  package    Calls your local conanfile.py 'package()' method.
  editable   Manage editable packages
  workspace  command to manage workspaces
Misc commands
  profile    Lists profiles in the '.conan/profiles' folder, or shows profile details.
  remote     Manages the remote list and the package recipes associated to a remote.
  user       Authenticates against a remote with user/pass, caching the auth token.
  imports    Calls your local conanfile.py or conanfile.txt 'imports' method.
  copy       Copies conan recipes and packages to another user/channel.
  remove     Removes packages or binaries matching pattern from local cache or remote.
  alias      Creates and exports an 'alias package recipe'.
  download   Downloads recipe and binaries to the local cache, without using settings.
  inspect    Displays conanfile attributes, like name, version, options. Works both locally,
             in local cache and remote
  help       Show help of a specific command.

```

**Comment by SSE4** [comment]
this appears to be very inconsistent now, some descriptions start from capital, some don't, some are ended with dot, while others aren't.

**Comment by jgsogo** [comment]
You are right, @SSE4, I've taken care of the offending help messages (and updated my comments above with the actual output). Now it is consistent.

Do you think it worths the change?

**Comment by SSE4** [comment]
yeah, if install conan for the first time and just run it, it's probably the very first output of conan you'd see.

**Comment by lasote** [comment]
Please solve conflicts and CI to move it forward.

**Comment by lasote** [comment]
Would be nice also to update the docs with the new formatting in the reference.

**Comment by jgsogo** [comment]
Done with conflicts and docs!

**Pull request merged**
