### PR TITLE
Update contributors.txt

### PR DESCRIPTION
**Pull request by raulbocanegra**
Added my name to 'contributors.txt'

### CODE REVIEW

**Comment by lasote** [comment]
Remember to click in the "licence/cla" and aprove it if it's ok for you!

Thanks Raúl!

**Comment by raulbocanegra** [comment]
Just signed! :-)

**Comment by lasote** [comment]
Your name has broken the appveyor build! hahahha, just kidding, We have a not very stable test related with windows filesystem that sometimes fails. I'm relaunching it ;)

**Comment by raulbocanegra** [comment]
Hahaha!

**Pull request merged**
