### PR TITLE
Removing indentation in conaninfo.txt for parsing with ConfigParser

### PR DESCRIPTION
**Pull request by aallrd**
Hello,
I recently tried to parse the generated conaninfo.txt with the Python 2.7 ConfigParser module and it failed with the below errors:
```
>> import ConfigParser
>> config = ConfigParser.ConfigParser()
>> config.read('conaninfo.txt')
ConfigParser.ParsingError: File contains parsing errors: conaninfo.txt
        [line  2]: '    arch = x86_64\n'
```

The error comes from the withespace before the defined properties.
This patch removes this whitespace.

I could not find any reference stating what is the correct format for the properties in INI files, so not sure if you should accept this merge request :)

### CODE REVIEW

**Comment by memsharded** [comment]
The truth is that the file reads better with indentation, but not opposed to remove it if more conformant to ConfigParser.

Just a small detail about the test fixing: I would try a cleaner approach, as it might happen that the conaninfo.txt is wrong, outputting info to oneline, and tests still pass. I suggest doing the multiline comparison as lists of lines, instead of joining them.

**Comment by lasote** [comment]
`/conans/test/model/info_test.py` is failing.
Also I would like to try the new format passed to an Artifactory server too see that it's parsed ok (should not be a problem but better to make sure.

**Comment by memsharded** [comment]
Hi @aallrd,

Have you been able to look into this, and check the broken tests? I would also like to know the use case, if you want to extract the information from packages, can you just import the conan class for the model and use it?. Something like (pseudo-code):

```python
from conans.model.info import ConanInfo
from conans.util.files import load

info = ConanInfo.loads(load(my_file_path))
# access to info.settings, info.options, etc
print info.settings.values.dumps()
```

Thanks!

**Comment by memsharded** [comment]
Hi @aallrd !

Any news on this? Do you still need it, or are you ok? Please tell, and if you need some help with it. Thanks!

**Comment by aallrd** [comment]
Hi @memsharded,

Sorry for the delay, I was off for some time.
I am closing this pull request as I don't need it anymore.
Thanks!

**Comment by memsharded** [comment]
No worries. Just re-open or report if you need this any other time. Thank you!

**Pull request closed without merging**
