### PR TITLE
Fix Conan Server (#4080)

### LINKED ISSUE #4080: Conan Server 1.10 is broken
#### Description
Hi!

I'm trying to start conan server but seems like is broken.

    $ conan_server

> Traceback (most recent call last):
>   File "/opt/miniconda3/bin/conan_server", line 7, in <module>
>     from conans.conan_server import run
>   File "/opt/miniconda3/lib/python3.6/site-packages/conans/conan_server.py", line 1, in <module>
>     from conans.server.server_launcher import main
>   File "/opt/miniconda3/lib/python3.6/site-packages/conans/server/server_launcher.py", line 53, in <module>
>     launcher = ServerLauncher()
>   File "/opt/miniconda3/lib/python3.6/site-packages/conans/server/server_launcher.py", line 47, in __init__
    server_capabilities, only_v1=False)
> TypeError: __init__() got an unexpected keyword argument 'only_v1'

#### Environment
Conan Versions: 1.10
Python version: 3.6, 3.7
OS: Linux Ubuntu 18.04

#### Steps to reproduce
    pip3 install conan==1.10.0
    conan_server

or using Conan Docker Tools:

    BUILD_CONAN_SERVER_IMAGE=1 python build.py
    docker run -t -p 9300:9300 --name conan_server conanio/conan_server:latest 

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

### PR DESCRIPTION
**Pull request by uilianries**
Changelog: Bugfix: Add v1_only argument in Conan server class

- [X] Refer to the issue that supports this Pull Request. Close #4080
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [X] I've read the [Contributing guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one.

### CODE REVIEW

**Comment by uilianries** [comment]
Error on Windows environment:

```
======================================================================

ERROR: cmake_outsource_build_test_0 (blocked_v2.conans.test.integration.workspace_test.WorkspaceTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "d:\j\t\1eaa\py27\blocked_v2\venv\lib\site-packages\parameterized\parameterized.py", line 392, in standalone_func

    return func(*(a + p.args), **p.kwargs)

  File "D:\J\t\source\1eaa\py27\blocked_v2\conans\test\integration\workspace_test.py", line 218, in cmake_outsource_build_test

    shutil.rmtree(os.path.join(client.current_folder, "build"))

  File "C:\Python27\Lib\shutil.py", line 261, in rmtree

    rmtree(fullname, ignore_errors, onerror)

  File "C:\Python27\Lib\shutil.py", line 261, in rmtree

    rmtree(fullname, ignore_errors, onerror)

  File "C:\Python27\Lib\shutil.py", line 270, in rmtree

    onerror(os.rmdir, path, sys.exc_info())

  File "C:\Python27\Lib\shutil.py", line 268, in rmtree

    os.rmdir(path)

WindowsError: [Error 145] The directory is not empty: 'D:\\J\\t\\1eaa\\py27\\blocked_v2\\tmp7tpfanconans\\path with spaces\\build\\A\\Release'
```

**Comment by jgsogo** [comment]
Running again Jenkins, it may be an error related to the CI, not to the PR itself.

**Comment by uilianries** [comment]
Now we have a new error from "Parallel / Linux - disabled_revisions - py34", but related to makefile generator:

```
======================================================================
ERROR: integration_test (disabled_revisions.conans.test.generators.make_test.MakeGeneratorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/source/1eaa/py34/disabled_revisions/conans/test/generators/make_test.py", line 337, in integration_test
    client.run("create . danimtb/testing")
  File "/tmp/source/1eaa/py34/disabled_revisions/conans/test/utils/tools.py", line 625, in run
    raise Exception(exc_message)
nose.proxy.Exception: 
```

Weird, because I didn't touch that code.

**Comment by lasote** [comment]
I've open: https://github.com/conan-io/conan/pull/4096

**Comment by uilianries** [comment]
Understood! :+1:

**Pull request closed without merging**
