### PR TITLE
Add apple-clang 16 to settings

### PR DESCRIPTION
**Pull request by chenrui333**
Changelog: Feature: support apple-clang 16
Docs: https://github.com/conan-io/docs/pull/3834

While bottling for conan in Sequoia OS, seeing some regression test failure as below:

```
  ==> /opt/homebrew/Cellar/conan/2.7.0/bin/conan install --requires=zlib/1.2.11 --build=missing --lockfile-out=conan.lock
  ERROR: Invalid setting '16' is not a valid 'settings.compiler.version' value.
  Possible values are ['5.0', '5.1', '6.0', '6.1', '7.0', '7.3', '8.0', '8.1', '9.0', '9.1', '10.0', '11.0', '12.0', '13', '13.0', '13.1', '14', '14.0', '15', '15.0']
  Read "http://docs.conan.io/2/knowledge/faq.html#error-invalid-setting"
```

relates to https://github.com/Homebrew/homebrew-core/actions/runs/10797633816/job/29949321497
- https://github.com/Homebrew/homebrew-core/issues/184132

### CODE REVIEW

**Comment by memsharded** [comment]
Thanks for the report and adding it @chenrui333 

Just a quick question, apple-clang has not been released yet, has it? It is still in RC?

**Comment by memsharded** [comment]
@czoido adding this to 2.7.1 in case the release of apple-clang 16 is imminent, but if not, it can be moved to 2.8

**Comment by czoido** [comment]
Closed in favor of https://github.com/conan-io/conan/pull/16972 for 2.7.1
Thanks a lot for the contribution @chenrui333 I cherry-picked your commit in the other PR

**Comment by chenrui333** [comment]
totally, thanks @czoido!

**Comment by chenrui333** [comment]
@memsharded yeah, it is in RC phase atm (expected to be released next week), but I think it is valuable to add it for the downstream consumptions.

**Pull request closed without merging**
