### PR TITLE
Enhance vs-generator

### LINKED ISSUE #5561: VS generator not exporting for <Lib> tag in vcxproj
Need to add Conan-handled lib to be referenced in .vcxproj in <Lib> tags. Conan VS-generator is exporting only in <Link> tag.

### PR DESCRIPTION
**Pull request by kobalicek**
Changelog: Feature: Enhanced vs-generator by providing more properties that can be referenced by other projects; added library paths also to <Lib> so it's possible to compile static libraries that reference other libs
Docs: Omit

Close #5561

### CODE REVIEW

**Comment by memsharded** [comment]
Hi @kobalicek 

Thanks very much for contributing this. It is looking good, just 3 tests are broken because they check the output of the visual_studio generator. Can you please have a look and fix them? Otherwise just tell and we will help with that, no problem.

**Comment by memsharded** [comment]
Side note, @kobalicek have a look to my edits to the first comment in the PR. We use that format to automatically generate the changelog, and it will also automatically close that issue. Thanks again!

**Comment by jgsogo** [comment]
I see that this PR is adding some `;` at some places to concatenate elements:

 * `$(ConanIncludeDirectories);%(AdditionalIncludeDirectories)`
 * `$(ConanPreprocessorDefinitions);%(PreprocessorDefinitions)`
 * `$(ConanLibraryDirectories);%(AdditionalLibraryDirectories)`
 * `$(ConanPreprocessorDefinitions);%(PreprocessorDefinitions)`

Conan provided elements already ends with `;`:

```python
fields = {
            'condition': condition,
            'bin_dirs': "".join("%s;" % p for p in build_info.bin_paths),
            'res_dirs': "".join("%s;" % p for p in build_info.res_paths),
            'include_dirs': "".join("%s;" % p for p in build_info.include_paths),
            'lib_dirs': "".join("%s;" % p for p in build_info.lib_paths),
            'libs': "".join(['%s.lib;' % lib if not has_valid_ext(lib)
                             else '%s;' % lib for lib in build_info.libs]),
            'definitions': "".join("%s;" % d for d in build_info.defines),
            'compiler_flags': " ".join(build_info.cxxflags + build_info.cflags),
            'linker_flags': " ".join(build_info.sharedlinkflags),
            'exe_flags': " ".join(build_info.exelinkflags)
        }
```
I suppose there is no problem having `;;` (an empty element or two `;` at the end), but I would suggest to fix this too or keep previous behavior. The fix would be to simplify the `join` statements above to something like: `'bin_dirs': ";".join(build_info.bin_paths),`. 

@memsharded , shall we change this too or just keep previous behavior?

**Comment by kobalicek** [comment]
@memsharded Unfortunately I noticed the tests were failing after the PR. Initially, I didn't want to touch anything else to not break some other part of the generator. I have looked at the tests and I would have to spend some time figuring out how to fix them (I'm not really a python guy).

I now see the problem with semicolons and I think they should:
  - either be removed from template vars and then just used as `$(ConanIncludeDirectories);%(AdditionalIncludeDirectories)` (which is probably breaking behavior)
  - kept and then used as `$(ConanIncludeDirectories)%(AdditionalIncludeDirectories)`

Both have pros/cons so let me know your preference.

**Comment by jgsogo** [comment]
@kobalicek, let's decide what to do with the `;` and then I will help you with the Python tests ;D

**Comment by kobalicek** [comment]
I would prefer to second option as it's backwards compatible, but in the end it doesn't matter for us :)

**Comment by kobalicek** [comment]
Should I update the PR to use the second option and proper commit message?

**Comment by jgsogo** [comment]
Yes, please, let's go for the more conservative option, but add a `FIXME Conan 2.0, use proper ';'` (maybe link to these last comments) so we realize to improve it in the future.

Do not worry about the commit message, we stash changes before merging to `develop`.

Thanks

**Comment by kobalicek** [comment]
Not sure why the tests are not running for the latest push, did I reach some limit?

I cannot run the tests from here so I rely on CI to finish this.

**Comment by jgsogo** [comment]
I can see it running in the CI right now, maybe it was due to the _force push_ that Jenkins was not able to ping back Github, but now it is working. Thanks!

**Comment by kobalicek** [comment]
OK it's finally passing, let me know about possible further improvements.

**Comment by kobalicek** [comment]
Ping :) Any objections or suggestion?

**Comment by kobalicek** [comment]
We have already tested this change locally, but I would welcome somebody else to test this independently of course.

**Comment by toughengineer** [comment]
Hello all.
I also need this bug to be fixed :slightly_smiling_face:.
In my case I have to specify Additional Dependencies as well as Additional Dependency Directories in Librarian properties, so vcxproj section looks like:
```xml
    <Lib>
      <AdditionalDependencies>xsec_2_0.lib</AdditionalDependencies>
      <AdditionalLibraryDirectories>$(Conan-xmlsecurity-Root)/lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
    </Lib>
```
@kobalicek, in your changes I see that you only added `AdditionalLibraryDirectories` in the `Lib` section unless I'm missing something, so I suppose you need to add something like
```xml
<AdditionalDependencies>{libs}%(AdditionalDependencies)</AdditionalDependencies>
```
to the `Lib` section as well.

**Comment by kobalicek** [comment]
@toughengineer I didn't want to change so much so I did only change that would be backward compatible. It's true that maybe `<AdditionalDependencies>` should be populated as well and I thought about it, but then reconsidered to make this more likely of being merged.

**Comment by toughengineer** [comment]
@kobalicek, the `Lib` section was missing altogether, hence the addition of `AdditionalDependencies` should not affect compatibility in any way. So, to be precise, it should look something like this:
```xml
<Lib>
  <AdditionalLibraryDirectories>$(ConanLibraryDirectories)%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
  <AdditionalDependencies>{libs}%(AdditionalDependencies)</AdditionalDependencies>
</Lib>
```
If the generated props file does not specify it, I believe you would have to _manually_ specify the libs to link against somewhere anyway, which is not what we want.

**Comment by jgsogo** [comment]
This is going to be merged to `1.19` which will be released by the end of this month... so just a little bit more patience. 👍

**Comment by memsharded** [comment]
Merged, will be in next 1.19 release.

Thanks @kobalicek for the contribution and @toughengineer for the feedback!

**Pull request merged**
