### PR TITLE
Manifest Option to show Path.

### PR DESCRIPTION
**Pull request by luckielordie**
Add #1005 

Changed the manifest manager to log the path to the manifests on logging.

### CODE REVIEW

**Comment by memsharded** [comment]
Good, thank you!

It seems there is some problem with the CLA signing, maybe your commit was done with a different user than your github one. Please check the instructions above.

Also it is nice to add to testing the things that are being changed. In this case it is simple, I guess that you tried it manually, so no need to add them, for the next one :)

Lets wait for CI, will try to include in tomorrows release.

**Comment by memsharded** [comment]
So it seems a couple of tests are broken, we need to fix it. I will have a look right now

**Comment by memsharded** [comment]
I have fixed the tests in this PR: https://github.com/conan-io/conan/pull/1772
One was an error because of latest features merges. The others were the tests for the manifests, that were checking the output, easy to fix.

It already include your commits, so github will acknowledge you as contributor, but please, I still need you to address the CLA issue. Thanks!

**Comment by luckielordie** [comment]
No worries I will address the CLA issue. I had trouble running the tests, I couldn't work out if they were failing because my dev environment was setup wrong. Is there a chat channel I can post to for issues like that in the future? I don't want to clog up the Github with random questions.

**Comment by memsharded** [comment]
#1772 has been merged, you are now an official contributor :)

**Pull request closed without merging**
