### PR TITLE
Introduced Safer FTP Alternative: Added `FTP_TLS`

### PR DESCRIPTION
**Pull request by nydelzaf**
Changelog: Feature: Added `FTP_TLS` option using `secure` argument in `ftp_download` for secure communication.
Docs: Omit

Documentation added to the docstrings here: https://github.com/conan-io/conan/pull/15294

---
## Details
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [files.py](https://github.com/conan-io/conan/blob/release/2.0/conan/tools/files/files.py#L145), method: ftp_download, a clear-text protocol such as FTP, Telnet or SMTP is used. These protocols transfer data without any encryption, which expose applications to a large range of risks. iCR suggested that data should be transferred over only secure transport channels.

## Changes
- Added `FTP_TLS` as an option

## Previously Found & Fixed
- https://www.github.com/jschneier/django-storages/pull/1320
- https://www.github.com/geopython/pycsw/pull/918

## CLA Requirements
*This section is only relevant if your project requires contributors to sign a Contributor License Agreement (CLA) for external contributions.*

All contributed commits are already automatically signed off.

> The meaning of a signoff depends on the project, but it typically certifies that committer has the rights to submit this work under the same license and agrees to a Developer Certificate of Origin (see [https://developercertificate.org/](https://developercertificate.org/) for more information).
\- [Git Commit SignOff documentation](https://developercertificate.org/)

## Sponsorship and Support
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed – to improve global software supply chain security.

The bug is found by running the Intelligent Code Repair (iCR) tool by OpenRefactory and then manually triaging the results.

### CODE REVIEW

**Review by memsharded — APPROVED** [review]
Many thanks for your contribution @fazledyn-or !

It is looking good. 
The ``ftp_download`` is not tested because it was problematic in CI. 
Have you tested this manually?

**Comment by nydelzaf** [comment]
I couldn't test manually since I don't have an FTP server set up.

However, if I find opportunity, I'll do so and notify here.

**Comment by memsharded** [comment]
> I couldn't test manually since I don't have an FTP server set up.

What was the driver/reason to submit this PR then? 🙂 I thought that you had needed this to connect to some ftp server safely

**Comment by nydelzaf** [comment]
We're working in collaboration with [OpenSSF](http://openssf.org) in Project Alpha Omega. We are using various SAST tools to scan top 10,000 Python & Java projects in GitHub. Based on the reports, we triage manually and fix the bugs found in open source projects.

The SAST tools generate results where plain text communication such as SMTP, FTP, HTTP are used. In those cases, such as this one, we add safer alternatives (SMTP with SSL/TLS, FTP TLS, etc.). Which aren't actually bug fixes, rather feature implementation.

**Review by memsharded — APPROVED** [review]

**Pull request merged**
