### PR TITLE
fixes issue 12568

### PR DESCRIPTION
**Pull request by MarkoMin**
Changelog: Fix : Simple fix of issue #12568 

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

Didn't open any PR for this change because it is trivial. Notify me if that should be done anyways.

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by MarkoMin** [comment]
For some reason it says " Contributor License Agreement is not signed yet." but I signed it...

**Comment by memsharded** [comment]
Hi @MarkoMin 

> For some reason it says " Contributor License Agreement is not signed yet." but I signed it...

This happens sometimes when the email used locally to do the commits in your PR do not match the one of your Github account. If you could please check that, that could fix it.

**Comment by MarkoMin** [comment]
Fixed. What about the 5th task? Do I need to open PR on conan docs for this?

**Review by memsharded — APPROVED** [review]

**Comment by memsharded** [comment]
> Fixed. What about the 5th task? Do I need to open PR on conan docs for this?

No, not necessary, that is mostly for bigger changes and also mostly for continuous 1.X releases.

Thanks very much for contributing!

**Pull request merged**
