### PR TITLE
renaming new cmake build helper for toolchain

### PR DESCRIPTION
**Pull request by memsharded**
Changelog: Bugfix: Rename new toolchain build helper to ``CMakeCmd`` to allow inheritance
Docs: https://github.com/conan-io/docs/pull/XXXX

Fix https://github.com/conan-io/conan/issues/7196

#tags: slow

### CODE REVIEW

**Comment by jgsogo** [comment]
Not with a metaclass, but overriding the `__new__` in a CMake class we can implement something that behaves like a factory function... wdyt?

image


```python

# This are the two build helpers we already have

class CMakeLegacy(object):
    def __init__(self, *args, **kwargs):
        print("CMakeLegacy::__init__")
        print(" - args: {}".format(args))

    def who(self):
        print("This is the LEGACY cmake")


class CMakeToolchain(object):
    def __init__(self, *args, **kwargs):
        print("CMakeToolchain::__init__")
        print(" - args: {}".format(args))

    def who(self):
        print("TOOLCHAIN for the Win!")


# This is the one exported in `form conans import CMake`

class CMake(object):
    def __new__(cls, has_toolchain):
        """ Inject the proper CMake base class in the hierarchy """
        
        # If already injected, create and return
        if CMakeToolchain in cls.__bases__ or CMakeLegacy in cls.__bases__:
            return super(CMake, cls).__new__(cls)

        # If not, add the proper CMake implementation
        if has_toolchain:
            CustomCMakeClass = type("CustomCMakeClass", (cls, CMakeToolchain), {})
        else:
            CustomCMakeClass = type("CustomCMakeClass", (cls, CMakeLegacy), {})

        return CustomCMakeClass.__new__(CustomCMakeClass, has_toolchain)

    def __init__(self, *args, **kwargs):
        super(CMake, self).__init__(*args, **kwargs)



if __name__ == "__main__":
    has_toolchain = True  # Minimal example of a conanfile

    print("-"*20)
    cmake = CMake(has_toolchain)
    cmake.who()

    print("-"*20)

    class OtherCMake(CMake):
        def __init__(self, *args, **kwargs):
            super(OtherCMake, self).__init__(*args, **kwargs)
            print("OtherCMake::__init__")

        def who(self):
            super(OtherCMake, self).who()
            print("OtherCMake::who")

    other = OtherCMake(has_toolchain)
    other.who()

```

**Comment by memsharded** [comment]
I like the idea, but quick question, how do you inject the ``has_toolchain`` selector onto something that the user imports?

**Comment by jgsogo** [comment]
No, the `has_toolchain` is the `conanfile, *args, **kwargs` that the user is already passing to the `CMake(conanfile=self, ....)`.

**Comment by memsharded** [comment]
Superseded by #7200

**Pull request closed without merging**
