### PR TITLE
Issue #2982: set WSLENV environment variable when using WSL bash

### LINKED ISSUE #2982: AutoToolsBuildEnvironment doesn't find dependencies when using Windows Bash
Conan version: 1.4
OS: Windows 10, version 1803, build 17134.1, Windows subsystem for Linux installed (openSuse)

I tried to build the following recipe:
https://github.com/wdobbe/conan-graphicsmagick.git

On Linux the (autoconf) configure script of GraphicsMagick finds the libjpeg and libpng that Conan installed. However on Windows both libjpeg and libpng are not detected. (Note that the configure script will not complain too hard about this, and compilation will start anyway).

When I open a windows bash prompt myself, set CPPFLAGS and LDFLAGS to the locations where Conan installed libjpeg and libpng and then run the configure script, it does detect both libraries.

So it looks like the CPPFLAGS and LDFLAGS environment variables that are set up by AutoToolsBuildEnvironment are not picked up by the configure script.

### PR DESCRIPTION
**Pull request by wdobbe**
Only bug fix, no need for documentation change. Closes #2982

### CODE REVIEW

**Comment by wdobbe** [comment]
Hmm, I have signed the CLA 5 minutes ago, but CLAassistant still says 'not signed yet' .

**Comment by lasote** [comment]
This is very interesting. Many thanks. I will give it a try but looks good!

**Comment by lasote** [comment]
Please, look at my PR here: https://github.com/conan-io/conan/pull/3104/files and to my last comment in the issue. I'm really not sure if passing LDFLAGS, CPPFLAGS, and so on to the subsystem will work. Did you try?

**Comment by lasote** [comment]
Could you try again? I updated the PR and tried with `https://github.com/wdobbe/conan-graphicsmagick` now it fails after building several things but for a missing include, so maybe it is ok now.

**Comment by lasote** [comment]
I'm closing this PR because we consider that the solution for the WSL env vars should be more general, not so attached to the AutoToolsBuildEnvironment.

**Comment by wdobbe** [comment]
I tested with lasote:feature/wsl_env_vars branch, but libpng and libjpeg are not found by the configure script:

```
GraphicsMagick/1.3.30@dynniq/stable: JBIG              --with-jbig=no           no
GraphicsMagick/1.3.30@dynniq/stable: JPEG v1           --with-jpeg=yes          no
GraphicsMagick/1.3.30@dynniq/stable: JPEG-2000         --with-jp2=no            no
GraphicsMagick/1.3.30@dynniq/stable: LCMS v2           --with-lcms2=no          no
GraphicsMagick/1.3.30@dynniq/stable: LZMA              --with-lzma=no           no
GraphicsMagick/1.3.30@dynniq/stable: Magick++          --with-magick-plus-plus=yes      yes
GraphicsMagick/1.3.30@dynniq/stable: PERL              --with-perl=no                   no
GraphicsMagick/1.3.30@dynniq/stable: PNG               --with-png=yes           no
GraphicsMagick/1.3.30@dynniq/stable: TIFF              --with-tiff=yes          no

```

Yes, the build of GraphicksMagick will fail because of a missing header file in the mingw installer, that is not important now. Just before the compilation start the configure script of graphicsMagick will show a status overview (of which I copy/pasted a part). In that overview check for the following output:

GraphicsMagick/1.3.30@dynniq/stable: JPEG v1           --with-jpeg=yes          **yes**
GraphicsMagick/1.3.30@dynniq/stable: PNG               --with-png=yes           **yes**

**Comment by lasote** [comment]
great! thanks

**Comment by lasote** [comment]
Hi again, is that working with this pull request code?

**Comment by lasote** [comment]
Would you mind to paste here the profile you are using? (or -s parameters)

**Comment by wdobbe** [comment]
My MinGW profile:

```
[build_requires]
mingw_installer/1.0@conan/stable
ninja_installer/1.8.2@conan/testing

[settings]
os_build=Windows
os=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=5.3
compiler.exception=seh
compiler.libcxx=libstdc++
compiler.threads=posix
build_type=Debug
```

**Comment by lasote** [comment]
Thank you. I've found a bug in my branch and pushed, but now with both your branch and mine I'm getting the same result, jpeg "yes" but png "false".  Could you try if you get a different result? Thanks for your help!

**Comment by wdobbe** [comment]
With that last commit, the GraphicsMagick seems to use the WSL gcc i.s.o. the conan installed MinGW:


```
Project: checking for gcc... gcc
Project: checking whether the C compiler works... no
Project: configure: error: in `/mnt/c/Users/wdobbe/generated/conan-graphicsmagick_build/tmp/build':
Project: configure: error: C compiler cannot create executables
Project: See `config.log' for more details
ERROR: GraphicsMagick/1.3.30@PROJECT: Error in build() method, line 79
        env_build.configure(configure_dir=os.path.join(self.source_folder, self.source_subfolder), args=config_args)
        ConanException: Error 77 while executing /mnt/c/Users/wdobbe/generated/conan-graphicsmagick_build/tmp/source/GraphicsMagick-1.3.30/configure --enable-shared=yes --enable-static=no --with-bzlib --with-jpeg --with-png --without-dps --without-fpx --without-jbig --without-jp2 --without-lcms2 --without-lzma --with-magick-plus-plus --without-perl --without-trio --without-webp --without-wmf --with-zlib --prefix=/mnt/c/Users/wdobbe/generated/conan-graphicsmagick_build/tmp/package --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32
```

In config.log:

```
## ----------- ##
## Core tests. ##
## ----------- ##

configure:3122: checking build system type
<cut>
configure:3971: checking for x86_64-w64-mingw32-gcc
configure:4001: result: no
configure:4011: checking for gcc
configure:4027: found /usr/bin/gcc
configure:4038: result: gcc
configure:4267: checking for C compiler version
configure:4276: gcc --version >&5
gcc (SUSE Linux) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:4287: $? = 0
configure:4276: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/4.8/lto-wrapper
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.8 --enable-ssp --disable-libssp --disable-plugin --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --disable-libmudflap --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --enable-linker-build-id --enable-linux-futex --program-suffix=-4.8 --without-system-libunwind --with-arch-32=i586 --with-tune=generic --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 4.8.5 (SUSE Linux) 
configure:4287: $? = 0
configure:4276: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:4287: $? = 1
configure:4276: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:4287: $? = 1
configure:4307: checking whether the C compiler works
configure:4329: gcc -m64 -g -fPIC -I/mnt/c/Users/wdobbe/.conan/data/mingw_installer/1.0/conan/stable/package/b2a5c106cd30b29d475da50a9633d31c2329d6bd/include -I/mnt/c/Users/wdobbe/.conan/data/bzip2/1.0.6/dynniq/stable/package/f209717a097a973e6f44c80137dc3f1e3aac7cb0/include -I/mnt/c/Users/wdobbe/.conan/data/libjpeg/9b/dynniq/stable/package/2d8c92555b1f4cbde30bc3ec3c98b1cecde16843/include -I/mnt/c/Users/wdobbe/.conan/data/libpng/1.6.34/dynniq/stable/package/99b6158424a12dedf9f7f609ff6ffd22e00bdfb4/include -I/mnt/c/Users/wdobbe/.conan/data/zlib/1.2.11/dynniq/stable/package/2d8c92555b1f4cbde30bc3ec3c98b1cecde16843/include -D_GLIBCXX_USE_CXX11_ABI=0 -m64 -L/mnt/c/Users/wdobbe/.conan/data/mingw_installer/1.0/conan/stable/package/b2a5c106cd30b29d475da50a9633d31c2329d6bd/lib -L/mnt/c/Users/wdobbe/.conan/data/bzip2/1.0.6/dynniq/stable/package/f209717a097a973e6f44c80137dc3f1e3aac7cb0/lib -L/mnt/c/Users/wdobbe/.conan/data/libjpeg/9b/dynniq/stable/package/2d8c92555b1f4cbde30bc3ec3c98b1cecde16843/lib -L/mnt/c/Users/wdobbe/.conan/data/libpng/1.6.34/dynniq/stable/package/99b6158424a12dedf9f7f609ff6ffd22e00bdfb4/lib -L/mnt/c/Users/wdobbe/.conan/data/zlib/1.2.11/dynniq/stable/package/2d8c92555b1f4cbde30bc3ec3c98b1cecde16843/lib conftest.c -lbz2 -ljpeg -lpng -lzlib >&5
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lpng
collect2: error: ld returned 1 exit status
configure:4333: $? = 1
configure:4371: result: no
configure: failed program was:
```

**Comment by wdobbe** [comment]
Hmm, yes, my branch now also uses WSL gcc in the configure script. It used to work, so I'll have to see what has changed.

**Comment by lasote** [comment]
I'm reopening this PR to keep the discussion open ;)

**Comment by lasote** [comment]
Any updates on this?

**Comment by lasote** [comment]
Hi, I prefer to clarify if my implementation works correctly before merge it. I'm assigning this to 1.8. 
Please, if you have further information would be nice to complete the feature.

**Comment by memsharded** [comment]
This became inactive, and now obsolete. New build system integrations are now in https://docs.conan.io/en/latest/reference/conanfile/tools.html, please report issues against them.

**Pull request closed without merging**
