### PR TITLE
Add --askpass argument to 'sudo' if it is not an interactive terminal

### LINKED ISSUE #3285: sudo in SystemPackageTool always fails when in non-interactive terminal
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

### Problem
Commands using `sudo` in SystemPackageTool always fail when used in non-interactive terminal.
This issue originated from https://github.com/bincrafters/community/issues/378. 
Example: Loading a project using cmake-conan wrapper in Qt Creator, with not yet built Qt as Conan dependency.

### Proposal
This could be solved by detecting if we're in non-interactive terminal and telling `sudo` to get password from a specified `askpass` program. It could be controlled with an extension to a variable [CONAN_SYSREQUIRES_SUDO](https://docs.conan.io/en/latest/reference/env_vars.html#conan-sysrequires-sudo) or a new variable, like CONAN_SYSREQUIRES_SUDO_MODE.

Example: `sudo --askpass apt update` will try to use program from SUDO_ASKPASS, or sudo.conf, or fail. A popular application for that is `ssh-askpass`.

From sudo manual:

> -A, --askpass
>    Normally, if sudo requires a password, it will read it from the user's terminal.  If the -A (askpass) option is specified, a (possibly graphical) helper program is executed to read the
>    user's password and output the password to the standard output.  If the SUDO_ASKPASS environment variable is set, it specifies the path to the helper program.  Otherwise, if sudo.conf(5)
>    contains a line specifying the askpass program, that value will be used.  For example:
> 
>        # Path to askpass helper program
>        Path askpass /usr/X11R6/bin/ssh-askpass
> 
>    If no askpass program is available, sudo will exit with an error.

### Steps to reproduce
conanfile.txt
```
[requires]
Qt/5.11.1@bincrafters/stable

[options]
*:shared=True

[generators]
cmake
```
CMakeLists.txt
```
cmake_minimum_required(VERSION 3.10)

project(conan-qt-test LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
   message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
   file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/v0.12/conan.cmake"
       "${CMAKE_BINARY_DIR}/conan.cmake")
endif()
include(${CMAKE_BINARY_DIR}/conan.cmake)
conan_cmake_run(
    CONANFILE conanfile.txt
    BASIC_SETUP
    BUILD missing)

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})
```
main.cpp
```
#include <QtCore/QDebug>

int main()
{
    qDebug() << "hello\n";
    return 0;
}
```
**Steps:**
* Open Qt Creator
* Click File -> Open file or project
* Find CMakeLists.txt and click Open
* Select your kit, click on details, uncheck Default, click Configure Project

**Expected result:**
CMake + Conan configuration should succeed.

**Actual result:**
CMake + Conan configuration fails with:
```
Running "/usr/local/bin/cmake -E server --pipe=/tmp/cmake-.BlsLST/socket --experimental" in /home/fazer/dev/project/test/build-conan-cmake-qtcreator-bug-Desktop-Debug.
Starting to parse CMake project, using: "-DCMAKE_BUILD_TYPE:STRING=Debug", "-DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++-8", "-DCMAKE_C_COMPILER:STRING=/usr/bin/gcc-8", "-DCMAKE_PREFIX_PATH:STRING=".
The CXX compiler identification is GNU 8.1.0
Check for working CXX compiler: /usr/bin/g++-8
Check for working CXX compiler: /usr/bin/g++-8 -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Downloading conan.cmake from https://github.com/conan-io/cmake-conan
Conan ** WARNING** : This detection of settings from cmake is experimental and incomplete. Please check 'conan.cmake' and contribute
Conan executing: conan install /home/fazer/dev/project/test/conan-cmake-qtcreator-bug/conanfile.txt -g cmake -s build_type=Debug -s os=Linux -s compiler=gcc -s compiler.version=8 -s compiler.libcxx=libstdc++11 --build=missing
CMake Error at /home/fazer/dev/project/test/build-conan-cmake-qtcreator-bug-Desktop-Debug/conan.cmake:335 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  /home/fazer/dev/project/test/build-conan-cmake-qtcreator-bug-Desktop-Debug/conan.cmake:413 (conan_cmake_install)
  CMakeLists.txt:14 (conan_cmake_run)

Configuring incomplete, errors occurred!
See also "/home/fazer/dev/project/test/build-conan-cmake-qtcreator-bug-Desktop-Debug/CMakeFiles/CMakeOutput.log".
CMake Project parsing failed.
```
Note that due to a bug in CMake (https://gitlab.kitware.com/cmake/cmake/issues/17931), it doesn't pass the `conan install` command output to Qt Creator to its "General Messages" pane.

However, it is possible to see the output in "Compile Output" pane when you follow these steps:
* Comment Qt/5.11.1@bincrafters/stable in conanfile.txt
* In Qt Creator click Build -> Run CMake
The project will now be configured successfully.
* Uncomment Qt/5.11.1@bincrafters/stable in conanfile.txt
* Click Build -> Run (Ctrl+R)
Result:
```
13:20:15: Running steps for project conan-qt-test...
13:20:15: Starting: "/usr/local/bin/cmake" --build . --target all
[0/1 ?/sec] Re-running CMake...
-- Conan ** WARNING** : This detection of settings from cmake is experimental and incomplete. Please check 'conan.cmake' and contribute
-- Conan executing: conan install /home/fazer/dev/project/test/conan-cmake-qtcreator-bug/conanfile.txt -g cmake -s build_type=Debug -s os=Linux -s compiler=gcc -s compiler.version=8 -s compiler.libcxx=libstdc++11 --build=missing
Running: sudo apt-get update
sudo: no tty present and no askpass program specified
ERROR: Qt/5.11.1@bincrafters/stable: Error in requirements() method, line 111
	installer.update() # Update the package database
	ConanException: Command 'sudo apt-get update' failed
CMake Error at /home/fazer/dev/project/test/build-conan-cmake-qtcreator-bug-Desktop-Debug/conan.cmake:335 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  /home/fazer/dev/project/test/build-conan-cmake-qtcreator-bug-Desktop-Debug/conan.cmake:413 (conan_cmake_install)
  CMakeLists.txt:14 (conan_cmake_run)


-- Configuring incomplete, errors occurred!
See also "/home/fazer/dev/project/test/build-conan-cmake-qtcreator-bug-Desktop-Debug/CMakeFiles/CMakeOutput.log".
FAILED: build.ninja 
/home/fazer/dev/app/cmake/bin/cmake -H/home/fazer/dev/project/test/conan-cmake-qtcreator-bug -B/home/fazer/dev/project/test/build-conan-cmake-qtcreator-bug-Desktop-Debug
ninja: error: rebuilding 'build.ninja': subcommand failed
13:20:15: The process "/usr/local/bin/cmake" exited with code 1.
Error while building/deploying project conan-qt-test (kit: Desktop)
When executing step "CMake Build"
13:20:15: Elapsed time: 00:00.
```
Also note that once the original problem is fixed, you will need to make two changes in CMakeLists.txt in order to compile the program (they weren't in the original version to stop unrelated errors):
* add this line:
`find_package(Qt5 5.11 COMPONENTS Core REQUIRED)`
* changing linking to
`target_link_libraries(${PROJECT_NAME} Qt5::Core)`

### Environment
Conan 1.6.1
Ubuntu 18.04 x64

### PR DESCRIPTION
**Pull request by jgsogo**
Changelog: Fix: Add ``--askpass`` argument to ``sudo`` if it is not an interactive terminal

- [x] closes #3285 

I'm supposing that everywhere ``sudo`` is used, the argument ``--askpassp`` is available. I hope this statement to be true 🤞

### CODE REVIEW

**Comment by ArekPiekarz** [comment]
What happens when we start the noninteractive terminal as root and run conan in a way that triggers installing system packages? Would it succeed without asking for the password? In that case, would `--askpass` unnecessarily block the execution until a password is provided? Or would it be successful anyway?

**Comment by lasote** [comment]
I think in that case "sudo" won't require a password so the `--askpass` argument won't have any effect, but please, @jgsogo can you try?

**Comment by jgsogo** [comment]
On docker ``lasote/conantests``, given

```python
from conans.client.tools.system_pm import SystemPackageTool

sp = SystemPackageTool()
```

Use cases:
1. No-root, tty:
    ```
    >>> sp.install("boost-dev")
    dpkg-query: no packages found matching boost-dev
    Running: sudo apt-get update
    [sudo] password for tom:
    ```

2. No-root, no-tty:
    ```
    >>> sp._tool._sudo_str = "sudo --askpass "
    >>> sp.install("boost-dev")
    dpkg-query: no packages found matching boost-dev
    Running: sudo --askpass apt-get install -y --no-install-recommends boost-dev
    sudo: no askpass program specified, try setting SUDO_ASKPASS
    Traceback (most recent call last):
    ```

3. No-root, no-tty, with SUDO_ASKPASS
    With file ``pw.sh``: 
    ```
    #!/bin/bash
    echo 'invalid-root-pass'
    ```

    and running python with the env variable
    ```
    $ SUDO_ASKPASS=/home/conan/conan/pw.sh python

    ```

    ```
    >>> sp._tool._sudo_str = "sudo --askpass "
    >>> sp.install("boost-dev")
    dpkg-query: no packages found matching boost-dev
    Running: sudo --askpass apt-get update
    Sorry, try again.
    Sorry, try again.
    sudo: 3 incorrect password attempts
    Traceback (most recent call last):
    ...
    ```

3. Root, tty
    ```
    >>> sp.install("ssh")
    dpkg-query: no packages found matching ssh
    Running: sudo apt-get install -y --no-install-recommends ssh
    Reading package lists... Done
    ...
    ```

4. Root, no-tty
    ```
    >>> sp._tool._sudo_str = "sudo --askpass "
    >>> sp.install("vlc")
    dpkg-query: no packages found matching vlc
    Running: sudo --askpass apt-get install -y --no-install-recommends vlc
    Reading package lists... Done
    Building dependency tree       

    ```

I think all casuistry is covered. 👨‍🏫

**Comment by yangcha** [comment]
`sudo --askpass` breaks Centos 6 package installation. The sudo version on Centos 6 is 1.8.6. The option of askpass for sudo version 1.8.7 or older is `sudo -A`.
So `sudo -A` will work on almost every platforms.

**Pull request merged**
