### PR TITLE
Fix short_paths_home validation

### PR DESCRIPTION
**Pull request by santhonisz**
Changelog: Bugfix: Enhance validation of the `short_paths_home` property to correctly handle the scenarios where it is set to a path that contains the value of the Conan cache path, but is not a subdirectory of it.

Fixes: #6273 

- [X] Refer to the issue that supports this Pull Request.
- [X] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [X] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've followed the PEP8 style guides for Python code.
- NA I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by santhonisz** [comment]
Preference would have been to use `os.path.commonpath` but that cannot be done until Python 2.7 support is officially dropped.

**Comment by danimtb** [comment]
Thanks a lot for the PR @santhonisz! Changes look good. Would you mind adding also a small test next to [this one](https://github.com/conan-io/conan/blob/15651a6bd416298afc949eeb5450f43ebfc62471/conans/test/functional/command/config_test.py#L115) verifying the new behavior? Thank you very much 😃

**Comment by danimtb** [comment]
Change base branch to target this for 1.21.1 release. @santhonisz we will need you to update this PR to the changes in branch `release/1.21.1`

**Comment by santhonisz** [comment]
Done!

**Comment by czoido** [comment]
Hi @santhonisz, as this PR ended with some commits from other branches, would you please open a new PR from a branch starting from `release/1.21.1` with just the changes to fix the issue?. I would push to your branch directly but I'm afraid of losing your authorship in the commits if I remove all the commits that should not be merged. Thanks a lot!

**Comment by czoido** [comment]
Hi @santhonisz, I'm opening a [new PR](https://github.com/conan-io/conan/pull/6303) pointing to `release/1.21.1` branch as we want to release this feature. As I have cherry-picked your commits we'll check if you are listed as a contributor after this is merged. 
If that is not the case please make a PR to the [contributors file](https://github.com/conan-io/conan/blob/develop/contributors.txt) with your name so you are listed as contributor as all the credit for the PR is yours.
Thanks a lot!

**Pull request closed without merging**
