### PR TITLE
fixing virtualbuildenv

### LINKED ISSUE #4582: virtualbuildenv generator does not set LIB env var correctly in activate_build.bat
Running **conan install** with -g virtualbuildenv generates activate_build.bat.
The first four env vars set are:
```
SET PROMPT=...
SET CL=...
SET LIB=...
SET_LINK_=...
```
CL and \_LINK\_ are set correctly, but LIB does not contain my "lib_path".

According to the following code, what happens is LIB added to a dictionary with the correct lib_path, but then the call to "update" to add "vc_vars" overwrites the LIB value with the Visual Studio LIB value.

**virtualbuildenv.py**
```javascript
        if compiler == "Visual Studio":
            self.env = VisualStudioBuildEnvironment(conanfile).vars_dict
            self.env.update(vcvars_dict(conanfile.settings, output=conanfile.output))
        else:
            self.env = AutoToolsBuildEnvironment(conanfile).vars_dict
```
This is incorrect.  The lib_path needs to be merged with the Visual Studio LIB value instead of being replaced.

I'm using conan v1.12.3 on Windows 10 and Visual Studio 2015.

### PR DESCRIPTION
**Pull request by memsharded**
Changelog: Bugfix: Fix LIB overwrite in ``virtualbuildenv`` generator
Docs: omit

Close #4582

This PR removes 2 files that were not named "_test" in the test scope, and then not being executed. Please @danimtb check.

### CODE REVIEW

**Comment by memsharded** [comment]
Yes, I already added a test, not a unittest but a integration one, because it happened to be quite broken (and unittest doesn't catch those things), 2 things have to be fixed:
- Not overwriting the lib paths
- The ``_LINK_`` env var is path separated

Please @lasote review.

**Comment by jmoutray** [comment]
(Windows) In trying to work around the issue until 1.13 is released, I discovered that the LIB environment variable "does not apply" unless UseEnv=true:  You must do "**SET UseEnv=True**" (if launching Visual Studio from conanbuildenv prompt) or pass argument "**/p:UseEnv=true**" (if executing msbuild).  See Remarks at https://docs.microsoft.com/en-us/visualstudio/ide/reference/useenv-devenv-exe?view=vs-2017.

I'm not sure what this means for conan.  Maybe activate_build.bat should set this env var.

I am trying to use virtualbuildenv in lieu of updating dependent Visual Studio projects to reference the "conanbuildinfo_multi.props" generated property file.

**Comment by memsharded** [comment]
Thanks for the info @jmoutray 
The truth is that the test is done with:

```python
self.run('activate_build.bat && cl /c /EHsc hello.cpp')
self.run('activate_build.bat && lib hello.obj -OUT:helloapp.lib')
self.run('activate_build.bat && cl /EHsc main.cpp helloapp.lib')
``` 
and it works fine, but yes, it is not the VS MSbuild system

The ``MSBuild`` conan helper is already setting ``'/p:UseEnv=true'``, so I guess it should be only the env-var.

We might try to have a look, but I don't think we will make it for Conan 1.13, because it is going to be released very soon, so we might need to wait.

> I am trying to use virtualbuildenv in lieu of updating dependent Visual Studio projects to reference the "conanbuildinfo_multi.props" generated property file.

I am not sure how far can you get doing this, because the ``conanbuildinfo_multi.props`` works nicely for switching Debug/Release, so if developers are going to use it, it might be more ergonomic than playing with the environment

**Comment by memsharded** [comment]
Trying to test in https://github.com/conan-io/conan/pull/4655, to see what happens with CI.

**Comment by jmoutray** [comment]
One more...  There doesn't appear to be any way to pass the `winsdk_version` to use for the vcvars command for the virtualbuildenv generator.  Using `MSBuild`, I can do this:  `msbuild.build("filename.sln", winsdk_version="8.1")`

Without the "8.1" argument, I get a linker error:
    `LINK : fatal error LNK1158: cannot run 'rc.exe'`

More info at https://stackoverflow.com/questions/14372706/visual-studio-cant-build-due-to-rc-exe#14373113.

**Comment by memsharded** [comment]
Yes, that might be an issue. As commented above, the virtualbuildenv, in case of Visual Studio/MSBuild might be a bit limited, and because of those limitations are inherent to VS/MSbuild, there is nothing that Conan could do.

In any case, the files created by generators are not to configure the build, they convey information strictly from dependencies. The build helpers like ``MSBuild()`` can try to inject some things in the command line, but the generated files like ``activate_build.bat`` are not intended to map build configuration, but mostly information from dependencies like include paths, library paths, library names, etc.

**Comment by memsharded** [comment]
@jmoutray 

The UseEnv=True has been added in https://github.com/conan-io/conan/pull/4655. It will be released next Conan 1.16, please update when it is released and give feedback if it doesn't work.


If the issue about ``winsdk`` is still not solved, I suggest to open a new issue for it, it is difficult to track comments in closed PRs. Thanks!

**Pull request merged**
