### PR TITLE
Update conan_requester.py

### PR DESCRIPTION
**Pull request by trulede**
Hi, I have a problem where proxy settings are _not_ being taken from the environment (so I have to manually specify them in conan.config). In searching for the solution to that problem I noticed that this code might not work as intended. When the popped variable is True the right part of the "or" will not be executed ... and thus not all proxy settings would be cleared (only the first encountered is removed).

Just as an example to check my thinking:
```
>>> False or print("hi")
hi
>>> True or print("hi")
True  <=== the right part of the or did not execute.
```

Do I understand it right? Thanks.

Changelog: Bugfix: Make sure that proxy "http_proxy", "https_proxy", "no_proxy" vars are correctly removed if custom ones are defined in the conan.conf. Also, avoid using ``urllib.request.getproxies()``, they are broken.
Docs: omit

### CODE REVIEW

**Comment by trulede** [comment]
I have a better understanding of why I have a problem with the Proxy settings. In this code:
```
def _call_method(self, method, url, **kwargs):
        popped = False
        if self.proxies or self._no_proxy_match:
            old_env = dict(os.environ)
            # Clean the proxies from the environ and use the conan specified proxies
            for var_name in ("http_proxy", "https_proxy", "no_proxy"):
                popped = True if os.environ.pop(var_name, None) else popped
                popped = True if os.environ.pop(var_name.upper(), None) else popped
        try:
            t1 = time.time()
```
self.proxies will be set; first from the conan.conf file; and then second from a call to urllib.request.getproxies() (conans/client/conf/__init__.py line 431). The problem with that is that getproxies() returns the proxy settings with truncated names, i.e. http_proxy becomes http, and these apparently do not work.

The comment gives a hint of the problem: `Clean the proxies from the environ and use the conan specified proxies.` What is happening is there are _no_ conan specified proxies, however the variable `self.proxies` has been filled by the call to `urllib.request.getproxies()` which itself returns mangled proxy names which were derived from the environment.

Its possible that this worked for a lot of people because the above code was broken and removed only one proxy string from the environment. It was a matter of chance which one it was, in my case the NO_PROXY was taken first ... and calls to local_host would fail (since the call went the the proxy server ... and that did not work at all).

I will make another change to remove the call to `urllib.request.getproxies()` as it is confusing the contents of `self.proxies`.

**Comment by trulede** [comment]
#5170

**Comment by lasote** [comment]
Hi, could you take a look at the failing test? In general, it looks good and we will try to push it to the next release.

**Comment by trulede** [comment]
Thanks, I just made a small change (returning an empty hash). The tests are OK now.

**Comment by memsharded** [comment]
Thanks very much for contributing this fix. It will be released in next 1.16

**Pull request merged**
