### PR TITLE
Saving profile list as a json file

### PR DESCRIPTION
**Pull request by mrunderline**
Changelog: Feature: Saving profile list as a json file
Docs: Omit

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

issue #5937

### CODE REVIEW

**Comment by memsharded** [comment]
Hi @mrunderline 

It is looking good, but it would need a couple of details to be complete:

- The functionality would need a test to check that it is ok, but more importantly, that it doesn't break in the future because other changes. Please take a look to the ``conans/test/functional/command/profile_test.py``, use one of those as a base, and add the ``--json`` argument, load the resulting file (with ``client.load()`` helper), and check the result is the expected one.
- The ``docs`` cannot be "omit" for this PR, because it is changing the behavior. Please submit a PR to https://github.com/conan-io/docs (reference/commands section)

Many thanks for this contribution!

**Comment by mrunderline** [comment]
Hi @memsharded 
Thanks for your attention and kind comment.
I've added a unit test, and would you help more for documenting? 
Is `/reference/commands/misc/profile.rst` a correct file for editing? should I add an optional arguments?

**Comment by memsharded** [comment]
Good, merged! Welcome to the Conan contributors :)

Yes, the /reference/commands/misc/profile.rst is where it should go. Just adding the optional argument in the command line reference is good, no need for examples or further explanation, just to be sure that what is in the docs is consistent with the ``conan profile list --help`` output.

**Comment by mrunderline** [comment]
thank's a lot! I also sent a PR for documents on https://github.com/conan-io/docs/pull/1449

**Comment by memsharded** [comment]
Thanks for the docs @mrunderline

**Pull request merged**
