### PR TITLE
Feature: add test for hard-links preserved

### LINKED ISSUE #6810: [bug] hard links are not preserved during creation of conan_package.tgz
Dear Conan Community, thank you all for your valuable time and great work: **We simply love Conan!**

There is an issue when using Conan to package tools and compilers from tar balls (i.e. cross compilation toolchains) which are containing many hard links. To reduce the size on the hard disk, many existing toolchains are packaged as *.tar.bz2 file and in there are a lot of the same files which are hard linked together.

Finding: The hard links are ignored, when creating the final conan_package.tgz. Conan creates copies of the files.

This results in larger Conan packages and a slower package creation and upload process. Depending on the toolchain, the Conan package size is one to several GB larger.

### Environment Details
  * Operating System + version: Ubuntu 18.04 + Mac OS 10.15.4
  * Conan version: 1.24
  * Python version: 3.x ; 3.7.7

### Steps to reproduce

Created a tar.gz file with hard links, file_10MB is the original file, link1..link4 are hard links:

```
dd if=/dev/urandom bs=1024 count=10000 of=**file_10MB** conv=notrunc
ln file_10MB file_10MB_link1
...
ln file_10MB file_10MB_link4
tar zcvf file* hard_links_example.tar.gz
```

File structure, all file* pointing to the same inode:

```
ls -liha
9971364 -rw-r--r--   5 mike  staff   9,8M  6 Apr 20:15 file_10MB
9971364 -rw-r--r--   5 mike  staff   9,8M  6 Apr 20:15 file_10MB_link1
9971364 -rw-r--r--   5 mike  staff   9,8M  6 Apr 20:15 file_10MB_link2
9971364 -rw-r--r--   5 mike  staff   9,8M  6 Apr 20:15 file_10MB_link3
9971364 -rw-r--r--   5 mike  staff   9,8M  6 Apr 20:15 file_10MB_link4
9971361 -rw-r--r--   1 mike  staff   9,8M  6 Apr 20:48 hard_links_example.tar.gz
```

Tar respects the hard links, size of resulting tarball is 10MB.

Now create a Conan package with this conanfile.py:

```
import os
from conans import ConanFile, tools

class ToolchainConan(ConanFile):
    name = "toolchain-example"
    version = "1.0"
    author = "user"
    # An example tar.gz with a 10 MB file and 4 hard links to it
    url="https://lithium.li/hard_links_example.tar.gz"

    @property
    def default_user(self):
        return "user"

    @property
    def default_channel(self):
        return "channel"

    def build(self):
        tools.download(self.url, "hard_links_example.tar.gz", verify="true")
        tools.unzip("hard_links_example.tar.gz", self.package_folder)
        os.unlink("hard_links_example.tar.gz")

    def package(self):
        self.output.info("tar.gz extracted to package folder to preserve hard links")
```

### Logs

```
conan create . && conan upload '*' -r *** --allExporting package recipe
toolchain-example/1.0: A new conanfile.py version was exported
toolchain-example/1.0: Folder: /Users/mike/.conan/data/toolchain-example/1.0/user/channel/export
toolchain-example/1.0: Exported revision: 3a1b53f51b2a5ab995328574f6ef57ea
Configuration:
[settings]
...
toolchain-example/1.0@user/channel: Forced build from source
Installing package: toolchain-example/1.0@user/channel
Requirements
    toolchain-example/1.0@user/channel from local cache - Cache
Packages
    toolchain-example/1.0@user/channel:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build

Installing (downloading, building) binaries...
toolchain-example/1.0@user/channel: Configuring sources in /Users/mike/.conan/data/toolchain-example/1.0/user/channel/source
toolchain-example/1.0@user/channel: Copying sources to build folder
toolchain-example/1.0@user/channel: Building your package in /Users/mike/.conan/data/toolchain-example/1.0/user/channel/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
toolchain-example/1.0@user/channel: Generator txt created conanbuildinfo.txt
toolchain-example/1.0@user/channel: Calling build()
Downloading hard_links_example.tar.gz completed [10003.41k]

toolchain-example/1.0@user/channel: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' built
toolchain-example/1.0@user/channel: Build folder /Users/mike/.conan/data/toolchain-example/1.0/user/channel/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
toolchain-example/1.0@user/channel: Generated conaninfo.txt
toolchain-example/1.0@user/channel: Generated conanbuildinfo.txt
toolchain-example/1.0@user/channel: Generating the package
toolchain-example/1.0@user/channel: Package folder /Users/mike/.conan/data/toolchain-example/1.0/user/channel/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
toolchain-example/1.0@user/channel: Calling package()
toolchain-example/1.0@user/channel: tar.gz extracted to package folder to preserve hard links
toolchain-example/1.0@user/channel package(): Packaged 5 files
toolchain-example/1.0@user/channel: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' created
toolchain-example/1.0@user/channel: Created package revision 38b0db1137f3f356e544095e33fb9fd0
Are you sure you want to upload 'toolchain-example/1.0@user/channel' to 'kube'? (yes/no): y
Uploading to remote 'kube':
Uploading toolchain-example/1.0@user/channel to remote 'kube'
Uploaded conanfile.py -> toolchain-example/1.0@user/channel [0.72k]
Uploaded conanmanifest.txt -> toolchain-example/1.0@user/channel [0.06k]
Uploaded conan recipe 'toolchain-example/1.0@user/channel' to 'kube': https://***/artifactory/api/conan/conan
Uploading package 1/1: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 to '***'
Compressing conan_package.tgz completed [5 files]
Uploaded conan_package.tgz -> toolchain-example/1.0@user/channel:5ab8 **[50015.90k]**
Uploaded conaninfo.txt -> toolchain-example/1.0@user/channel:5ab8 [0.15k]
Uploaded conanmanifest.txt -> toolchain-example/1.0@user/channel:5ab8 [0.30k]
```

After creation everything is fine, because we extract directly to the package folder. But when uploading the final package is created with a much larger size (50MB).

What we tried so far:
- Tar in Tar ... it works, but we want small and very fast downloadable Conan tool packages in our CI
- Symlinks are not affected by this issue and fully working ... is the cross compiler working after converting all the hard links into symlinks?
- Just use the recipe and do not try to upload, how to prevent re-packaging and upload for everyone?

We think Conan should support hard links in the (mid term) future.
Thank you for your help and ideas!

B.r.
Mike

### PR DESCRIPTION
**Pull request by SSE4**
Changelog: Feature: add test for hard-links preserved
Docs: omit

closes: #6810 

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [ ] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by uilianries** [comment]
Consider https://github.com/SSE4/conan/pull/12

**Comment by uilianries** [comment]
It's broken, but I think it comes from Develop branch, I can reproduce a similar error and running test for develop branch on my machine®

**Comment by SSE4** [comment]
any ideas?
```
======================================================================

ERROR: test_conan_data_as_source (disabled_revisions.conans.test.functional.conanfile.conan_data_test.ConanDataTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/tmp/source/dec4/py36/disabled_revisions/conans/test/functional/conanfile/conan_data_test.py", line 134, in test_conan_data_as_source

    client.run("create . {}".format(ref))

  File "/tmp/source/dec4/py36/disabled_revisions/conans/test/utils/tools.py", line 708, in run

    error = self.run_cli(command_line, user_io=user_io, assert_error=assert_error)

  File "/tmp/source/dec4/py36/disabled_revisions/conans/test/utils/tools.py", line 693, in run_cli

    self._handle_cli_result(command_line, assert_error=assert_error, error=error)

  File "/tmp/source/dec4/py36/disabled_revisions/conans/test/utils/tools.py", line 733, in _handle_cli_result

    raise Exception(exc_message)

Exception: 
```

**Comment by SSE4** [comment]
@uilianries this breaks lots of tests, unfortunately. I think this [line](https://github.com/conan-io/conan/pull/8099/files#diff-c2ca7643fc907db00b41a346805bc9926f9a77adeaefebb10f42d5c528544536R114) is harmful, as `FileCopier` filters out some files like `.git` (while `shutil` doesn't)
something else has to be used instead (re-implement `shutil.copytree`? or maybe overriding `copy_function` is enough)

**Comment by SSE4** [comment]
seems like `copy_function` isn't available in all python versions...

**Comment by uilianries** [comment]
Thanks for checking, I'll investigate.

**Comment by uilianries** [comment]
According Python docs: 

> Changed in version 3.2: Added the copy_function argument to be able to provide a custom copy function. Added the ignore_dangling_symlinks argument to silent dangling symlinks errors when symlinks is false.

https://docs.python.org/3/library/shutil.html#shutil.copytree

**Comment by SSE4** [comment]
yep, but 2.7 doesn't have it :(

**Comment by uilianries** [comment]
@SSE4 Please, take a look on https://github.com/SSE4/conan/pull/13

**Comment by uilianries** [comment]
@SSE4 New fix: https://github.com/SSE4/conan/pull/14

The current error occurred because there is a copy in build folder, but it should be a hard link instead (same inode as all other files).

**Comment by SSE4** [comment]
CI passed, I think test is good to be merged now

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
@SSE4 Could you please solve this conflict?

**Comment by SSE4** [comment]
@uilianries I am not sure why does it conflict, I don't remember if we did changes in that area:
```
<<<<<<< preserve_hard_links
            if not os.path.isdir(package_folder):
                raise ConanException("Package '%s' corrupted. Package folder must exist: %s\n"
                                     "Try removing the package with 'conan remove'"
                                     % (str(pref), package_folder))

=======
            assert os.path.isdir(package_folder), ("Package '%s' folder must exist: %s\n"
                                                   % (str(pref), package_folder))
>>>>>>> develop
```
which code block is correct one now?

**Comment by uilianries** [comment]
> @uilianries I am not sure why does it conflict, I don't remember if we did changes in that area:
> 
> ```
> <<<<<<< preserve_hard_links
>             if not os.path.isdir(package_folder):
>                 raise ConanException("Package '%s' corrupted. Package folder must exist: %s\n"
>                                      "Try removing the package with 'conan remove'"
>                                      % (str(pref), package_folder))
> 
> =======
>             assert os.path.isdir(package_folder), ("Package '%s' folder must exist: %s\n"
>                                                    % (str(pref), package_folder))
> >>>>>>> develop
> ```
> 
> which code block is correct one now?

I would keep:

```
if not os.path.isdir(package_folder):
                raise ConanException("Package '%s' corrupted. Package folder must exist: %s\n"
                                     "Try removing the package with 'conan remove'"
                                     % (str(pref), package_folder))
```

`ConanException` is better than an `AssertError`, and that error message is better described.

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
@SSE4 This PR should target 2.0, following its new milestone.

**Comment by memsharded** [comment]
Closing this as outdated, it seems hard-links is not something that will be supported.

**Pull request closed without merging**
