### PR TITLE
testing updated Pyyaml

### PR DESCRIPTION
**Pull request by memsharded**
Changelog: omit
Docs: omit

@tags: slow
@PYVERS: py27, py36, py34

Comes from https://github.com/conan-io/docs/issues/1244

### CODE REVIEW

**Comment by lasote** [comment]
If this a draft to see what happen or do you really think we should unlock it to any higher version?

**Comment by memsharded** [comment]
Yes, sorry, it should be a draft, I clicked the button too fast, and it cannot be changed to draft later.

**Comment by memsharded** [comment]
Now, the CI is green, should we constraint the requirement to something like?:

```
PyYAML>=3.11, <6.0
```

Assuming that all 5.X versions won't break Conan?  I have updated the PR to include that.

There are other requirements not bounded like ``fasteners`` or ``six``, but it is unlikely that they will get major versions released.

**Comment by lasote** [comment]
Sure, I think we are ok doing that. We could just release a minor if we release any problem, but if apparently is working, go ahead.

**Pull request merged**
