### PR TITLE
Add parallel option to CMake.build()

### PR DESCRIPTION
**Pull request by sixten-hilborn**
See issue #1026.
Not sure how to handle Visual Studio, as it requires the `/MP` flag at the configuration step.

### CODE REVIEW

**Comment by memsharded** [comment]
Great, thanks for this contribution. I think @piponazo might know how to do parallel builds on Win via cmake, from what I know it is not evident. I think necessary to add /MP[X] to CXXFLAGS/CFLAGS, but this is not a good idea from what I know, as they contain some defaults that are lost if you just define them in the command line.

Maybe using the conan flags, because they get appended, not overwrite the default flags. CONAN_CXX_FLAGS/CONAN_C_FLAGS 

In any case, this can be moved forward even if not implemented fo VS, but then at least a warning should be printed.

**Comment by sixten-hilborn** [comment]
Adding ``/MP`` to ``CONAN_*_FLAGS`` should work. The drawback is that the ``parallel`` argument needs to be moved to ``configure()`` instead, which seems less intuitive at least for make users.
I can do these updates before merge so that we don't need to change the interface later.

**Comment by memsharded** [comment]
Maybe moving the parallel arg to the constructor, so it is the same for all?
Another improvement could be using a different number of cores than ``cpu_count``. I think that some people will not want to use the full capacity, but maybe half, to speed things, but leave resources to other (CI server?) tasks. This could be done just by providing a number to parallel, using it instead of cpu_count().

**Comment by piponazo** [comment]
I think somebody pinged me 😋 . In our case we did not take care of the "parallelization" of the builds for the windows packages but we use `/MP` internally in our project by setting the CMAKE_CXX_FLAGS. Something to take into account is that /MP is automatically disabled on Debug configuration because of the incremental builds (/Gm). More info [here](https://msdn.microsoft.com/en-us/library/bb385193.aspx).

Something in which I also thought a long time ago was in the usage of the Ninja generator for parallelizing the builds in CMake projects. In that case we would not need to specify the number of compilation threads since it is computed automatically.

Anyways, this PR looks promising ;)

**Comment by memsharded** [comment]
Thanks very much @piponazo for the feedback!

**Comment by sixten-hilborn** [comment]
Thanks for your input @memsharded and @piponazo !
I was also thinking about configurable `cpu_count`, but in my opinion that should be an option for package consumers, not package creators. What about having a setting in `conan.conf` for max CPU cores conan may use?

For the `/Gm` flag, should it just be overridden/removed if `parallel=True`? Conan isn't designed to do incremental builds anyway.

**Comment by lasote** [comment]
I agree it should be a consumer thing. Maybe the consumer conan.conf var can override the default cpu_count() return.

**Comment by memsharded** [comment]
Yes, I also think that a conan.conf var would be the best way, good idea.

Yes, I think that /Gm can be removed if it is bad for building debug configs in parallel, you are right, incremental builds are never done in conan.

In that case, I wonder why the package creators should specify any "parallel" parameter, as it is going to be always overriden by the user configuration.

**Comment by sixten-hilborn** [comment]
@memsharded are you suggesting `parallel=True` should be the default? Sounds fine to me.
There could be reasons/cases where serial execution is preferred, so package creators should still be able to disable the parallel flag.

**Comment by memsharded** [comment]
Yes, probably, so it might be enabled by default with CPUs=1 or maybe CPUs=max(1, count/2), defined in conan.conf, so users can easily change it. Yes, package creators should be able to explicitly disable parallel builds, just in case.

**Comment by lasote** [comment]
I like the following approach: default `parallel=False` (I'm afraid to break something if we change the default behavior), if package creator set it to True it will build with `cpu_count`. Consumer can configure the `cpu_count` in its conan.conf, defaulted to... 1? <= Maybe it's better to keep it simple.

**Comment by sixten-hilborn** [comment]
Sounds good, except I believe default for `cpu_count` should be to use the number of available cores (current behaviour) which then can be overriden by the consumer if needed.

**Comment by memsharded** [comment]
This would only apply to the new CMake methods, which have just been introduced, I think the default can be defined now without breaking existing builds.

**Comment by lasote** [comment]
Ok, let's do it that way

**Comment by lasote** [comment]
Hi @sixten-hilborn, I've opened a PR https://github.com/sixten-hilborn/conan/pull/1 resolving the conflicts and updated with develop branch.
We think we can merge this implementation and postpone the visual studio parallelize.

**Comment by sixten-hilborn** [comment]
Thank you @lasote! I've updated the interface so it doesn't need to be changed for implementing parallel for VS.

**Comment by memsharded** [comment]
This PR has been rebased and merged to develop by https://github.com/conan-io/conan/pull/1104.

Thanks very much!

**Pull request closed without merging**
