### PR TITLE
Preliminary support for disabling login prompt (#2502)

### PR DESCRIPTION
**Pull request by lewie-donckers**
Fix for #2502.

- [x] Refer to the issue that supports this Pull   ##Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. Also adding a description of the changes in the ``changelog.rst`` file. https://github.com/conan-io/docs

### CODE REVIEW

**Comment by lewie-donckers** [comment]
Could I get some feedback on the code and tests? Before I invest more time in the tests, I'd like to know whether or not I'm on the right track.

**Comment by danimtb** [comment]
Tests are looking good so far @lewie-donckers 👍

**Comment by memsharded** [comment]
Feature is implemented OK, and perfectly covered by tests.
Code is clean. Great job!

**Comment by memsharded** [comment]
Could you please open a PR to the docs too?

Something simple, just in the Reference section -> Environment variables.

3-4 lines explaining what is this variable for (and saying the conan.conf equivalent) will be perfect. Many thanks!

**Comment by lewie-donckers** [comment]
Awesome!

But TBH, I'm a bit surprised. I thought I would have had to do more:
- There are a lot of commands (all those relating to a remote) that are affected by the setting. Wouldn't you want those covered by the tests as well?
- The setting is now tested by  using the configuration. What about using the environment variable?
- The documentation hasn't been updated yet. (Well, at least not by me.)

**Comment by lewie-donckers** [comment]
I'll give editing the documentation a go. Branch from develop, I assume?

**Comment by memsharded** [comment]
Not really. The rationale is that it is very low risk. See:

```python
disable_login_prompt = getenv("CONAN_DISABLE_LOGIN_PROMPT", "False")
+                if disable_login_prompt == "True":
```

- It is clear that this behavior only fires when that env-var is defined. The rest won't be affected at all. Nothing will break if this var is not defined
- You already covered the case than when this var is defined, it does what you want. 
- If there is some case with CONAN_DISABLE_LOGIN_PROMPT = True that fails, no problem. It is NOT breaking behavior, as it didn't work in the past either
- In any case you already checked that defining this variable don't affect either the behavior of interactive login.

Good enough. Sometimes it is best to release something that it is low risk as this, so it gets a chance to be used and tested by other users, that will discover those possible edge cases.

Docs, branch for develop, yes :)

**Comment by lewie-donckers** [comment]
I think we jumped the gun here. I did some tests and now CONAN_DISABLE_LOGIN_PROMPT has to be set to True for this to work. This is not what is stated in the documentation.

I propose we switch to `get_env()` from `conans.util.env_reader` so setting it to 1 will also work and updating the documentation. I'll go do some pull requests.

**Pull request merged**
