### PR TITLE
Feature/html graph

### PR DESCRIPTION
**Pull request by memsharded**
Generates html interactive graphs.
Inspired and based on the cool job of @austinjmorlan :)

### CODE REVIEW

**Comment by austinjmorlan** [comment]
The help string for the --graph command needs to be updated to match this new behavior because it says it'll generate in the DOT syntax.

**Comment by memsharded** [comment]
Yes @austinjmorlan , you are right, just fixed it, thanks for noticing!

**Comment by austinjmorlan** [comment]
Would it be cleaner/clearer if `--graph` required an argument, and would then generate differently based on that file's extension? And if no argument was provided it would complain. It doesn't seem like either a DOT graph or an HTML graph should be default as both are distinct and have separate uses.

For example:

`conan info .. --graph` would complain about needing an argument and print a message about the available  extensions (dot and html at this point)

`conan info .. --graph=filename.dot` would generate a file with DOT

`conan info .. --graph=filename.html` would generate a file with HTML

This could be extended in the future to support even more extensions if desired.

**Comment by memsharded** [comment]
You are totally right, I have just submitted a commit with the changes, thanks for the suggestion.

**Pull request merged**
