### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by troyvoy88**
fixed url typo

### CODE REVIEW

**Comment by memsharded** [comment]
Hi @troyvoy88 , 

I think you should not PR to release branches. Release branches are used to release, and that includes creating packages and installers for all platforms. If some important bug appears, then a minor patch 0.4.1 should be released.

Can you please submit PRs to the develop branch? Thanks!

In any case, I think that the appveyor build should not have failed, maybe @lasote can have a look at it.

**Comment by jslee02** [comment]
It seems the typo is already fixed by c5b08e06f2d031199e603888b22480a4c50ddb40.

**Comment by memsharded** [comment]
Yes, that's right, and the appveyor build fails because it was introduced after the 0.4 release, so it is expected. Thanks in any case @troyvoy88 for trying to contribute! Very appreciated.

**Comment by troyvoy88** [comment]
Thank you @memsharded  and @jslee02  for the prompt reply. I greatly appreciate the polite response ^_^! I should have read or asked about the development guidelines or just  use common sense jajaja. I'll pull the develop branch mates. Thank you again.

**Pull request closed without merging**
