### PR TITLE
Add VERSION variable to the GNU make generator; add unit test

### PR DESCRIPTION
**Pull request by f18m**
This PR addresses issue #7705

### CODE REVIEW

**Comment by f18m** [comment]
Hi @memsharded ,
I tried to address the issue #7705 I opened but the Jenkins CI is failing... however it's hard for me to understand if that's related to my changes... can you have a look? 
Thanks!

**Comment by uilianries** [comment]
Hi @f18m !

The error is described at the line https://conan-ci.jfrog.info/blue/organizations/jenkins/ConanTestSuite/detail/PR-7887/1/pipeline#step-267-log-1417

Basically, `CONAN_VERSION_MYPKG2` is not listed on expected output:

Screenshot_2020-10-19 Diff Checker


You can test directly by running:

    nosetests conans/test/unittests/client/generators/make_test.py

More info about testing: https://github.com/conan-io/conan#running-the-tests

**Comment by memsharded** [comment]
This generator was removed, this is outdated, closing. Many thanks.

**Comment by f18m** [comment]
@memsharded are you saying that the GNU make generator is deprecated by Conan tool? 
That would be bad news to me... :(

**Comment by memsharded** [comment]
It has been replaced by ``AutotoolsDeps``, ``AutotoolsToolchain`` generators, like all other build-system integrations, they all have been superseded by modern 2.0-ready alternatives: 
- https://docs.conan.io/en/latest/reference/conanfile/tools.html
- https://docs.conan.io/en/latest/conan_v2.html

**Comment by f18m** [comment]
Hi @memsharded ,
but what about GNU-make based build systems? Can I ask Conan2.0 to generate a .mak file with GNU-make-style variables? 
In my company we're using GNU make without any additional layer (e.g. cmake, bazel, meson)... and we've been integrating with Conan 1.x just nicely with GNU make... is this use case being dropped in Conan2.0 ? 
thanks

**Comment by memsharded** [comment]
For GNU Make systems, the ``AutotoolsDeps`` (or maybe in some cases ``PkgConfigDeps``) and ``AutotoolsToolchain`` are the recommended way. They cover autotools integration, but using directly Makefiles can easily work just by following standard GNU conventions of the env-vars names (CC/CXX/CXXFLAGS/LDFLAGS, etc) 
This keeps being supported nicely in 2.0, support for it is not being dropped, just being replaced for a new integration, which is more modern and standard. It is based on generating environment variable files, not a custom .mak files which requires intrusive changes to your Makefiles, but the support is there.

**Pull request closed without merging**
