### PR TITLE
Windows line endings for default config and settings

### PR DESCRIPTION
**Pull request by opilar**
Resolving #629.

### CODE REVIEW

**Comment by opilar** [comment]
Checked on Windows 10:
image

**Comment by memsharded** [comment]
Great, thank you!

**Comment by lasote** [comment]
I was a little worried about migration of settings, we are comparing some fixed text with the current file contents, maybe now the end lines could break it?

**Comment by memsharded** [comment]
I'd say that no big problem, in many releases the settings are migrated, the worst it could happen could be an unnecessary migration of settings, right?

**Comment by lasote** [comment]
Yes. Not a big problem, but not a big problem edit the files without our "loved" notepad XD

**Pull request merged**
