### PR TITLE
Filter directories

### PR DESCRIPTION
**Pull request by SSE4**
filter out non-existing and empty directories
such directories can cause troubles for certain generators, e.g. CMake targets complains about them

#1607

### CODE REVIEW

**Comment by SSE4** [comment]
@memsharded please don't merge for a while, as I am going to learn how to run and debug conan unit tests, fix failing test cases and probably adding few to cover filtering feature.

**Comment by lasote** [comment]
I'm not completely sure about this. If CMake is complaining about empty directories maybe should be CMake the one who filters? 
Could this break things? WDYT @memsharded ?

**Comment by lasote** [comment]
Also, we are performing an `os.listdir()` for every single dir of each dependency. Could it affect the performance? We should measure it with a big graph.

**Comment by memsharded** [comment]
I think the approach is valid, I think there are other build systems that would complain if some path for includes or libs doesn't exist. Maybe the filter can be check for just existence of the folder (I don't care if it is empty, but that is not the case in 99% of cases). I will try to run some performance tests, to check the impact.

**Comment by SSE4** [comment]
@memsharded okay, I am holding off future changes until we have decision about performance, and do we want to filter non-existing folders or empty folders or both, or may be non of them

**Comment by memsharded** [comment]
The proposed approach multiplied 3X the cost of computing and propagating the graph info. (for 7 seconds for a 250 deps graph to almost 30 seconds)

I have proposed caching the values, and also fixed the broken tests in: https://github.com/conan-io/conan/pull/1719

That PR already includes your commits, many thanks! I think this PR can be closed now.

**Pull request closed without merging**
