### PR TITLE
Add configs to JSON generator

### PR DESCRIPTION
**Pull request by jgsogo**
Changelog: Fix: Include information about all the configurations in the JSON generator
Docs: https://github.com/conan-io/docs/pull/1129

JSON generator was ignoring the configs in the output, after including them in this PR some fields are duplicated or have null values (`version` and `description` in the config subnodes), have a look at the test for more detailed information.

Full output for the included test (before there was no `configs` node):

```json
{
    "deps_env_info": {
        "MY_ENV_VAR": "foo"
    },
    "deps_user_info": {
        "Hello": {
            "my_var": "my_value"
        }
    },
    "dependencies": [
        {
            "version": "0.1",
            "description": null,
            "rootpath": "/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpkp9l_dovconans/path with spaces/.conan/data/Hello/0.1/lasote/testing/package/46f53f156846659bf39ad6675fa0ee8156e859fe",
            "sysroot": "",
            "include_paths": [],
            "lib_paths": [],
            "bin_paths": [],
            "build_paths": [
                "/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpkp9l_dovconans/path with spaces/.conan/data/Hello/0.1/lasote/testing/package/46f53f156846659bf39ad6675fa0ee8156e859fe/"
            ],
            "res_paths": [],
            "libs": [],
            "defines": [],
            "cflags": [],
            "cppflags": [],
            "sharedlinkflags": [],
            "exelinkflags": [],
            "name": "Hello",
            "configs": {
                "debug": {
                    "version": null,
                    "description": null,
                    "rootpath": "/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpkp9l_dovconans/path with spaces/.conan/data/Hello/0.1/lasote/testing/package/46f53f156846659bf39ad6675fa0ee8156e859fe",
                    "sysroot": "",
                    "include_paths": [],
                    "lib_paths": [],
                    "bin_paths": [],
                    "build_paths": [
                        "/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpkp9l_dovconans/path with spaces/.conan/data/Hello/0.1/lasote/testing/package/46f53f156846659bf39ad6675fa0ee8156e859fe/"
                    ],
                    "res_paths": [],
                    "libs": [
                        "Hello_d"
                    ],
                    "defines": [
                        "LIB_DEBUG"
                    ],
                    "cflags": [],
                    "cppflags": [],
                    "sharedlinkflags": [],
                    "exelinkflags": []
                },
                "release": {
                    "version": null,
                    "description": null,
                    "rootpath": "/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpkp9l_dovconans/path with spaces/.conan/data/Hello/0.1/lasote/testing/package/46f53f156846659bf39ad6675fa0ee8156e859fe",
                    "sysroot": "",
                    "include_paths": [],
                    "lib_paths": [],
                    "bin_paths": [],
                    "build_paths": [
                        "/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpkp9l_dovconans/path with spaces/.conan/data/Hello/0.1/lasote/testing/package/46f53f156846659bf39ad6675fa0ee8156e859fe/"
                    ],
                    "res_paths": [],
                    "libs": [
                        "Hello"
                    ],
                    "defines": [
                        "LIB_RELEASE"
                    ],
                    "cflags": [],
                    "cppflags": [],
                    "sharedlinkflags": [],
                    "exelinkflags": []
                }
            }
        }
    ],
    "settings": {
        "arch": "x86_64",
        "arch_build": "x86_64",
        "build_type": "Release",
        "compiler": "apple-clang",
        "compiler.libcxx": "libc++",
        "compiler.version": "10.0",
        "os": "Macos",
        "os_build": "Macos"
    },
    "options": {
        "Hello": {}
    }
}
```

### CODE REVIEW

**Comment by lasote** [comment]
>  after including them in this PR some fields are duplicated or have null values

So what are you proposing? Should it be fixed as the test say? when?

**Comment by jgsogo** [comment]
It would require a refactor of the `CppInfo` and we didn't want to do it now as we talked about for #4656. I don't know what to do, that's the reason I'm pointing it out in the comment: to grab your opinion about it.

**Comment by jgsogo** [comment]
...a refactor of the `CppInfo` object or more work in the JSON generator to detect and avoid these duplicated fields (although I think that the former one should be preferred).

**Comment by lasote** [comment]
Convert this to a draft please. We will talk this for the next release.

**Comment by jgsogo** [comment]
I think it cannot be downgraded to _draft_ once it is _ready for review_ 😞

**Comment by jgsogo** [comment]
Done!

**Pull request merged**
