### PR TITLE
CMakeDeps checks build profile + CMakeDeps check real targets

### LINKED ISSUE #9112: [bug] Conan 1.37.2 CMakeDeps generator does not bootstrap package's own CMake config file
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS Catalina
  * Compiler+version: n/a
  * Conan version: 1.37.2
  * Python version: 3.9.5

### Problem

The new `CMakeDeps` generator behaviour generates generic CMake `*Config.cmake` etc files from the Conan recipes for the external libraries that are specified as dependencies.
What if a library provide its own `*Config.cmake` file(s)? It seems that the `CMakeDeps` generator does not defer to that.
I would expect the generator to generate the typical files for Conan, but then also still defer/include/execute the package's original `*Config.cmake` file(s).

Also, if there is any bootstrapping that needs to occur for said external library and this logic is embedded and shipped with the external library's package, how should that be accessed /executed using the `CMakeDeps` generator.
For past generators like `find_package`, it generates a `Find<packagename>.cmake` file, but this still had the functionality to include the build module if specified via `self.cpp_info.build_modules[]` in the recipe method `package_info()` for the library.
Adding `self.cpp_info.build_modules["CMakeDeps"].append(...)` does not seem to make any difference for the `CMakeDeps` generator.

#### Step 1
Clone this repo to get a Conan package (in a sub-folder of this repo) that only contains CMake files that you will install into your local cache.
https://github.com/SeanSnyders/TestExamples.git

#### Step 2
Then use the gist below that is a recipe that depends on the package above that you installed. This recipe uses the Conan helloworld example as source code, and patches it to suit this test.
https://gist.github.com/SeanSnyders/30f73a76736864977bd88c0212f55fd7

Try to build this package for this gist and it'll fail because it cannot find a CMake utility file that it wants to include that is part of the first package above.

It fails because to illustrate the problem, this dependent library sets a variable `CMAKE_PURECMAKEPACKAGE_PACKAGE_PATH` which is defined in the library's own CMake config file. Conan does not seem to include this, thus this variable is not defined, and thus the 2nd package could not be built.

#### Step 1
```
mkdir temp && cd temp
git clone https://github.com/SeanSnyders/TestExamples.git
cd TestExamples/PureCMakePackage
conan export . ssnyder/testing
```
image

#### Step 2
Download gist specified above into new folder, then
```
conan export . ssnyder/testing
```
image

Then build and install this package into the local cache
```
conan install ConanCMakeDepsGenerator/0.1.0@ssnyder/testing --build=ConanCMakeDepsGenerator -s build_type=Debug  --build missing
```
image

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Forced build from source
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Generators in TestRecipe.build_requirements(): ('CMakeDeps', 'cmake_paths', 'virtualenv')
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: self.build_requires=<class 'conans.client.graph.graph_manager._RecipeBuildRequires'>
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: self.build_requires=cmake/3.19.4 (host), gtest/1.10.0 (host), PureCMakePackage/0.1.0@ssnyder/testing (host)
Installing package: ConanCMakeDepsGenerator/0.1.0@ssnyder/testing
Requirements
    ConanCMakeDepsGenerator/0.1.0@ssnyder/testing from local cache - Cache
Packages
    ConanCMakeDepsGenerator/0.1.0@ssnyder/testing:0458ed5e3c5080307ca8a3bae7bab3c04f2768cc - Build
Build requirements
    PureCMakePackage/0.1.0@ssnyder/testing from local cache - Cache
    cmake/3.19.4 from 'conan-center' - Cache
    gtest/1.10.0 from 'conan-center' - Cache
    openssl/1.1.1i from 'conan-center' - Cache
Build requirements packages
    PureCMakePackage/0.1.0@ssnyder/testing:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build
    cmake/3.19.4:8780864092a6c58a5f5d385d2da47db0f418446d - Cache
    gtest/1.10.0:8ea16b5437d767794f13beec66099d7352875d19 - Cache
    openssl/1.1.1i:d98fae1010d1fb9e7f79a1e8a72bbf129d8660a2 - Cache

Installing (downloading, building) binaries...
PureCMakePackage/0.1.0@ssnyder/testing: Configuring sources in /Users/ssnyder/.conan/data/PureCMakePackage/0.1.0/ssnyder/testing/source
PureCMakePackage/0.1.0@ssnyder/testing: Copying sources to build folder
PureCMakePackage/0.1.0@ssnyder/testing: Building your package in /Users/ssnyder/.conan/data/PureCMakePackage/0.1.0/ssnyder/testing/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
PureCMakePackage/0.1.0@ssnyder/testing: Generator txt created conanbuildinfo.txt
PureCMakePackage/0.1.0@ssnyder/testing: Calling build()
PureCMakePackage/0.1.0@ssnyder/testing: Running build in ConanRecipe...
PureCMakePackage/0.1.0@ssnyder/testing: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' built
PureCMakePackage/0.1.0@ssnyder/testing: Build folder /Users/ssnyder/.conan/data/PureCMakePackage/0.1.0/ssnyder/testing/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
PureCMakePackage/0.1.0@ssnyder/testing: Generated conaninfo.txt
PureCMakePackage/0.1.0@ssnyder/testing: Generated conanbuildinfo.txt
PureCMakePackage/0.1.0@ssnyder/testing: Generating the package
PureCMakePackage/0.1.0@ssnyder/testing: Package folder /Users/ssnyder/.conan/data/PureCMakePackage/0.1.0/ssnyder/testing/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
PureCMakePackage/0.1.0@ssnyder/testing: Calling package()
PureCMakePackage/0.1.0@ssnyder/testing: Running package in ConanRecipe...
PureCMakePackage/0.1.0@ssnyder/testing package(): Packaged 2 '.cmake' files: PureCMakePackageConfig.cmake, Utils.cmake
PureCMakePackage/0.1.0@ssnyder/testing: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' created
PureCMakePackage/0.1.0@ssnyder/testing: Created package revision b6387e11d78d612393aa2871ebe6c586
PureCMakePackage/0.1.0@ssnyder/testing: Running package_info in ConanRecipe...
gtest/1.10.0: Already installed!
openssl/1.1.1i: Already installed!
cmake/3.19.4: Already installed!
cmake/3.19.4: Appending PATH environment variable: /Users/ssnyder/.conan/data/cmake/3.19.4/_/_/package/8780864092a6c58a5f5d385d2da47db0f418446d/bin
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Applying build-requirement: cmake/3.19.4
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Applying build-requirement: gtest/1.10.0
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Applying build-requirement: PureCMakePackage/0.1.0@ssnyder/testing
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Applying build-requirement: openssl/1.1.1i
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Configuring sources in /Users/ssnyder/.conan/data/ConanCMakeDepsGenerator/0.1.0/ssnyder/testing/source
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Getting source in TestRecipe.source()....
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Copying sources to build folder
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Building your package in /Users/ssnyder/.conan/data/ConanCMakeDepsGenerator/0.1.0/ssnyder/testing/build/0458ed5e3c5080307ca8a3bae7bab3c04f2768cc
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Generator virtualenv created activate.ps1
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Generator virtualenv created deactivate.ps1
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Generator virtualenv created environment.ps1.env
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Generator virtualenv created activate.sh
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Generator virtualenv created deactivate.sh
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Generator virtualenv created environment.sh.env
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Generator cmake_paths created conan_paths.cmake
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Generator 'CMakeDeps' calling 'generate()'
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Calling generate()
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Running generate in TestRecipe...
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Calling build()
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: cmake.defs: OrderedDict([('CMAKE_BUILD_TYPE', 'Debug'), ('CMAKE_OSX_ARCHITECTURES', 'x86_64'), ('CMAKE_OSX_SYSROOT', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk'), ('CONAN_IN_LOCAL_CACHE', 'ON'), ('CONAN_COMPILER', 'apple-clang'), ('CONAN_COMPILER_VERSION', '12.0'), ('CONAN_CXX_FLAGS', '-m64'), ('CONAN_SHARED_LINKER_FLAGS', '-m64'), ('CONAN_C_FLAGS', '-m64'), ('CONAN_LIBCXX', 'libc++'), ('CMAKE_INSTALL_PREFIX', '/Users/ssnyder/.conan/data/ConanCMakeDepsGenerator/0.1.0/ssnyder/testing/package/0458ed5e3c5080307ca8a3bae7bab3c04f2768cc'), ('CMAKE_INSTALL_BINDIR', 'bin'), ('CMAKE_INSTALL_SBINDIR', 'bin'), ('CMAKE_INSTALL_LIBEXECDIR', 'bin'), ('CMAKE_INSTALL_LIBDIR', 'lib'), ('CMAKE_INSTALL_INCLUDEDIR', 'include'), ('CMAKE_INSTALL_OLDINCLUDEDIR', 'include'), ('CMAKE_INSTALL_DATAROOTDIR', 'share'), ('CMAKE_PREFIX_PATH', '/Users/ssnyder/.conan/data/ConanCMakeDepsGenerator/0.1.0/ssnyder/testing/build/0458ed5e3c5080307ca8a3bae7bab3c04f2768cc'), ('CMAKE_MODULE_PATH', '/Users/ssnyder/.conan/data/ConanCMakeDepsGenerator/0.1.0/ssnyder/testing/build/0458ed5e3c5080307ca8a3bae7bab3c04f2768cc'), ('CMAKE_EXPORT_NO_PACKAGE_REGISTRY', 'ON'), ('CONAN_EXPORTED', '1'), ('CMAKE_VERBOSE_MAKEFILE', 'ON')])
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Component target declared 'GTest::gtest'
-- Conan: Component target declared 'GTest::gtest_main'
-- Conan: Component target declared 'GTest::gmock'
-- Conan: Component target declared 'GTest::gmock_main'
-- Conan: Target declared 'GTest::GTest'
-- Conan: Target declared 'PureCMakePackage::PureCMakePackage'
-- PureCMakePackage PureCMakePackage_PACKAGE_FOLDER_RELEASE=
-- PureCMakePackage PureCMakePackage_PACKAGE_FOLDER_DEBUG=/Users/ssnyder/.conan/data/PureCMakePackage/0.1.0/ssnyder/testing/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
-- PureCMakePackage CMAKE_PURECMAKEPACKAGE_PACKAGE_PATH=
CMake Error at CMakeLists.txt:9 (include):
  include could not find load file:

    /utils/Utils.cmake


-- Configuring incomplete, errors occurred!
See also "/Users/ssnyder/.conan/data/ConanCMakeDepsGenerator/0.1.0/ssnyder/testing/build/0458ed5e3c5080307ca8a3bae7bab3c04f2768cc/CMakeFiles/CMakeOutput.log".
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: 
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: ERROR: Package '0458ed5e3c5080307ca8a3bae7bab3c04f2768cc' build failed
ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: WARN: Build folder /Users/ssnyder/.conan/data/ConanCMakeDepsGenerator/0.1.0/ssnyder/testing/build/0458ed5e3c5080307ca8a3bae7bab3c04f2768cc
ERROR: ConanCMakeDepsGenerator/0.1.0@ssnyder/testing: Error in build() method, line 52
	cmake = self._configure_cmake()
while calling '_configure_cmake', line 48
	self._cmake.configure(source_folder="./hello")
	ConanException: Error 1 while executing cd '/Users/ssnyder/.conan/data/ConanCMakeDepsGenerator/0.1.0/ssnyder/testing/build/0458ed5e3c5080307ca8a3bae7bab3c04f2768cc' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="apple-clang" -DCONAN_COMPILER_VERSION="12.0" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libc++" -DCMAKE_INSTALL_PREFIX="/Users/ssnyder/.conan/data/ConanCMakeDepsGenerator/0.1.0/ssnyder/testing/package/0458ed5e3c5080307ca8a3bae7bab3c04f2768cc" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_PREFIX_PATH="/Users/ssnyder/.conan/data/ConanCMakeDepsGenerator/0.1.0/ssnyder/testing/build/0458ed5e3c5080307ca8a3bae7bab3c04f2768cc" -DCMAKE_MODULE_PATH="/Users/ssnyder/.conan/data/ConanCMakeDepsGenerator/0.1.0/ssnyder/testing/build/0458ed5e3c5080307ca8a3bae7bab3c04f2768cc" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DCMAKE_VERBOSE_MAKEFILE="ON" -Wno-dev '/Users/ssnyder/.conan/data/ConanCMakeDepsGenerator/0.1.0/ssnyder/testing/build/0458ed5e3c5080307ca8a3bae7bab3c04f2768cc/./hello'
ssnyder-nz-la1:ConanCMakeDepsGenerator ssnyder$ 

```

### PR DESCRIPTION
**Pull request by lasote**
Changelog: Fix: Added warning in the new toolchains (the used in the generate() method) if no build profile is being used.
Changelog: Fix: Implemented check that will raise an error in the `CMakeDeps` generator when using the `build_context_activated`, `build_context_suffix` or `build_context_build_modules` attributes if no build profile is being used.
Changelog: Fix: The`CMakeDeps` generator will check if the targets specified in the `find_package(foo components x y z)` exist instead of checking against an internal variable. Also, this check will be done at the end of the `xxx-config.cmake` so any included `build_module` can declare the needed targets.
Docs: https://github.com/conan-io/docs/pull/2173
For documentation: (Modify the documentation with a note indicating that the usage of build_context_activated, build_context_suffix and build_context_build_modules will fail if no build profile is specified. Also a note in every new generator that the usage of the build profile is very recommended or unexpected errors/behavior may ocurr) 

Closes https://github.com/conan-io/conan/issues/9112

### CODE REVIEW

**Comment by danimtb** [comment]
Just missing a test here that shows the expected behavior for components coming from a build module. I think it is important to have this covered by a test

**Comment by lasote** [comment]
@danimtb Added test, please review.

**Review by memsharded — APPROVED** [review]

**Comment by cboos** [comment]
Hello, I'm commenting on:
> Changelog: Fix: TheCMakeDeps generator will check if the targets specified in the find_package(foo components x y z) exist instead of checking against an internal variable. Also, this check will be done at the end of the xxx-config.cmake so any included build_module can declare the needed targets.

This is indeed a step further to fix the "regression" from 1.36 for my Qt5 use case (cf. [#9112 comment](https://github.com/conan-io/conan/issues/9112#issuecomment-869909144)), but the explicit check for defined components won't work in this situation.

e.g. if we have in our CMakeLists.cmake something like:

```cmake
find_package(Qt5 COMPONENTS Core LinguistTools REQUIRED)
``` 

then the test in Conan's Qt5Config.cmake passes for `Core` but not for `LinguistTools`:

```
...
  Paths specified by the find_package PATHS option.

    C:/Users/cboos/.conan/data/Qt5/5.15.2.0/bct/testing/package/811010fc454bb85ee1e902a530feb1ec906ff80f/lib/cmake



  find_package considered the following locations for the Config module:

    C:/Users/cboos/.conan/data/Qt5/5.15.2.0/bct/testing/package/811010fc454bb85ee1e902a530feb1ec906ff80f/lib/cmake/Qt5LinguistToolsConfig.cmake
    C:/Users/cboos/.conan/data/Qt5/5.15.2.0/bct/testing/package/811010fc454bb85ee1e902a530feb1ec906ff80f/lib/cmake/qt5linguisttools-config.cmake
    C:/Users/cboos/.conan/data/Qt5/5.15.2.0/bct/testing/package/811010fc454bb85ee1e902a530feb1ec906ff80f/lib/cmake/Qt5LinguistTools/Qt5LinguistToolsConfig.cmake

  The file was found at

    C:/Users/cboos/.conan/data/Qt5/5.15.2.0/bct/testing/package/811010fc454bb85ee1e902a530feb1ec906ff80f/lib/cmake/Qt5LinguistTools/Qt5LinguistToolsConfig.cmake

Call Stack (most recent call first):
  build/Qt5Config.cmake:21 (include)
  applications/bct_ico_sync/CMakeLists.txt:7 (find_package)


-- Conan: Component 'Core' found in package 'Qt5'
CMake Error at build/cmakedeps_macros.cmake:4 (message):
  Conan: Component 'LinguistTools' NOT found in package 'Qt5'
Call Stack (most recent call first):
  build/Qt5Config.cmake:31 (conan_message)
  applications/bct_ico_sync/CMakeLists.txt:7 (find_package)


CMake Debug Log at applications/bct_ico_sync/CMakeLists.txt:7 (find_package):
    D:/Workspace/src/git/BCT/main/build/Qt5Config.cmake
```

This is because the `Qt5LinguistToolsConfig.cmake` (as shipped in Qt 5.15.2) provides targets like `Qt5::lrelease`, `Qt5::lupdate`, but no `Qt5::LinguistTools` target. I'm not sure how legit that is from a CMake point of view, but it certainly works well in practice. However, Conan assumes that for each `${Qt5_FIND_COMPONENTS}` there is a `Qt5::${_FIND_COMPONENT}` target defined, and that's not the case with this "virtual" component.

**Comment by cboos** [comment]
> However, Conan assumes that for each `${Qt5_FIND_COMPONENTS}` there is a `Qt5::${_FIND_COMPONENT}` target defined, and that's not the case with this "virtual" component.

... following-up with a suggestion: would it be possible to make that explicit check optional? (the whole `# Check that the specified components in the find_package(Foo COMPONENTS x y z) are there` part).

An invalid component name in a `find_package` will lead to an error anyway:

```cmake
find_package(Qt5 COMPONENTS Core LinguistToolZ REQUIRED)
```
```
-- Conan: Target declared 'Qt5::Qt5'
-- Conan: Including build module from 'C:/Users/cboos/.conan/data/Qt5/5.15.2.0/bct/testing/package/811010fc454bb85ee1e902a530feb1ec906ff80f/lib/cmake/Qt5/Qt5Config.cmake'
-- Conan: Target declared 'Qt5::Qt5'
-- Conan: Including build module from 'C:/Users/cboos/.conan/data/Qt5/5.15.2.0/bct/testing/package/811010fc454bb85ee1e902a530feb1ec906ff80f/lib/cmake/Qt5/Qt5Config.cmake'
CMake Error at C:/Users/cboos/.conan/data/Qt5/5.15.2.0/bct/testing/package/811010fc454bb85ee1e902a530feb1ec906ff80f/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5LinguistToolZ"
  with any of the following names:

    Qt5LinguistToolZConfig.cmake
    qt5linguisttoolz-config.cmake
```

Something like:  `self.cpp_info.set_property('cmake_check_components', false)` (~or always leave it out and rely on cmake to produce an error when needed~ - well, in the regular situation, when the only package .cmake files are the ones generated by Conan, I understand this must be there).

**Comment by lasote** [comment]
Hi @cboos. ~~Sorry, I don't get it. If you use `find_package(Qt5 COMPONENTS Core LinguistToolZ REQUIRED)` it will make CMake fail because it is what `REQUIRED` is intended, right? We cannot avoid that from Conan. 
It would be different if you use don't specify the REQUIRED: `find_package(Qt5 COMPONENTS Core LinguistToolZ)` in that case will be Conan the one failing, right?.~~ We could consider avoiding the check but the correct way to do it would be in the `generate()` method of the consumer, it could be something like:

```
def generate(self):
    deps = CMakeDeps(self)
    deps.skip_components_check = True
    deps.generate()
```
(and remove the `generators = "CMakeDeps"`)

**Comment by lasote** [comment]
Edit: I have checked that `REQUIRED` is not affecting when a component is missing, that's why we introduce that check.

**Comment by cboos** [comment]
> the correct way to do it would be in the generate() method of the consumer

I did hope it would be possible to do that at the level of my Qt5 Conan package itself, so that I can keep using simple consumers based on a conanfile.txt and `[generators] CMakeDeps`. Well, I suppose it might be possible to support generator options there at some point (`CMakeDeps [skip_components_check=True]`).

But still, that would then apply to *all* the dependencies, not just to that Qt5 one, and it's possibly the only one which wouldn't need the components check. So I see that more as a "property" of that package itself rather than a constraint to spread on its consumers, possibly affecting other packages.

**Comment by lasote** [comment]
After checking that CMake is not failing by default when a component specified in the `find_package` doesn't exist we changed our default behavior and we are not checking anymore the components existence unless it is explicitly activated with `deps.check_components_exist=True`

**Comment by cboos** [comment]
I just checked 468b68e and with that, I can use again my Qt5 package again! So thanks a lot! 👍 

The point I raised above that it could be more appropriate to decide to check for components or not (so `check_components_exist` now) at the level of a given package rather than for all dependencies of a consumer might still be a valid concern. But as the default behavior fits my use case, I won't insist on that ;-)

**Review by danimtb — APPROVED** [review]

**Review by memsharded — APPROVED** [review]

**Pull request merged**
