### PR TITLE
Add support for letting the generators save multiple files.

### PR DESCRIPTION
**Pull request by tru**
For what I was doing with the PkgConfig generator I had to
be able to generate one file per dependency. The current
generator system was not able to handle this. Fortunately
it was a easy change without having to break any current
generators.

### CODE REVIEW

**Comment by memsharded** [comment]
Let me suggest an alternative approach to this implementation. Doing a PR to your fork.

**Comment by memsharded** [comment]
Hi @tru! I did a PR to your fork: https://github.com/tru/conan/pull/3 Did you have a chance to look at it?

**Comment by tru** [comment]
@memsharded all your changes looked fine! thanks for writing the test as well. Tested it with my PC generator and it worked fine. Feel free to merge this!

**Comment by memsharded** [comment]
Ups, seems I broke CI. Will check it asap, and merge it to start release 0.10. Thanks!

**Comment by memsharded** [comment]
Fixed, and merged. Thanks again for your contributions!

**Pull request merged**
