### PR TITLE
Feature: add deprecated attribute

### LINKED ISSUE #7251: [feature] Add 'deprecated' attribute to ConanFile
Add a `deprecated` attribute to ConanFile class:
 * _falsy_ value will do nothing
 * _truthy_ value will print a standardized warning to the user (probably during the configuration step): the value can contain the name/reference of another recipe that supersedes this one.

```python
class Recipe(ConanFile):
    name = "cpp-taskflow"

    deprecated = "taskflow"
```

```bash
$ conan install cpp-taskflow/1.0
...
WARN.- Recipe 'cpp-taskflow/1.0' is deprecated in favor of 'taskflow/1.0'. Please, consider changing your requirements.
...

### PR DESCRIPTION
**Pull request by SSE4**
closes: #7251 

Changelog: Feature: add deprecated attribute
Docs: https://github.com/conan-io/docs/pull/1775

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [x] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by SSE4** [comment]
NOTE: this doesn't print:
```
WARN.- Recipe 'cpp-taskflow/1.0' is deprecated in favor of 'taskflow/1.0'. Please, consider changing your requirements.
```
instead, it will print just:
```
WARN.- Recipe 'cpp-taskflow/1.0' is deprecated in favor of 'taskflow'. Please, consider changing your requirements.
```
notice taskflow has no version specified. 
reason - `taskflow/1.0` might not exist - the new version might be `taskflow/2.0` for instance.

**Review by memsharded — APPROVED** [review]

**Review by danimtb — APPROVED** [review]
I was wondering if this `deprecated` attribute is prone to be ser conditionally in the `configure()` method. Having a look at the implementation, I think it is already working but I am not sure if we have a use case for that 🤔

**Comment by memsharded** [comment]
> I was wondering if this deprecated attribute is prone to be ser conditionally in the configure() method. Having a look at the implementation, I think it is already working but I am not sure if we have a use case for that 🤔

Well, it is possible that some recipe support for one OS is deprecated, probably not a very common case, so I would be fine even if this didn't work at the moment.

**Comment by SSE4** [comment]
I don't see any advantage in such complicated use-case as a conditionally deprecated recipe. I'd say let's go with simple implementation, until someone will actually request that feature.

**Comment by uilianries** [comment]
One advantage using the current condition, is that we can give a hint to the new reference. This new feature doesn't offer the same case.

Maybe, deprecated could accept a package reference or a boolean:

```python
class Foo(ConanFile):
    ...
    deprecated = True
    # OR
    deprecated = "foobar/0.1.0" # new reference
```

**Comment by SSE4** [comment]
@uilianries both are allowed, boolean and reference

**Comment by uilianries** [comment]
@memsharded Sorry, now I see: https://github.com/conan-io/conan/pull/7399/files#diff-3eb9b6f2733f2b3ba7899d8edeebf60fR42

**Review by uilianries — APPROVED** [review]

**Pull request merged**
