### PR TITLE
- define CMAKE_LIBRARY_OUTPUT_DIRECTORY as well

### PR DESCRIPTION
**Pull request by SSE4**
follow up #1982

### CODE REVIEW

**Comment by memsharded** [comment]
I know this is how it should be. However I am a bit afraid that this little change might affect existing packages badly. The same way you had to change the test so the libs are located in a different folder, that can happen to many packages, not only those in conan-center (and conan-transit), but also many user private packages. @lasote?

**Comment by ovidiub13** [comment]
Personally, I believe that those directories should be set by the user if so desired, and should not exist there; But as long as we're setting them, why not set them all?

**Comment by piponazo** [comment]
It looks good to me as far as these changes are inside the function `conan_output_dirs_setup`. If somebody wants to customize those directories they always can do it afterwards or avoiding the call to that function. 

In most of the CMake projects that I wrote I end up writing the same values than the one used here. :+1:

**Comment by memsharded** [comment]
Probably it makes sense to add also output for other configs than Release/Debug, as was added by: https://github.com/conan-io/conan/pull/2041.

From the received feedback, my suggestion would be to merge this, and probably do this sooner than later if we are going to break. Wdyt @lasote?

**Comment by SSE4** [comment]
@memsharded yep, I am adding them today

**Comment by SSE4** [comment]
@memsharded done, pls review

**Pull request merged**
