### PR TITLE
Allow to change the name of generated CMake targets in conanbuildinfo.cmake

### PR DESCRIPTION
**Pull request by MarcoKoch**
This extends the output of the CMake generators so users can influence the generated target names in `TARGETS` mode from within their CMake files.

The syntax of both `conan_basic_setup()` and `conan_define_targets()` is extended:

```cmake
# global configuration mode (unchanged)
conan_basic_setup()

# targets mode
conan_basic_setup(TARGETS
    [PREFIX <prefix> | NO_PREFIX]
    [NAME <package> <target> [OPTIONAL] ]...)

conan_define_targets(
    [PREFIX <prefix> | NO_PREFIX]
    [NAME <package> <target> [OPTIONAL] ]...)
```

`PREFIX` can be used to provide a custom `<prefix>` that is prepended to the package name to form the corresponding target name. `NO_PREFIX` can be specified to skip the prefix and use the package names as target names. If none of both is specified, `CONAN_PKG::` is used (i.e. the current behavior is retained as default).

```cmake
include("${CMAKE_BINARY_DIR}/conanbuildinfo.cmake")
conan_basic_setup(TARGETS PREFIX conan::)
# ...
target_link_libraries(myexe conan::OpenSSL)
```

Currently, specifying `PREFIX ""` has the same effect as `NO_PREFIX`. Future additions to these macros may use `cmake_parse_arguments()`, though. Then `PREFIX ""` will not work any longer.

`NAME` can be used to set the target name for package `<package>` to `<target>`. In this case, no prefix is used. Multiple instances of `NAME` can be used to provide target names for multiple packages.

```cmake
include("${CMAKE_BINARY_DIR}/conanbuildinfo.cmake")
conan_basic_setup(TARGETS
    NAME OpenSSL ssl
    NAME zlib z
)
# ...
target_link_libraries(myexe ssl z)
```

By default, a warning is issued if `<package>` is not a dependency of the project. `OPTIONAL` can be specified to omit that warning. This is useful for dependencies that are enabled by conan options or that are required only on specific platforms or configurations.

```cmake
include("${CMAKE_BINARY_DIR}/conanbuildinfo.cmake")
conan_basic_setup(TARGETS
    NAME OptionalLibA optA OPTIONAL
    NAME OptionalLibB optB OPTIONAL
    NAME NonOptionalLib nonopt
)
```

For each dependency, a CMake variable `CONAN_<package>_TARGET` is created that contains the name of the corresponding target. The new variable `CONAN_DEPENDENCIES` provides a list of all packages the project depends on.

I had to alter the tests a bit to accommodate the fact that the target names are no longer created by conan itself, but during CMake configuration. I also changed some log messages a bit to make them more consistent.

If this gets merged, I will also provide a corresponding pull request to the docs repo.

### CODE REVIEW

**Comment by memsharded** [comment]
Some tests are still breaking, I have to have a look at them.

My main question regarding this PR is getting to know the use case to change the names (or scopes). We are adding a bunch of new lines of code, with more complexity, that will have to be later maintained. So I wonder about the use case of this target renaming, why do you need such functionality? Do you think that will be relevant for more conan users?

Thanks very much for your contribution!

**Comment by MarcoKoch** [comment]
Judging from a brief glance through the CI logs, the breaking tests have to do with some changed log messages. I will have a look at that tomorrow. Unfortunately I could only test on Linux beforehand and the breaking tests seem to be on both OS X and Windows.

Regarding the use case: I want to retain the possibility to build my projects without Conan, using system-installed dependencies only (mainly to facilitate the work of system package maintainers). For that I use the targets from `conanbuildinfo.cmake` if it is present and otherwise use CMake's `find_package()` command to find the dependencies.
With exported targets becoming common practice in `FindXXX.cmake` modules, the problem now is that both mechanisms provide different target names. With many dependencies I have to add boilerplate code of the form:

```cmake
if (USING_CONAN)
    set(LIBUNWIND_TARGET CONAN_PKG::libunwind)
else ()
    find_package(libunwind 1.2.1 REQUIRED)
endif ()
# ...
target_link_libraries(mylib ${LIBUNWIND_TARGET})
```

Having to use variables in the link command also feels to kind of work against the idea of imported targets in CMake. With a `conan_basic_setup(TARGETS NO_PREFIX)`, the Conan-provided targets have the same name as those defined by `find_package()`. So no branching is required. The `NAME` option is for the more rare case when the packages are named differently in CMake than in Conan.

I seem to remember that users in the reddit article mentioned in #1522 have brought up the issue of the tight coupling between Conan and CMake by using `conan_basic_setup()`, too. The possibility to use interchangeable 'sources' of imported targets should loosen that coupling a bit.

**Comment by memsharded** [comment]
Good, makes sense, thanks very much for clarifying.

**Comment by memsharded** [comment]
I have reviewed this PR a few times. I have tried other approaches, like creating ALIAS targets, or renaming. Not possible, because IMPORTED INTERFACE target doesn't allow that in cmake.

My concern with this PR is that it is adding many lines of code to the generated conanbuildinfo.cmake, that IMHO are a bit overkill, as doing it consumer side is obvious:

```cmake
if (USING_CONAN)
    set(LIBUNWIND_TARGET CONAN_PKG::libunwind)
else ()
    # find_package(libunwind 1.2.1 REQUIRED)
    set(LIBUNWIND_TARGET libunwind)
endif ()
```
This structure might be also be necessary in any case, if the ``find_package()`` needs to be done. So the number of lines required to address this in the consumer side, is exactly the same that with the proposed solution, that will also add some lines, one per target too:

```cmake
conan_basic_setup(TARGETS
    NAME OpenSSL ssl
    NAME zlib z
)
```

So, the number of lines to be added in the consumer CMakeLists.txt is exactly the same in both scenarios, while we would be adding approx 100 lines more to the conanbuildinfo.cmake (lines that need to be maintained, documented, etc). Besides that, the first solution is easy and immediate to conan users, while the solution proposed in the PR adds a new level, so users need to go to the docs, learn about the syntax and then use it.

What do you think, @lasote, @MarcoKoch ?

**Comment by MarcoKoch** [comment]
Thanks for your time looking into this again!

The idea of this PR was originally based on the fact that Conan provides a means to pass compiler flags, definitions etc. into the CMake script, which `find_package()` in most cases doesn't (at least most `FindXXX.cmake` scripts don't and very few projects seem to provide `XXXConfig.cmake` scripts). So I preferred to use the available information from Conan directly instead of using `find_package()`.

Concerning the `NAME` lines: The idea was that (at least in my case) the Conan packages are usually named the same as the targets created by the corresponding `FindXXX.cmake` modules. So in most cases, the `NAME` lines would not be required if `NO_PREFIX` is given. The `NAME` parameter was meant as a work-around for the rarer cases where this is not the case.
On the other hand, more recent `FindXXX.cmake` scripts seemingly tend to put their targets into some sort of namespace like `namespace::lib`. Here the proposed system obviously breaks down and we would indeed have nothing gained.

In can perfectly understand your concerns about the amount of added code. In my current project, I'm using the approach to always use `find_package()` and just let Conan set up the search paths. As said, this works well as long as the Conan packages do not come with any funky compiler settings.
Maybe a possible 'compromise' would be to just add the proposed `CONAN_DEPENDENCIES` variable. Then consumers could do basically the same thing in their own code as this PR does, using the already available variables, if so required. At the same time, there would not be much additional code in `conanbuildinfo.cmake`.

**Comment by memsharded** [comment]
> Concerning the NAME lines: ...The NAME parameter was meant as a work-around for the rarer cases where this is not the case.

I would say not that rare, maybe you were lucky :)

> On the other hand, more recent FindXXX.cmake scripts seemingly tend to put their targets into some sort of namespace like namespace::lib. Here the proposed system obviously breaks down and we would indeed have nothing gained.

Yes, that is exactly the kind of things that I am concerned about, and the reason I prefer to keep things on the conan side (regarding the build system quirks) as simple as possible.

> Maybe a possible 'compromise' would be to just add the proposed CONAN_DEPENDENCIES variable. 

Regarding this, it is something that I missed during the review. There is already a ``CONAN_DEPENDENCIES`` variable being defined in ``conanbuildinfo.cmake`` containing the dependencies bare names (not the targets, but gettings the target names is straightforward).

**Comment by MarcoKoch** [comment]
Oh, now that you say it, I just see that that `CONAN_DEPENDENCIES` already existed. For some reason, I had overlooked it when I wrote the PR and added (a second definition of) it myself.

Then, from my point of view, this PR can be closed.

**Comment by memsharded** [comment]
Ok, thanks very much for your understanding. It is really appreciated, given the effort you made into this PR, it is very hard for maintainers sometimes...
Cheers!

**Comment by memsharded** [comment]
I have pushed contributors.txt with your name to develop :)

**Comment by MarcoKoch** [comment]
Without me having actually contributed something significant? 😆
But thank you, of course.
Do not worry about the effort I put in. With the amount of work Conan already saved me, I'm glad to spend some spare time trying to help out. Though I perfectly understand your pain...

**Comment by memsharded** [comment]
Github labels you as a contributor: https://github.com/conan-io/conan/commits?author=MarcoKoch

And every PR is significant! There is no insignificant contribution :) :) :) Thanks again!

**Pull request closed without merging**
