### PR TITLE
Feature/vsgen respaths

### PR DESCRIPTION
**Pull request by cawilson**
Added the mapping of res_paths into the Visual Studio generator for additional include paths to resource files not included in the include_paths, if such a requirment is required by the package recipe author. In addition, this maps a option implemented in the CMake generator to be inline with the Visual Studio generator as well.

### CODE REVIEW

**Comment by cawilson** [comment]
Hmm, seems like the previous commit, [320cbae](https://github.com/conan-io/conan/commit/320cbaec8b80d5ce487c256189a7b0857b51dcbe), to the develop branch has broken the build and this has caused this change to fail as well.

**Comment by memsharded** [comment]
Indeed, thanks for telling. It is weird, all CI checks were green. I am checking what happened and trying to revert asap to a green build.

**Comment by memsharded** [comment]
You were right, it was a mistake in a conflict resolution. I have pushed a fix, and develop now seems mostly green (still to finish). So if you could please rebase your PR and launch it again. 

Could you please elaborate a bit more why it is necessary to add ``ResourceCompile`` item to the project? Does it make sense to do it for any file type that the package creators might consider as resources? Originally, the idea was to put there files like images, sounds, config-files (xml, jsons), data files, etc.

Thanks!

**Comment by cawilson** [comment]
Hmm, maybe my interpretation of the what the paths were used for was wrong. So for CMake, are these paths just a reference to folder(s) that contain files that may require referencing in the parent project for various reasons? If so, I will cancel this PR :)

**Comment by memsharded** [comment]
The truth is that the resources dirs is not a very used feature.
It is intended to store any kind of resource besides headers, libs, and executables, so you add other files to packages, like a bunch of images, and you don't necessarily want to put them in those folder or in the root folder.

Having a variable that point to the resources folder makes easier for consumers to use them directly if they want, from their build system or from their own automation scripts. Right now, they are not managed by default by any build system. What was the use case you were thinking about?

**Comment by cawilson** [comment]
The use case was were you had a separate folder defined for the location of resources to be compiled (*.rc, images, icons, etc) and are required for the ResourceCompile task in MSBuild as we do set this in our current setup (we also set paths for the `<MIDL>`, `<Lib>` and `<CICompile><AdditionalUsingDirectories>` 

```xml
<ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <AdditionalUsingDirectories>%(AdditionalUsingDirectories)</AdditionalUsingDirectories>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
    </Link>
    <Lib>
      <AdditionalLibraryDirectories>%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
    </Lib>
    <ResourceCompile>
      <AdditionalIncludeDirectories>%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ResourceCompile>
    <Midl>
      <AdditionalIncludeDirectories>%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </Midl>
  </ItemDefinitionGroup>
```

Although as I work through our current setup and convert the projects to Conan packages (from direct project references) I'm finding that some of the paths that we define are largely redundant, as they all point to the same location.

We do, however, use conditions on things like the `<Link>` paths, so we can switch between different platforms and configurations in the IDE and I was thinking of helping to add support to Conan for multi-configuration, if I find the time.

I will close this PR for now and re-visit if I run into problems. For now, I've figured out that this change is notrequired.

**Comment by memsharded** [comment]
Thanks for the feedback!

I think you might be interested in issue: https://github.com/conan-io/conan/issues/1338, and specially the work developed by @birsoyo in https://github.com/birsoyo/conan-visualstudio.

We are open to improving the current visual_studio generator, or to add new generators to help integrating with visual studio. There are different lines of work:
- Multi-configuration: Something similar as the ``cmake-multi`` generator does: generate 3 files, one common, one for debug and one for release, so you can install both debug and release packages and use them seemsly from CMake. I think that for VS, it is just running 2 ``conan install`` to generate both debug and release ``conanbuildinfo.props`` files, but maybe something could be improved.
- Handling of resources: so far there is no explicit management of VS resources, but something could be implemented. Besides the ``resource_dirs``, we also have the ``build_dirs``, where packages can put build-related files. Maybe we could just use some convention, and if a folder "visual_studio" is found under "res_dir", then it can be assumed to be processed by the generator as VS resources to be compiled.

**Pull request closed without merging**
