### PR TITLE
fix exports relative paths

### LINKED ISSUE #2675: exports_sources loses part of relative path when ../ is used
When `../` is used in the path for a path in the `export_sources` attribute of a conanfile, the relative directory structure in the generated package under the `exports_sources` directory behaves "unexpectedly".  It's actually unclear what the "expected" behavior would be when the `../` is used, as it's not intuitive or obvious when you consider that we're passing a pattern and not `source` or `destination` parameters. 

_Note that this is a corner case, as the vast majority of uses of `exports_sources` involve the `conanfile.py` existing in the root of the sources, not some external subdirectory of a parent directory as in this example   It's possible that the use of `../` in `exports_sources` should simply be unsupported if a predictable/sensible behavior cannot be agreed upon ._

Expected/desired directory structure in `exports_sources` directory: 
`hello/src/file.c`

Actual directory structure:
`file.c`

```
from conans import ConanFile, CMake
class HelloConan(ConanFile):
    name = "hello"
    version = "0.1"
    exports_sources = "../../hello/src/file.c",

```

If I were to define the behavior that makes the most sense for my use case, it would be to retain the directory structure with all `../`'s stripped from it, but I'm not even sure that makes sense for all cases. 

This is not a blocking issue for me, as I can define where i want the files to go with the `package()` step in my case. 

[exports_sources_ssue.zip](https://github.com/conan-io/conan/files/1844723/exports_sources_ssue.zip)

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

### PR DESCRIPTION
**Pull request by memsharded**
- [x] Refer to the issue that supports this Pull Request.
Close #2675

Not sure if this could be considered breaking or fixing a bug.

### CODE REVIEW

**Comment by lasote** [comment]
Not sure either but it looks breaking, let's assign it to 1.3 to look at it carefully.

**Comment by lasote** [comment]
So, you cannot export a single file (without exporting the directories) if the folder is "..", right?
I agree it was weird to not copy the directories, but could the previous use case at least be kept writing something different?

**Comment by memsharded** [comment]
All possible solutions are a bit weird on the syntax.
Better to wait until we consider the ``exports()`` method as the way to do more advanced things at export time.

**Comment by memsharded** [comment]
This would be breaking, so delaying it until 2.0.

If someone requests this as an important and urgent feature, we might try to re-evaluate and see if there are other solutions, like the mentioned ``export()`` method, so far it seems there is not enough evidence to move it forward.

**Comment by memsharded** [comment]
Conan has learned the export() and export_sources() methods in Conan 1.26: https://docs.conan.io/en/latest/reference/conanfile/methods.html#export

This is a better solution, explicit, and not breaking, so I think we can close this PR now.

**Pull request closed without merging**
