### PR TITLE
Rename retry

### PR DESCRIPTION
**Pull request by yangcha**
Changelog: (Feature): os.rename() function frequently raises "Access is denied" exception on windows. This PR provides a function to rename file or folder with retrying to avoid the exception on windows. 
Docs: https://github.com/conan-io/docs/pull/1390

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [x] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by memsharded** [comment]
Quick feedback: one of the biggest source of "access denied" in Windows is the Windows Indexer service, which should be disabled for the conan cache(s) folder for avoiding these errors. Have you tried that?

**Comment by memsharded** [comment]
The thing is that we have been trying to avoid to add this kind of behavior, mainly for the built-in "rmtree" and remove functionality, feels a bit hacky.

**Comment by yangcha** [comment]
> Quick feedback: one of the biggest source of "access denied" in Windows is the Windows Indexer service, which should be disabled for the conan cache(s) folder for avoiding these errors. Have you tried that?

It runs on a build server which is out of my control.

**Comment by memsharded** [comment]
> It runs on a build server which is out of my control.

I see, if possible you should try contacting the admin of such a server to check it, if it is become of the Windows Indexer, it is likely to see other errors, random builds failing even at Conan internals... Also slower builds.

**Comment by SSE4** [comment]
there are multiple possible reasons of such access denied errors:
- Windows Indexer Service
- Anti-Virus Software, like Windows Defender and others
- TortoiseSVN/TortoiseGit cachers
same situation for delete

**Comment by danimtb** [comment]
Latest release includes a `conan.tools.rename()` https://github.com/conan-io/conan/pull/8915 that uses `robocopy` in windows (if available) to avoid this kind of errors. This issue can be closed now. Thank you!

**Pull request closed without merging**
