### PR TITLE
#5101 Export detected_os from OSS Tools

### LINKED ISSUE #5101: [BUG] Conan Tools does not export detected_os
To help us debug your issue please explain:

When I was updating cmake_installer, I just found that `detected_os` is not exported by conans.tools

Conan Version 1.15.0

```python
from conans import tools

if __name__ == "__main__":
	tools.detected_os()
```

**ERROR**: 
```
Traceback (most recent call last):
  File "conanfile.py", line 4, in <module>
    tools.detected_os()
AttributeError: module 'conans.tools' has no attribute 'detected_os'
```

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

### PR DESCRIPTION
**Pull request by uilianries**
Add alias for tools.oss.detected_os

Changelog: Fix: Export detected_os from tools.oss (#5101)
Docs: https://github.com/conan-io/docs/pull/1276
fixes #5101

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by uilianries** [comment]
What? migration test error? But my patch is only about an unit test ... Go home Jenkins, you are drunk

https://conan-ci.jfrog.info/blue/organizations/jenkins/ConanTestSuite/detail/PR-5102/1/pipeline#step-131-log-1309

**Comment by lasote** [comment]
Merge develop to get rid of that error.

**Comment by jgsogo** [comment]
@uilianries, please merge upstream, it should solve the error in CI. Thanks!

**Comment by uilianries** [comment]
@jgsogo done! let's see the result :)

**Pull request merged**
