### PR TITLE
WIP Deployment to create compressed artifacts

### PR DESCRIPTION
**Pull request by sigmoidal**
I have made my first attempt on a conan feature. This feature is primarily based on the premise that conan has a long way to becoming the defacto way of using third-party libraries and thus a transition period would be required, even if it becomes *the* standard tool to manage deps.

### What
Make it simple to create deployments of compressed package artifacts in human readable archives, enabling distribution outside the conan ecosystem.

### Why
There are many reasons to turn conan packages into compressed distributable archives. The most important ones:

 - Upstream developers/maintainers/packagers of existing software need to still serve their existing users via alternative (non-conan) channels, such as ftp, web, project pages, etc. Getting them to replace their current build tools with conan, while keeping their users happy, makes conan more attractive to them.

 - Enable non-conan end-users to benefit from all the work being put into clean builds of various important packages, despite not having adopted conan yet. 

 - There are many contexts where it is time-consuming and out of scope to have to install python, conan, etc. to just get a dependency. (think education, critical system's & security QA where devs are not using third-party software from unverified channels, etc.)

 - As @grafikrobot suggested to me, it may make sense to expand such a feature to generate *nix system packages in the future.

(there are more, but I'll stop here and we can discuss this further if necessary)

### How
The approach I took was to leverage the newly introduce deploy() function (per the suggestion of @drodri) and a separate specialized class Deployment that takes the content of the built package and turns it into an archive (.zip, .tar.gz, .tar.bz2, .tar.xz). See below the two commands necessary to create those "deployments".

```
    def deploy(self):
        # create an instance of a deployment
        dp = Deployment(self)

        # we can create an archive using the deployment
        # output_file can be overriden by the user, or use the one computed automatically.
        # supports: zip, tar.gz, tar.bz2, tar.xz
        if self.settings.os == "Windows":
            dp.compress(output_file=dp.filename, compression='.zip')
        else:
            dp.compress(output_file=dp.filename, compression='.tar.bz2')

        # atm, i chose not to delete automatically the deployment folder (for safety)
        #self.output.info("You could delete: %s" % dp.deployment_dir)
```

`dp.filename` is computed internally to a human readable filename that is used as the archive name, but it can be trivially overridden by the user. The formatting pattern could also be exposed to enable user-supplied formatting patterns.

I would appreciate any feedback on whether this is a feature that would be worth improving and eventually including into conan's core. I know little about conan's internals, so let me know how this can be technically improved. I have no strong feelings about the naming of the feature, but I am having a feeling it may need a better name.

cheers.

### CODE REVIEW

**Comment by memsharded** [comment]
I think this is a valid feature, in fact it is aligned with an issue from long time ago: the possibility to create installers (lets call it packing) with conan, for deb, msi, and others. 

So I'd say this is interesting, but I would suggest to carefully think a bit more about its usage, interface and later generalization:

- Adding the functionality to the ``deploy()`` methods ties the packing to the package recipe. So if a package author only provides a ``deploy()`` for zip/tgz files, it would be impossible to generate .deb or .msi installer from it
- Once the files to be "packed" are defined (binaries, exes, shared libs, license, data-files), a common tooling to create the installers could be defined
- It seems that the final installer should be user-selected. I might want a zip installer when I am in Windows, and not a .msi installer, or a tgz instead of a .deb isntaller when I am in Debian/Ubuntu, even if the ``deploy()`` supports both .msi and .deb packages.

So I like the feature, but I am concerned about the difficulty to evolve, generalize and maintain it without breaking it once it is coded in user recipes.

My suggestion (just and idea for discussion) would be:
- Clearly define some interface for creating such final "packing". What is the files layout. What files should exist in each one.
- Use the current ``deploy()`` to just extract the binaries from the local cache to user space
- Try a new experimental "pack" command, that will contain the logic to do this. 
- Most configuration would be in command line: ``conan pack . --target=deb`` and ``conan pack . --target=zip``
- The implementation of the "zip" and "tgz" targets would be based on the current ``Deployment`` class

**Comment by ovidiub13** [comment]
I like the idea of having this in a separate `conan pack` command.

**Comment by sigmoidal** [comment]
I have implemented the feature as a conan command, albeit my code is probably not clean enough yet. For example:

```
cd D:\archives
conan pack MyLib/1.0@sigmoidal/testing \
               --package_id c0a8ac7453d9a1817dd30d7fab29b3134611f1ee \
               --out some_output_dir 
               --target zip
```

The command uses a package's dir as the source of the compressed pack, in this case:

`
<conan storage>/MyLib/1.0/sigmoidal/testing/package/c0a8ac7453d9a1817dd30d7fab29b3134611f1ee 
`

Anything that is in this folder is copied over to <some_output_dir>/<auto-constructed-dirname>:

`
D:\archives\some_output_dir\MyLib-1.0-win-x86-release-MD-shared-vs2017
`

Then it is compressed in:

`
D:\archives\some_output_dir\MyLib-1.0-win-x86-release-MD-shared-vs2017.zip
`

The --target scheme supports the other options, etc.

Does that sound about right? If that's ok, I can clean it up and submit another PR for review of the feature.


thanks.

**Comment by sigmoidal** [comment]
I've updated the code for v0.29.1. See #2077

**Pull request closed without merging**
