### PR TITLE
add default_deploy feature enabling the deployment of any package

### PR DESCRIPTION
**Pull request by solvingj**
In response to: #3280

The primary capability added with this feature, is the long-requested ability to "easily get ahold of" any arbitrary file from any existing Conan package for use outside of Conan from a single CLI call without having to create some intermediate recipe.  It is fundamentally different from the existing `deploy` functionality, which requires recipes to be written with `deploy()` methods before they can be deployed. 

One noteworthy decision about scope with this implementation is that the feature provides only a simple extraction of artifacts to user space.  Users will no doubt need to apply custom logic for selecting specific files and moving them to custom destinations.  With this implementation, any such logic must all be implemented in scripts outside of Conan.  This seems reasonable as most of the non-trivial uses of this feature are likely to involve automated CI scripts which are calling Conan CLI anyway.  

An alternative to this feature which would enable users to achieve a similar capability would be for the `conan info` command to return manifests of the contents of packages with full local file paths for each file.  This seemed more complex to implement, and will require users to loop over the results outside of Conan.  Requiring the user to loop over results seems reasonable for devops automation use cases, and would save an unnecessary copy compared how my team is using this `default_deploy` feature currently. Personally, I would like both features to co-exist. 

While still a rough draft, this feature feature has solved some very real-world devops workflow challenges we had when integrating Conan into an existing environment, relating to migrations between workflows. 

Until there is some approval to move forward with this feature in principle, I will wait to write a documentation PR for it. 

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. Also adding a description of the changes in the ``changelog.rst`` file. https://github.com/conan-io/docs

### CODE REVIEW

**Comment by lasote** [comment]
Hi Jerry, sorry for the delay. @memsharded is investigating some alternative related to abstract the installation paths that maybe could cover this feature. At the moment we want to end the investigation until we decide if we continue with this idea.

**Comment by solvingj** [comment]
You can close if you feel the need.  I'll just have to maintain this feature in our private fork of Conan since we use it heavily.   

Again, I would rather see `conan info` get a `package_path` field in JSON output which lets me get at the package directory in the client cache for a given package/settings/options set.  This opens a better path to integrations and custom-deploy logic IMO. 

After using this feature internally, I can say that it's only re-inforced my initial feeling that "deployment" layout is not something Conan should be aware of.  Having authors hard-code deployment path logic into recipes feels wrong.  For those who are using the deploy feature to specify destinations, I'm sure it's more convenient than maintaining external scripts to handle that logic, so I'm sure I'm in the idealistic minority here.  However, we have a separate set of scripts in a separate Jenkins stage called `deploy.py` that operates much like `build.py`, and a `deployfile.py` which maintains all the logic for post-conan operations (making rpms/debs/msis/etc).  It feels like the right abstraction.

**Comment by jgsogo** [comment]
> Again, I would rather see conan info get a package_path field in JSON output which lets me get at the package directory in the client cache for a given package/settings/options set. This opens a better path to integrations and custom-deploy logic IMO.

I think this is covered with https://github.com/conan-io/conan/pull/3717 that solves the issue #3641, now a consumer can know where the package has been generated and inspect that folder. The general behavior of copy-it-all may not be suitable for all use cases.

**Comment by solvingj** [comment]
Thanks for the feedback. 

I'm still firmly of the opinion that it makes sense to have the ability to `copy-it-all` for cases where recipes have no `deploy` method.  I agree that this behavior would certainly not be suitable for all cases, but that's true of all default behavior.  Also, this proposal isn't actually proposing a general or default behavior, but rather a specific flag with to over-ride behavior for specific cases (where there's no deploy method).  Again, most OSS packages won't have `deploy()` methods, and I personally don't think they should.  

The decision being made here is: 
> We're choosing to keep it impossible to use the `deploy` feature of Conan to do simple package extraction to user-directories with the vast majority of OSS packages.  Users will need to call `conan info` and write their own parser and copy logic in an external script if they want to get files out of these packages, or alternatively use a bespoke deployment plugin in the future."  

In either case, seems wrong to me when a practical and useful implementation is already proven out here in a PR. It works, and it's extremely straightforward. Maybe it's bias because it's my PR and my need, but I really can't comprehend the resistance here.

**Pull request closed without merging**
