### PR TITLE
Use PKG_CONFIG_PATH in Meson helper if defined

### PR DESCRIPTION
**Pull request by noverby**
The way it works now, the Meson helper overwrites the existent `PKG_CONFIG_PATH` value.
The current behavior is not consistent with CMake helper, where `PKG_CONFIG_PATH` is used if it is defined.

This is useful if Conan hooks automatically sets the `PKG_CONFIG_PATH` of Conan requirements.

Changelog: Fix: Use PKG_CONFIG_PATH in Meson helper if defined
Docs: https://github.com/conan-io/docs/pull/6568
Issue: https://github.com/conan-io/conan/issues/6440

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by TheQwertiest** [comment]
@noverby , your docs PR link is invalid.

**Comment by memsharded** [comment]
Having a look at this PR, I am a bit confused because this is not implementing the thing that the referred issue #6440 is reporting.

It seems asymetrical to what is in the ``CMake`` build helper, but it is what is documented in the docs:

> pkg_config_paths (Optional, Defaulted to None): A list containing paths to locate the pkg-config files (*.pc). If None, it will be set to conanfile.build_folder.

The mistake there is that it assumes the ``build_folder`` is the same as ``install_folder`` in this case. That could probably be fixed, but not setting the PKG_CONFIG_PATH env-var because it is already defined, would be breaking behavior. We certainly need to improve this and make this homogeneous when we get to Conan 2.0, but at the moment it doesn't seem possible without breaking other users.

**Comment by noverby** [comment]
@memsharded I just copied the exact code/behavior of the `CMake` helper class.

For anybody interested, here is my workaround for the inconsistent behavior of the `Meson` helper class:
```python
meson.configure(pkg_config_paths=os.environ["PKG_CONFIG_PATH"].split(":"))
```

**Comment by memsharded** [comment]
This PR became obsolete. Please check the new Meson integration in https://docs.conan.io/en/latest/reference/conanfile/tools/meson.html (it automatically adds ``pkg_config_path`` to the Meson files). Closing this, thanks!

**Pull request closed without merging**
