### PR TITLE
Conan 1.x: set `CMAKE_FRAMEWORK_PATH` in CMakeToolchain generator for `find_package()` 

### LINKED ISSUE #14334: [bug] Conan 1.x: `CMAKE_PREFIX_PATH` cannot be set to `self.package_folder`
### Environment details

* Operating System+version: Ubuntu 20
* Compiler+version: irrelevant
* Conan version: 1.60.1
* Python version: 3.8.10

### Steps to reproduce

I am using `CMakeToolchain` generator.

`conanfile.py` (mylib)
```
def package_info(self):
        self.cpp_info.builddirs.append(self.package_folder)
```

`CMakeLists.txt` (test_package)
```
message(STATUS "CMAKE_PREFIX_PATH '${CMAKE_PREFIX_PATH}'"
```

I can see that the explicitly specified `self.cpp_info.builddirs` is not added to `CMAKE_PREFIX_PATH`.
According to the comments in `blocks.py` it `# The explicitly defined "builddirs" of "host" context dependencies must be in PREFIX_PATH`

### Logs

_No response_

### PR DESCRIPTION
**Pull request by thorsten-klein**
Changelog: (Feature | Fix | Bugfix): add explicitly specified builddirs to CMAKE_PREFIX_PATH

In `CMakeToolchain` generator explicitly specified `self.cpp_info.builddirs` should be prepended to `CMAKE_FRAMEWORK_PATH`. 
Additionally the paths should not be prepended multiple times but only one time.

Docs: https://github.com/conan-io/docs/pull/XXXX

This PR fixes #14334 
- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one.

### CODE REVIEW

**Comment by thorsten-klein** [comment]
I have changed the PR now to use `CMAKE_FRAMEWORK_PATH` on Linux and Windows too

**Review by memsharded — COMMENTED** [review]
Hi @thorsten-klein 

Thanks for your contribution.
You can check that CI is being broken by these changes, this is because the different behaviors are not that evident due to the evolution and legacy.

As this is a risky change, I think we need to start with a "red" test, with the problem we are trying to solve first. Then we can discuss the possible different solutions that will not break other Conan users.

If you want to give it a try, it will be very welcome, otherwise I can try to do that test, if you provide a bit more of context in the associate issue https://github.com/conan-io/conan/issues/14334, like a basic dependency ``conanfile.py`` and a basic consumer ``conanfile.py`` together with the consumer ``CMakeLists.txt``, and I can build the test from there. 

Thanks!

**Comment by thorsten-klein** [comment]
Hello @memsharded ,
I have had a look. I changed to ignore paths which do not exist in order to keep the `CMAKE_` variables clean.
In the unittest the path `/path/to/builddir` is used, which of course does not exist and the test is therefore filtered out / ignored.

I have adapted the PR now to keep old behavior = all paths remain in the list even if they do not exist.
What do you think about this? Does it make sense in future that non-existent paths should be ignored?

**Comment by thorsten-klein** [comment]
@memsharded  I have created some test for it. I hope it is at the correct place.

The package_folder can now be appended to `CMAKE_FRAMEWORK_PATH` by specifying `self.cpp_info.frameworkdirs.append(self.package_folder)`

**Comment by thorsten-klein** [comment]
Changing conan 1.x to support CMAKE_FRAMEWORK_PATH is maybe little bit overkill. I close this PR now and open another one with another much simpler solution (#14401)

**Pull request closed without merging**
