### PR TITLE
removed duplicated line in b2 output

### PR DESCRIPTION
**Pull request by grisumbras**
Changelog: Fix: Removes duplicate lines from b2 generator output

- [ ] Refer to the issue that supports this Pull Request.
- [X] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [X] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've followed the PEP8 style guides for Python code.

### CODE REVIEW

**Comment by lasote** [comment]
@grisumbras should this be a draft or not?

**Comment by grisumbras** [comment]
I planned to "undraft" it after my 2 other PRs are merged. The reason being, it is very likely it won't merge automatically, as the other 2 edit the same files (and lines). If this is not a problem, I can press "Ready for review".

**Comment by lasote** [comment]
NP. Just wondered why.

**Comment by lasote** [comment]
The other two has been merged

**Pull request merged**
