### PR TITLE
Add prefix for query (#5540)

### PR DESCRIPTION
**Pull request by uilianries**
- option: and o: for options search
- setting: and s: for settings search

Changelog: Feature: Search query with custom settings and deterministic options
Docs: https://github.com/conan-io/docs/pull/1383

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [x] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by uilianries** [comment]
the last build failed due pip error during installation process.

**Comment by memsharded** [comment]
Hi @uilianries 

I don't know why this was not reviewed from us, sorry about that. Is this still a use case in 2.0? 
Do you want to check the 2.0 commands, and see if there are potential ambiguities that this syntax might solve? It would be a good moment, before declaring stable the 2.0 CLI.

**Comment by uilianries** [comment]
2 years later ... 😂 Well, better late than never. For Conan 1.x I don't know, probably someone asked it on Slack, because there is no issue.

For Conan 2.0, I feel `conan search` more limited, as query argument no longer exist, but it's fine. It could be included in the future if people start to ask I guess.

So far, we have the follow result:

```
% venv/bin/conan --version    
Conan version 2.0.0-beta3

% venv/bin/conan search --help                              
usage: conan search [-h] [-f FORMAT] [-v [V]] [--logger] [-r REMOTE] query

Searches for package recipes in a remote or remotes

positional arguments:
  query                 Search query to find package recipe reference, e.g., 'boost', 'lib*'

options:
  -h, --help            show this help message and exit
  -f FORMAT, --format FORMAT
                        Select the output format: json
  -v [V]                Level of detail of the output. Valid options from less verbose to more verbose: -vquiet, -verror, -vwarning, -vnotice, -vstatus, -v or -vverbose, -vv or -vdebug, -vvv or -vtrace
  --logger              Show the output with log format, with time, type and message.
  -r REMOTE, --remote REMOTE
                        Remote names. Accepts wildcards. If not specified it searches in all remotes

% venv/bin/conan search -r conancenter zlib/1.2.11@        
conancenter:
  zlib
    zlib/1.2.11
```

**Comment by memsharded** [comment]
> For Conan 2.0, I feel conan search more limited, as query argument no longer exist, but it's fine. It could be included in the future if people start to ask I guess.

It is because the equivalent is not ``conan search``, but ``conan list packages``, there you will still have a query.

**Comment by uilianries** [comment]
@memsharded does `conan list packages` work with current Conan center?

```
% conan --version           
Conan version 2.0.0-beta3

% conan list packages -r conancenter zlib/1.2.11@       
ERROR: Invalid 'zlib/1.2.11@' missing revision. Please specify one revision or '#latest' one

% conan list packages -r conancenter zlib/1.2.11@#d77ee68739fcbe5bf37b8a4690eea6ea 
conancenter:
  There are no packages

% conan list packages -r conancenter zlib/1.2.11@#latest 
conancenter:
  There are no packages
```

I mean, on Conan v1, a simple `conan search -r conancenter zlib/1.2.11@` shows me everything, now a I need to be very specific.

**Comment by memsharded** [comment]
> @memsharded does conan list packages work with current Conan center?

No, it doesnt (it works if there are no packages, the output is correct, but if there are packages, server will return 500). That is the known Conan 2.0 Artifactory limitation (we are on it)

Needs to be tested in codebase unittests, not against server.

**Comment by uilianries** [comment]
Closing this PR, as Conan 2.x supersedes it.

**Pull request closed without merging**
