### PR TITLE
Update check_compiler_version macro to handle latest Visual Studios

### PR DESCRIPTION
**Pull request by jmarrec**
Changelog: Fix: A simple addition to ensure right compiler version is found on windows.

(I have read the contributing guide. It's such a small thing that I didn't bother to create an issue first for this though).

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code: N/A
- [x] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one: N/A

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by memsharded** [comment]
Hi @jmarrec 

Thanks for trying to contribute this PR. 
The tests are broken, you can see the output of CI here: https://conan-ci.jfrog.info/blue/organizations/jenkins/ConanTestSuite/detail/PR-5041/1/pipeline. You can also try to run the tests locally with ``nosetests``.

The problem is that you are using lexicographic string compare with ``STRLESS`` and you probably need to use numerical or version comparison in order to achieve the expected result. Please have a look at it, thanks!

**Comment by jmarrec** [comment]
Hi, yeah I did see the failures earlier. Will look when back at a computer. What's the earliest cmake you intend to support? (Some functions aren't available in older cmake versions (eg strless_equal, not that I intend to use this one in particular))

**Comment by memsharded** [comment]
Hi.
Yes, we are still trying to support CMake down to 2.8.12. This might change in the future, but so far, we are maintaining ourselves a few hacks to be compatible. Unfortunately there are still some users that can't upgrade cmake from that version easily.

**Comment by memsharded** [comment]
Great, thanks for the contribution

**Pull request merged**
