### PR TITLE
Ensure direct tool requires conflicts are properly reported instead of hanging

### PR DESCRIPTION
**Pull request by AbrilRBS**
Changelog: Fix: Ensure direct tool requires conflicts are properly reported instead of hanging.
Docs: Omit

### CODE REVIEW

**Review by memsharded — APPROVED** [review]
The XCRun test refactor is unrelated to this PR, better do it separately as a general rule (I think it can be left here as it is already done and the change is trivial)

**Comment by AbrilRBS** [comment]
Oh noes, the curse of `git add .` strikes again! Commited by mistake, was meant to go in a separate PR after I looked into the rst of the integration tests to double-check that nothing uses actual programs

**Comment by memsharded** [comment]
> Oh noes, the curse of git add . strikes again! Commited by mistake, was meant to go in a separate PR after I looked into the rst of the integration tests to double-check that nothing uses actual programs

Not a big deal! It can stay, not worth the effort to move it to another PR now

**Review by perseoGI — APPROVED** [review]
LGTM!

**Review by ErniGH — APPROVED** [review]

**Pull request merged**
