### PR TITLE
Copy symlinks (folders) in 'merge_directories' func

### LINKED ISSUE #5080: Conan Create (scm) copy source removing folder symlink
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

```
Conan version 1.14.3
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

Hi there,
It appears when running `conan create` locally or remotely, folder symlinks are removed when source is copied to the build folder. This is not true for file symlinks. We are using the `scm` feature.

After running `conan create` and going to the build directory:
```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    Libs/prebuilt/Debug
```

```
lrwxrwxrwx  1 mh70023 bluetooth    8 Feb 21 14:14 Debug -> Release/
```

All other file symlinks are working as intended and are not deleted.
I have checked my .gitignore as well for errors.

### PR DESCRIPTION
**Pull request by jgsogo**
Changelog: Fix: Copy symlinked folder when using `merge_directories` function
Docs: omit

closes #5080 

This PR is just targeting the bug reported in #5080, which was already patched in lasote's branch 🍰 . 

About replacing the code in `merge_directories` with `FileCopier` one, I'm agree, but I think we should leave it for another issue/pr, wdyt?

### CODE REVIEW

**Comment by SSE4** [comment]
this doesn't work for me:
```
ERROR: [HOOK - conan-center.py] pre_export(): [Errno 62] Too many levels of symbolic links: '/Users/sse4/bincrafters/test-symlinks/test'
Traceback (most recent call last):
  File "/Users/sse4/bincrafters/conan/conans/client/hook_manager.py", line 58, in execute
    method(output=output, **kwargs)
  File "/Users/sse4/.conan/hooks/conan-center.py", line 58, in wrapper
    ret = func(output, *args, **kwargs)
  File "/Users/sse4/.conan/hooks/conan-center.py", line 142, in pre_export
    @run_test("RECIPE FOLDER SIZE", output)
  File "/Users/sse4/.conan/hooks/conan-center.py", line 67, in tmp
    ret = func(out)
  File "/Users/sse4/.conan/hooks/conan-center.py", line 151, in test
    total_size += os.path.getsize(file_path)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 62] Too many levels of symbolic links: '/Users/sse4/bincrafters/test-symlinks/test'
```
repro:
```
mkdir test-symlinks
cd test-symlinks
conan new test/1.0@user/testing
ln -s test test
conan create . user/testing
```

**Comment by jgsogo** [comment]
@SSE4, that one is failing in the hook, not in Conan itself. Can you run your test without the hook? (...and maybe submit this issue to the `hooks` repo if it is related to an _official_ one).

**Comment by SSE4** [comment]
ah, didn't notice that, sorry :(

**Comment by SSE4** [comment]
still fails:
```
ERROR: Traceback (most recent call last):
  File "/Users/sse4/bincrafters/conan/conans/errors.py", line 24, in conanfile_exception_formatter
    yield
  File "/Users/sse4/bincrafters/conan/conans/client/packager.py", line 68, in create_package
    conanfile.package()
  File "/Users/sse4/.conan/data/test/1.0/bincrafters/testing/export/conanfile.py", line 48, in package
    self.copy("*", dst="a", keep_path=False)
  File "/Users/sse4/bincrafters/conan/conans/client/file_copier.py", line 75, in __call__
    keep_path, excluded_folders=excluded)
  File "/Users/sse4/bincrafters/conan/conans/client/file_copier.py", line 93, in _copy
    copied_files = self._copy_files(files_to_copy, src, dst, keep_path, symlinks)
  File "/Users/sse4/bincrafters/conan/conans/client/file_copier.py", line 221, in _copy_files
    shutil.copy2(abs_src_name, abs_dst_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 153, in copy2
    copyfile(src, dst)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 62] Too many levels of symbolic links: '/Users/sse4/.conan/data/test/1.0/bincrafters/testing/build/f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2/test1'
```

**Comment by jgsogo** [comment]
... but I think that it is an OS error, because of the line `ln -s test test`, you are linking a folder to itself and it creates some kind of recursion trying to iterate it (_"Too many levels of symbolic links"_):

```bash
⇒  mkdir tmp
⇒  ln -s tmp tmp
⇒  cd tmp
⇒  cd tmp
cd: too many levels of symbolic links: tmp
```

I'm not sure if this is something we can handle in Conan, nevertheless, I'll add a try/except to get rid of the ugly traceback and print just the error message.

**Comment by jgsogo** [comment]
btw, @SSE4, I'm not able to reproduce that error. If I create those kind of symlinks I get an error like this one: _"ERROR: The file is a broken symlink, verify that you are packaging the needed destination files: '.../test/1.0/user/testing/export_source/src/src'.You can skip this check adjusting the 'general.skip_broken_symlinks_check' at the conan.conf file."_ which is not the best, but at least it points in the right direction to the file/folder originating the problem.

**Comment by SSE4** [comment]
@jgsogo yes, we may change recipes to remove existing workarounds. right now we have to deal with compiler.runtime manually, e.g.:
https://github.com/bincrafters/conan-libiconv/blob/testing/1.15/conanfile.py#L91
https://github.com/bincrafters/conan-ffmpeg/blob/stable/4.1/conanfile.py#L255
otherwise, we don't get correct binaries. same story about meson:
https://github.com/bincrafters/conan-glib/blob/stable/2.58.3/conanfile.py#L79
https://github.com/bincrafters/conan-gstreamer/blob/stable/1.16.0/conanfile.py#L62
and it doesn't seem to be breaking - if recipe is already adding these flags, adding them for the second time will have no effect

**Pull request merged**
