### PR TITLE
Support multiline blocks and inline commets on profiles

### LINKED ISSUE #16328: [feature] Allow multiline blocks and inline comments in profiles
### Background 

While editing a profile, it may be convenient to have the possibility to add a comment on the same line and not above or below the current line. 

Also as there configurations that can potentially be really long in terms of a line of code, it may also be interesting to allow a `bash like` multiline support, ending in `\` character.

E.g.
```
include(otherprofile)

[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos           # this is a comment

[conf]
tools.cmake.cmaketoolchain:extra_variables={'STR': 'string # value', \   # Another comment
                                            'NUM': 1.3, \                                                        # More comments! 
                                            'CMAKE_GENERATOR_INSTANCE': '${ENV}/buildTools/', \
                                            'SOME_DICT': {'value': '42 sense', 'cache': 'true', 'type': 'BOOL', 'docstring': 'test cache var'} \
                                            }
```

### Considerations and caveats

Same as in `bash` or any other `shell like emulator`, the `#` character should only be interpreted as a beginning of a commentary if it is not inside of a string, thus between any quotation mark (`'` and `"`)

Also, backslash character `\` should only be taken into consideration if it does not belong to the end of a Windows path, e.g.
`C:\\users\file\`

A basic solution to avoid any problem with existing profiles with this form could be to only accept `\` characters for multiline purposes if they have at least one space between the end of the line and the backslash.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

### PR DESCRIPTION
**Pull request by perseoGI**
Changelog: Feature: Support multiline blocks and inline commets on profiles
Docs: https://github.com/conan-io/docs/pull/XXXX
Closes: https://github.com/conan-io/conan/issues/16328

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop2/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one.

### CODE REVIEW

**Review by memsharded — COMMENTED** [review]
Case broken by this PR, profile with

```
[replace_requires]
zlib/1.3: zlib/1.3#rrev1
```

We can try to be smart and think about all the other potential corner cases that would be breaking, and keep increasing the regex complexity to cover those, but there will always be more that we cannot simply foresee. Take into account that profiles also support jinja syntax, that in turn can contain practically any python code, so regex based replacer there will always be risky.

**Comment by perseoGI** [comment]
> Case broken by this PR, profile with
> 
> ```
> [replace_requires]
> zlib/1.3: zlib/1.3#rrev1
> ```
> 
> We can try to be smart and think about all the other potential corner cases that would be breaking, and keep increasing the regex complexity to cover those, but there will always be more that we cannot simply foresee. Take into account that profiles also support jinja syntax, that in turn can contain practically any python code, so regex based replacer there will always be risky.

Yes, you are totally right! 
I've modified the code to ignore comment function of `#` if it is not at least separated by a blank character from the end of the line.
All tests are passing now. 

We may see if there is any other possible case where we could be breaking something. 
I can't think of any at the moment.

In terms of breaking changes in the jinja python injected code... I think there can't be any issue.
E.g. In this template...
```
[settings]
os = {{ {"Darwin": "Macos"}.get(platform.system(), platform.system()) }}
```
there can't be any `#` inside (except inside a string -> which are correctly handled by the regex)
And there is also no possibility to put a `\` at the end because a jinja template must always be surrounded by 
`{{ ... }}` or `{% ... %}`

Also, and fortunately, jinja supports natively multiline blocks without needing to add `\` at the end of each line so that is great!

**Review by memsharded — COMMENTED** [review]
```
{# # my useless comment #}

include(default)
```
Will break your regex replacer again.

I didn't have to provide a very complex profile, just one line to break your code.

See for reference https://github.com/conan-io/conan/issues/15544#issuecomment-1912802985 what some users are doing with profiles.

I think this is not worth the risk.

**Comment by memsharded** [comment]
Note, that if you want to have a beautiful formatted dict, you can probably define such a dict in jinja, then render it as text in the ``extra_variables`` field.

**Comment by memsharded** [comment]
Closing as risk is too high for little value.

**Pull request closed without merging**
