### PR TITLE
Implement vsprops creation.

### PR DESCRIPTION
**Pull request by sturmf**
This is a quick hack of a visual studio 2008 vsprops generator. 
I hope this or something similar could be merged into conan in the near future.

Implements https://github.com/conan-io/conan/issues/1697

### CODE REVIEW

**Comment by memsharded** [comment]
This looks very good indeed. Also, the good thing is that it is not in a critical path. Bugs, or any issues in this generator won't harm other conan users, so it is likely that we can accept it for next conan release. I would suggest adding at least some small tests, please check ``VisualStudioGeneratorTest``, adn ``GeneratorsTest`` so coverage doesn't decrease, and we are sure at least the basics are working. Please tell if you need help with these tests. Thanks very much!

**Comment by sturmf** [comment]
Thanks for the feedback, I now added a simple test based on the original visual studio test.
Please let me know if there is anything else missing which would prevent this from being merged upstream?

**Comment by sturmf** [comment]
I just wanted to check if everything is ok with this branch. Unfortunately the build on travis failed but it seems to be more a problem of the build server configuration and not my patch. 
But if you wish any changes to the branch don't hesitate to write me!

**Comment by memsharded** [comment]
Yes, don't worry, I just fired the failed job again, lately travis OSX is failing a lot.

Everything looks good so far, just a couple of very minor issues. I just wanted to try the feature manually myself and play a bit with it, then I will come with a review if necessary or just propose changes directly. Thanks!

**Comment by memsharded** [comment]
Proposed some small improvements in: https://github.com/sturmf/conan/pull/1

**Comment by memsharded** [comment]
I have also written some docs for it: https://github.com/conan-io/docs/pull/320, please have a look :)

**Comment by memsharded** [comment]
Uhm, it seems I broke the build in linux :(

Don't worry, I will check and propose a fix.  Appveyor failure seems to be not our fault, but Appveyor's

**Comment by memsharded** [comment]
No, we didn't broke the build. It is because of the merge, and some recently pushed changes to develop branch. I have merged and submitted a new PR.

**Comment by sturmf** [comment]
Thanks for merging my branch and I therefore will close this merge request here! 
I now also added myself to the contributors.txt file in this branch since I was not sure if I now should also fork your repo?

**Comment by memsharded** [comment]
Maybe the best is to submit a new, clean PR to develop, no need to fork my repo.
Also, CI is now broken, we are fighting against appveyor timouts, so don't worry if your PR is red, not your fault :) Thanks!

**Comment by sturmf** [comment]
Ahh ok I can do this, I have submitted one commit to this PR but I guess that's bad to merge...

**Comment by memsharded** [comment]
I had to re-launch my PR, so I just added your data in contributors.txt: https://github.com/conan-io/conan/pull/1727, so we don't have to wait for a long build just for a change in this text file :)

Cheers

**Pull request closed without merging**
