### PR TITLE
Fix for 'Visual Studio generator dll paths #264'

### PR DESCRIPTION
**Pull request by Xaltotun**
Added the dependent dll paths to the 'ExecutablePath' msbuild property in the Visual Studio Generator.

### CODE REVIEW

**Comment by Xaltotun** [comment]
Woops i missed part of the CL... half asleep still. Will redo this in a bit.

**Comment by memsharded** [comment]
Yes, now looks much better, no worries about the first PR :) Thanks for fixing this issue, I will merge it when CI passes. Good job!

**Comment by Xaltotun** [comment]
Should there be an option to copy the binaries to the output directory?  I can see it being useful for packaging.

**Comment by memsharded** [comment]
You mean, the [imports] section in conanfile.txt? It is used to copy dlls, or any other files to your current project. I usually copy shared libraries to my project output directory, so I can run executables from there without messing with the path.

**Comment by Xaltotun** [comment]
Ah ok. I was under the impression that wasn't working for the visual studio generator either, but i guess that doesn't make sense since it is handled by the install command.

**Comment by memsharded** [comment]
Oh, yes, the ``conan install`` command is still necessary, and it will manage to copy the dlls to the project. It is true that the conanfile.txt cannot handle dumping to different directories, that could be necessary for Visual, if we don't change the typical Visual output layout.

What can be done is using a conanfile.py instead of a conanfile.txt and create a smarter imports, something like:

```python
def imports(self):
    if self.settings.build_type == "Debug":
         self.copy("*.dll", "Debug", "bin")
    else:
         self.copy("*.dll", "Release", "bin")
```

Similarly the architecture can be taken into account

**Comment by Xaltotun** [comment]
Yeah i completely forgot about the imports function when i posted that yesterday.  The multiconfig layout of VS could be handled by a VS plugin that uses conan.  This would make conan work in a familiar way for VS users, but keep the conan VS generator consistent.

**Comment by memsharded** [comment]
Yes, a VS plugin would be definitely great. It is definitely in the roadmap, but it is a bit early now. Most likely after hitting the release 1.0.

**Comment by memsharded** [comment]
Hi @Xaltotun ,

I have tried the fix, but seems it doesnt work for my problem. The problem is that it still doesn't find the dlls, as it is not enough to add them to that dir, as it is only for exes. Maybe this stackoverflow answer gives some hint: http://stackoverflow.com/questions/6551414/is-it-possible-to-add-path-to-dll-in-visual-studio-2010-property-sheet

**Pull request merged**
