### PR TITLE
Hotfi as VS has not full XML support

### PR DESCRIPTION
**Pull request by claasd**
not every VS can handle . in names in properties. Replace them with -

### CODE REVIEW

**Comment by claasd** [comment]
If this PR should not go on the master, please tell me where it should go.

**Comment by memsharded** [comment]
@claasd, opened a 0.21.1 minor branch, and merged to it. Will wait one day or so, to see if more bugs arise, and release it. Thanks for fixing this.

**Comment by claasd** [comment]
Sure, no problem. I was the one who put this bug in :-(

**Comment by memsharded** [comment]
The only way not to introduce bugs is not to contribute, so no worries :)

**Pull request merged**
