### PR TITLE
test toolchain configs

### PR DESCRIPTION
**Pull request by memsharded**
Changelog: Fix: Define user variables in the ``conan_toolchain.cmake`` file, not in the project-include file.
Docs: Omit

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [ ] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by memsharded** [comment]
@jgsogo, please check this when possible, it seems that multi-config cmake vars can also work in the toolchain file, no need to put them in the ``conan_project_include.cmake`` file?

**Comment by jgsogo** [comment]
IIRC the problem with this approach is that those variables cannot be stored in the CMake cache (you cannot store and read the generator expression). This shouldn't be a problem as long as you run configure+generate together because you are not using the cache, but if you need to generate again it would be broken (is this what happens when CMake detects a file has been modified and generates again the project before compiling?)

I'm 90% sure about it.

**Comment by memsharded** [comment]
> IIRC the problem with this approach is that those variables cannot be stored in the CMake cache (you cannot store and read the generator expression). This shouldn't be a problem as long as you run configure+generate together because you are not using the cache, but if you need to generate again it would be broken (is this what happens when CMake detects a file has been modified and generates again the project before compiling?)

Good point, I'll add that case to the tests

**Comment by jgsogo** [comment]
I'm playing with this PR and so far it works because CMake is adding `CMAKE_TOOLCHAIN_FILE` to the cache and the file is parsed/used each time CMake runs... which lead me to the conclusion that **we don't need to store in the cache (`CACHE FORCE`) any of the variables we are defining in the toolchain**, we will have a cleaner cache and no one will see those variables in the cache and be tempted to modify them.

So I will probably delay this to `1.28`, we can get rid of everything we are writing to the cache... and check what happens with `MD/MT` substitution if we move them to the toolchain too (does it fail? do we have a confirmation?)

**Comment by memsharded** [comment]
> So I will probably delay this to 1.28, we can get rid of everything we are writing to the cache... and check what happens with MD/MT substitution if we move them to the toolchain too (does it fail? do we have a confirmation?)

Precisely for this, I would merge this now, as the toolchain is experimental, and we could have earlier feedback if this works or not for more use cases.

**Review by jgsogo — APPROVED** [review]
pa'dentro, let's see if something happens

**Pull request merged**
