### PR TITLE
Feature/cmake skip install rpath

### LINKED ISSUE #2038: CMAKE_SKIP_INSTALL_RPATH is not set on macOS
Hi,

According to the docs `conan_basic_setup()` sets `CMAKE_SKIP_RPATH 1` on macOS.
However, `otool -L my_installed_lib.dylib` gives the following output:

>@rpath/libmy_installed_lib.dylib (compatibility version 0.0.0, current version 0.0.0)

Whereas the one in the build folder doesn't have the `@rpath/` prefix.

Is this intended? I'm kind of a n00b with rpaths.

EDIT: setting `cmake.definitions["CMAKE_SKIP_INSTALL_RPATH"] = "ON"` in my recipe fixes the issue.
EDIT2: that's weird though, the CMake doc says that CMAKE_SKIP_RPATH includes CMAKE_SKIP_INSTALL_RPATH...

### PR DESCRIPTION
**Pull request by lasote**
Fix of the PR #2112. Closes #2038
@theodelrieu

### CODE REVIEW

**Comment by memsharded** [comment]
I really hate this cmake stuff. The thing is that setting policies to OLD is really discouraged by the cmake docs (https://cmake.org/cmake/help/v3.9/manual/cmake-policies.7.html#manual:cmake-policies(7)) but maybe we are in a case that makes sense.

Agree about the KEEP_RPATHS change (should we deprecate SKIP_RPATHS for conan 1.0?)

**Comment by theodelrieu** [comment]
In that case what about `set(CMAKE_INSTALL_NAME_DIR "")`?

**Comment by memsharded** [comment]
Yes, I think I like it more, wdyt @lasote?

**Comment by lasote** [comment]
Ok `set(CMAKE_INSTALL_NAME_DIR "")` then. About deprecating the `SKIP_RPATHS`, not sure, we are going to change the default behavior for many many packages. Probably we shouldn't do it that quickly. I'm going to add a message of deprecation when using `SKIP_RPATHS`.

**Pull request merged**
