### PR TITLE
possibility to require itself, previous version visible=False

### PR DESCRIPTION
**Pull request by memsharded**
Changelog: Feature: Allow a recipe to ``requires(..., visible=False)`` a previous version of itself without raising a loop error.
Docs: Omit

### CODE REVIEW

**Comment by gegles** [comment]
@memsharded, any progress/update on this? Just curious. Thx!

**Comment by memsharded** [comment]
@gegles we are still consider this, the possible risks and future challenges.

What is your use case? Could you please elaborate why are you interested in this feature? So far we have considered it for a very extraordinary situation with openssl, but I can't think of many other cases beyond it.

**Comment by gegles** [comment]
> @gegles we are still consider this, the possible risks and future challenges.
> 
> What is your use case? Could you please elaborate why are you interested in this feature? So far we have considered it for a very extraordinary situation with openssl, but I can't think of many other cases beyond it.

Yes, the use case I am interested in is the OpenSSL/FIPS use case that started this whole thing. See the initial idea presented by @jcar87 [here](https://github.com/conan-io/conan-center-index/issues/22796#issuecomment-2079830251).

You're right, as of now, I don't see any other use case for this... but , from my POV, this would be the most elegant and useful way for the community to get the exact right set of binaries directly within the single openssl recipe/package and without needing to do any weird repackaging outside...

As long as it does not harm anything else, I believe loosening the restrictions just enough for something like this to be possible would be a great thing.

Thanks!

**Review by czoido — APPROVED** [review]

**Review by jcar87 — APPROVED** [review]

**Comment by gegles** [comment]
Thanks @memsharded!

I'll wait till this is released and will try to work on the update to the OpenSSL recipe based on @jcar87's suggestion.

**Comment by memsharded** [comment]
> I'll wait till this is released and will try to work on the update to the OpenSSL recipe based on @jcar87's suggestion.

The problem is that this will not work with Conan 1, and that is still running on ConanCenter CI, so it might be a bit early to submit this to openssl recipe there, and we might need to wait a bit more.

**Comment by szigetics** [comment]
@memsharded : Do you have any plans to backport this change to Conan v1?

**Comment by memsharded** [comment]
Hi @szigetics 

No, I am afraid this is extremely challenging to be backported to Conan 1.X, this will be a Conan 2.X-only feature.

Note that Conan 2 is already 19 months old, all the dev effort has been moved to Conan 2, it is very strongly recommended to move to Conan 2 as a high priority.

**Pull request merged**
