### PR TITLE
Feature: Support yaml list as workspace root.

### LINKED ISSUE #5155: [suggestion] [workspaces] Support yaml list as workspace root
Using yaml list for setting the workspace root variable makes it easier to manage the yaml file, when the workspace has multiple roots.

I would like to contribute to this feature.

### PR DESCRIPTION
**Pull request by birgerbr**
This pull-request closes #5155

### CODE REVIEW

**Comment by jgsogo** [comment]
Hi, it looks pretty good. Can you please add a test like [this one](https://github.com/conan-io/conan/blob/6022abf83a61e7bba720bff4349118ee818b018e/conans/test/functional/workspace/workspace_test.py#L191) using a yaml list? (maybe you can just `parameterize` that unittest).

If you need help with the test, please let me know.

Thanks for the contribution!

**Comment by birgerbr** [comment]
> Hi, it looks pretty good. Can you please add a test like [this one](https://github.com/conan-io/conan/blob/6022abf83a61e7bba720bff4349118ee818b018e/conans/test/functional/workspace/workspace_test.py#L191) using a yaml list? (maybe you can just `parameterize` that unittest).
> 
> If you need help with the test, please let me know.
> 
> Thanks for the contribution!

Thanks! I've added a new test based on [multiple_roots_test](https://github.com/conan-io/conan/blob/6022abf83a61e7bba720bff4349118ee818b018e/conans/test/functional/workspace/workspace_test.py#L191). Using `parametrize` would reduce the code duplication. Is it `parameterized.parameterized` (`from parameterized import parameterized`) that should be used then?

**Comment by jgsogo** [comment]
Yes, we use `parameterized.parameterized`, you can find it at several places in the test suite.

**Comment by birgerbr** [comment]
Should I create a new commit which uses `parameterized.parameterized` instead of having a separate test?

**Comment by jgsogo** [comment]
Yes, I think it is much better to avoid duplicating code.

**Comment by birgerbr** [comment]
I've refactored the test to parametrize `multiple_roots_test` instead of having an additional test.
Another question: Should I squash these commits into a single commit?

**Comment by jgsogo** [comment]
Don't worry about it, we squash on merge. Thanks a lot!

**Comment by birgerbr** [comment]
Thanks :+1:  Should be ready for review now.

**Comment by memsharded** [comment]
Very nice, and also good test, thanks @birgerbr for the contribution and @jgsogo for the collaboration, good job.

**Comment by memsharded** [comment]
Will be released in Conan 1.16

**Comment by memsharded** [comment]
@birgerbr 

Note how I have updated the original first comment to add for ``Changelog`` and ``docs``. This is automatically used in our releases for the changelog. Also please have a look to the PR of the contributed doc, and check if it is correct, please. Every PR that changes or add things for users, should have an accompanying PR to the docs. 

Many thanks again!

**Comment by birgerbr** [comment]
Thanks! I'll remember that for the next time.
I've looked through the doc changes. They look good to me :+1:

**Pull request merged**
