### PR TITLE
Refactorize the parser of cpp_info in TXTGenerator

### PR DESCRIPTION
**Pull request by jgsogo**
Changelog: omit
Docs: omit

This PR tries to simplify a little bit how the information related to ``cpp_info`` is parsed from ``conanbuildinfo.txt``. It basically reads it all and afterward builds the data structures.

----
I need this refactor to continue working in #3641 in order to remove ``version`` from ``cpp_info``. Why do I need this PR? I will write in ``conanbuildinfo.txt`` the full reference string under a tag called `[conanfileref[_<dep>]]`; this refactor makes it easier to group all the information related to a reference together, look for the reference string and then create the ``cpp_info`` structures.

### CODE REVIEW

**Comment by jgsogo** [comment]
### About the ``conanbuildinfo.txt`` issue (commented in code with the ``FIXME`` block).

In the diamond test, the ``conanbuildinfo.txt`` for library ``Hello4`` has the following structure:

```txt
...
[libs]
helloHello3
helloHello1
helloHello2
helloHello0
...

[libs_Hello3]
helloHello3

...

[libs_Hello1]
helloHello1

...

[libs_Hello2]
helloHello2

...

[libs_Hello0]
helloHello0
```

so, if we use to add information about dependencies ``DepsCppInfo::update(dep_cpp_info, dep)`` with the merge logic that is applied for libraries, we end up with the following list of libraries: ``[2, 3, 0, 1]`` instead of the desired ``[3, 1 , 2, 0]`` and the linker fails because libraries defining symbols must be after their usage.

The workaround is to avoid the merge behavior by assigning the data to the private member instead of using the public function.

If the file ``conanbuildinfo.txt`` had the full information for dependencies, then we could have used the ``update`` function, something like this would have been enough:

```txt
...
[libs]
helloHello3
# Transitive deps are not essential here
helloHello1
helloHello2
helloHello0
...

[libs_Hello3]
helloHello1
helloHello2

...

[libs_Hello1]
helloHello0

...

[libs_Hello2]
helloHello0

...

[libs_Hello0]

```

And also, I will improve the ``merge_list`` behavior in ``build_info`` so it doesn't depend on the order of appeareance of the libraries in this file... even though this order is given by the same class.

**Comment by memsharded** [comment]
> I need this refactor to continue working in #3641 in order to remove version from cpp_info

The conanbuildinfo.txt cannot be changed, it is being used directly by users. Adding things is possible, but not removing, as that would be breaking.

**Comment by jgsogo** [comment]
So ignore the second comment, but the PR does not remove anything from the ``conanbuildinfo.txt``, it is just adding one _config_ section:

> I will write in conanbuildinfo.txt the full reference string under a tag called [conanfileref[_< dep >]]

**Comment by jgsogo** [comment]
image

👍

**Pull request merged**
