### PR TITLE
fixing test with abs path to sh.exe

### PR DESCRIPTION
**Pull request by memsharded**
Changelog: omit
Docs: omit

This test was failing in Windows due to hardcoded path

### CODE REVIEW

**Comment by memsharded** [comment]
@jgsogo the problem with this failing test is that ``sh.exe`` in the CI server is NOT in the path. So ``tools.which()`` or ``where`` doesn't find it. Adding ``sh.exe`` to the path in the server might break something? Should the test use an env-var just for this (seems overkill)?

**Comment by jgsogo** [comment]
I think it is ok if the CI populates some environment variables with paths to some tools. It will also help us to control the version of those tools being used: we can install several versions of CMake, for example, run by default with one version, but let the user configure it in Jenkins for a manual run.

**Comment by memsharded** [comment]
> I think it is ok if the CI populates some environment variables with paths to some tools.

Ok, good, I agree. As this is not an urgent thing, I am removing the milestone. This keeps open, pending to discuss a way to define such env-vars, where to put them, the defaults, etc.

**Comment by jgsogo** [comment]
I was proposing something like [this](https://github.com/conan-io/conan_ci_jenkins/pull/3/files#diff-7224ad2eab8bf4f80e90f5aaed64a401R1) for the docker images we use in our CI. They will populate the environment with the path to some useful stuff:
 * `Git.sh`
 * CMake default (we may want to have several versions installed)
 * ...

[.](https://github.com/conan-io/conan_ci_jenkins/pull/3)

**Comment by memsharded** [comment]
Obsolete, new ``Environment`` management.

**Pull request closed without merging**
