### PR TITLE
No longer hard-code major version of c++ compiler into include path f…

### PR DESCRIPTION
**Pull request by skizzay**
…or YCM generator

### CODE REVIEW

**Comment by memsharded** [comment]
Hi Andrew!

Nice to see you back :)

Your PR looks good, just a small observation, I think that getting the compiler version might fail (crash) when installing some conanfile that doesn't have that setting defined (like a header-only package). So I would recommend to protect the line:
```
cxx_version=str(self.settings.compiler.version).split('.')[0])
```
with some try-except.

Thanks!

**Comment by skizzay** [comment]
Thanks! :)

Would compiler be missing in those cases?  Or would it be version?  Depending on what's (not) available, I can have it try different paths and use fallbacks until it finds one that's useful.

**Comment by memsharded** [comment]
It might miss just the version, or the compiler too. It depends on the package declared settings. It would be unusual, in >95% of cases, the compiler.version will be there, so I would suggest just one try-except, keep it simple.

**Comment by memsharded** [comment]
Merged, will be in 0.25, thanks very much!

**Pull request merged**
