### PR TITLE
Test no warning for global output/requester in tools

### LINKED ISSUE #4468: Some tools still throw global instaces warnings
Reported in https://github.com/conan-community/community/issues/143

``tools.download()`` is using the global instance of ``output``

It would be nice to have this warnings polished in all tools (additionally in build helpers too).

### PR DESCRIPTION
**Pull request by danimtb**
Changelog: omit
Docs: omit

- [x] Refer to the issue that supports this Pull Request: closes #4468 

  Seems there was no real issue, as recipe was doing ``from conans.client import tools`` instead of ``from conans import tools``. However, I have done a general test of all tools checking the output.

### CODE REVIEW

**Comment by jgsogo** [comment]
_I'm not sure if I would add these tests, but given that you like them these are my two cents:_

In the future (Conan 2.0?), we are going to remove the warning and throw an error instead (the argument won't be defaulted to `None`) and these test will no longer be necessary. So, if we want to add these tests I will do it in a way that will force us to delete them once we make the change: we can check that if we import from `conans.client.tools` it prints the message and importing from `conans.tools` it doesn't, in the future the first one will fail and will invalidate this test.

For completeness:
 * I think that we should notice about new tools added to `conans.tools` and we can only do it traversing the module `conans.tools` and checking all the symbols imported against a fixed list that enumerates the tools that we are currently testing.
 * The argument `requester` has exactly the same problem, we should test it the same way

**Comment by jgsogo** [comment]
Better than this, I suggest just activating `warning-as-errors` for the test suite: https://github.com/conan-io/conan/issues/4527

**Comment by lasote** [comment]
Looks like the #4527 investigation from @jgsogo is looking good. As probably that is a good way to go I would close this PR. Maybe for next release @jgsogo can come up with the "warnings as errors" only for tests idea. What do you think @conan-io/barbarians ?

**Comment by danimtb** [comment]
Definitely the approach on #4527 is better and cover this case too. Closing this one.

**Pull request closed without merging**
