### PR TITLE
- add --no-install-recommends flag to apt-get

### PR DESCRIPTION
**Pull request by SSE4**
add --no-install-recommends to the AptTool, this will install less packages on system

### CODE REVIEW

**Comment by lasote** [comment]
And are we sure that the user never want to install the recommended ones?

**Comment by SSE4** [comment]
@lasote for build environment, it makes sense. most of Debian/Ubuntu docker files use that flag.
however, I can add option, if you think it's more appropriate.

**Comment by lasote** [comment]
@SSE4 Yes, we always try to not block a user, so I think we should make it optional (I agree to default it). The problem is, as user instances a `SystemPackageTool`, where to introduce it? in the constructor and only used in debian? Not very clean. @memsharded WDYT?

**Comment by SSE4** [comment]
@lasote added opt-out flag, pls review

**Comment by memsharded** [comment]
I am mostly fine with this, only that the argument should be renamed to something like "no_recommends", because now it seems to have the opposite meaning ``recommends=True`` => ``-no-install-recommends``

I am fine with it, even if it is not the cleanest approach to add it to the constructor, because I still think that a new approach of this tool is needed: https://github.com/conan-io/conan/issues/1659

**Comment by SSE4** [comment]
I don't think it's opposite meaning:
`recommends_str = '' if self._recommends else '--no-install-recommends '`
True -> empty
False -> no-install-recommends

**Comment by memsharded** [comment]
You are right, my mistake. I thought that the default had changed to opt-in, I just read too quickly the conversation.

So my only concern now is that the default recommend=False will change current behavior. Is it possible that someone is relying on some of the recommended packages and we will be breaking their builds because of this change?

**Comment by SSE4** [comment]
I highly doubt someone is relying on recommends. that's usually used to install *-dev packages, which are usually explicitly listed on library build instructions.

**Comment by memsharded** [comment]
> that's usually used to install *-dev packages

Yes, that is exactly my concern. Don't you think it is possible that someone is installing some package by its name, like ``sqlite``, or ``libpng`` or whatever, and they are actually getting the ``*-dev`` packages which in fact they need them to link with? I think it is likely.

**Comment by SSE4** [comment]
that doesn't seem to be the case. e.g. libpng is virtual package provided by libpng-dev, while sqlite doesn't recommend sqlite3-dev at all (while it recommends libsqlite3, which is runtime library, not development library). to summarize - no breakage in both cases.

**Comment by memsharded** [comment]
They were just examples, but yes, if those are typical behaviors, then I am fine with this.

**Pull request merged**
