### PR TITLE
#7503 Extend iOS versions

### LINKED ISSUE #7503: Extend iOS version in settings.yml
Hi, 

could you please update settings for iOS? The newest version in settings.yml for iOS is 13.1. From [here](https://en.wikipedia.org/wiki/IOS_version_history) you can see that there are newer versions. I have to use 13.2 and this is not problem to edit locally my settings.yml, but if I do it all my clients have to do the same work.

Br,
Tomasz

### PR DESCRIPTION
**Pull request by uilianries**
Add new iOS 13 minor version in default settings.yml

Changelog: Feature: Support from iOS 13.2 to 13.6.
Docs: https://github.com/conan-io/docs/pull/1800
closes #7503

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [x] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by uilianries** [comment]
Network error, not related to this PR. Restarting ...

**Review by jgsogo — CHANGES_REQUESTED** [review]
@uilianries You cannot modify the settings from an older version, you need to add at the bottom of `conans/client/migrations_settings.py` a new entry with the settings for 1.29.0:

```
settings_1_29_0 = """...."""
```

**Comment by uilianries** [comment]
:facepalm:

**Comment by uilianries** [comment]
@jgsogo Can we use template/jinja2 to avoid all this ugly copy/paste?

**Review by jgsogo — APPROVED** [review]

**Comment by jgsogo** [comment]
We need to figure out something, at least now we have some tests so we don't forget about the new settings. I would prefer to save _diffs_ (like Git, like database migrations,...) over a template, because we need to be able to reconstruct the _settings_ as they were when we released the corresponding version.

**Pull request merged**
