### PR TITLE
Conan2 logo

### PR DESCRIPTION
**Pull request by prince-chrismc**
Changelog: omit
Docs: omit

Add new logo with light and dark theme support
- followed https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

Same as the conan-io/docs#3080 to have as a preview

### Dark

image

### Light 

image

### CODE REVIEW

**Comment by AbrilRBS** [comment]
Maybe green in the light version for the JFrog logo?

**Comment by prince-chrismc** [comment]
I thinking full monochromatic but we can do Colored as well

**Comment by memsharded** [comment]
> Maybe green in the light version for the JFrog logo?

I agree, green would be a bit nicer, the black version seems too much for me, I'd appreciate some color (maybe for both light and dark, I think green would still be good on both)

**Comment by prince-chrismc** [comment]
I was thinking this

image

**Comment by prince-chrismc** [comment]
### Dark

image


### Light

image

**Comment by prince-chrismc** [comment]
Going full colored 

### Same as website

image

### Same as docs

image

**Review by memsharded — APPROVED** [review]
looking good, should we move this forward?

**Comment by prince-chrismc** [comment]
In my notes it's not clear what color we decided :) It currently looks like https://github.com/conan-io/conan/pull/13391#issuecomment-1462678340

Also this is in multiple places on GitHub so I am not sure if this is the best repository for the files. It's also here https://github.com/conan-io

Previously the files were hosted on the website https://conan.io/img/jfrog_conan_logo.png 😕

**Comment by prince-chrismc** [comment]
I also made https://github.com/conan-io/.github/pull/2 which references these ones but hopefully slightly less error prone 🤞 i put a comment :)

**Review by AbrilRBS — APPROVED** [review]

**Pull request merged**
