### PR TITLE
Add environment variable CONAN_DEFAULT_PROFILE to define path to default profile

### LINKED ISSUE #3193: Environment variable to set [general]default_profile
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

This idea was initially proposed at https://github.com/conan-io/conan/issues/1221#issuecomment-403961457

It would be nice if there was an environment variable (perhaps `CONAN_DEFAULT_PROFILE`?) which, if set, would override `[general]default_profile` from `conan.conf `. In an IDE workflow, a project file might be set up to obtain its own dependencies by calling `conan install` (e.g. https://github.com/conan-io/cmake-conan), but it feels wrong to hard-code a desired profile into the call to conan install. Most project systems like this support multiple configurations (e.g. Qt Creator has [kits](http://doc.qt.io/qtcreator/creator-configuring-projects.html), MSVC supports setting up multiple configurations. conan_cmake_settings(...) makes an effort to reverse-engineer the settings from the compiler detection variables, but it's not particularly complete, and in any case a sophisticated profile might have content (e.g. build_requires for toolchains) arguably could never get in this fashion. 

IDE features to define a build template like this usually have a mechanism to add environment variables to the build invocation, and a way to set the default profile through the environment seems consistent with the existing ability to override specific settings from it using [CONAN_ENV_XXXX_YYYY](https://docs.conan.io/en/latest/reference/env_vars.html#conan-env-xxxx-yyyy).

### PR DESCRIPTION
**Pull request by jgsogo**
close #3193

- [x] Docs needed: https://github.com/conan-io/docs/pull/849

Changelog: Feature: The environment variable `CONAN_DEFAULT_PROFILE_PATH` allows the user to define the path (absolute and existing) to the default profile that will be used by Conan.

### CODE REVIEW

**Comment by lasote** [comment]
1.8
Add the docs.

**Comment by jgsogo** [comment]
@lasote, is this expected behaviour?  `profile2` is not listed but it is shown:

```
(python3) MacBook-Pro-de-Javier:conan jgsogo$ CONAN_DEFAULT_PROFILE_PATH=/Users/jgsogo/dev/conan/conan/default2 conan profile list
default
default.old
gcc49

(python3) MacBook-Pro-de-Javier:conan jgsogo$ CONAN_DEFAULT_PROFILE_PATH=/Users/jgsogo/dev/conan/conan/default2 conan profile show default2
Configuration for profile default2:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=9.1
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]

```

**Comment by danimtb** [comment]
@jgsogo  Conan help output seems OK with the behavior of ``conan profile list``:

```
λ conan profile --help
usage: conan profile [-h] {list,show,new,update,get,remove} ...

Lists profiles in the '.conan/profiles' folder, or shows profile details. The
'list' subcommand will always use the default user 'conan/profiles' folder.
But the 'show' subcommand is able to resolve absolute and relative paths, as
well as to map names to '.conan/profiles' folder, in the same way as the '--
profile' install argument.

positional arguments:
  {list,show,new,update,get,remove}
    list                List current profiles
    show                Show the values defined for a profile
    new                 Creates a new empty profile
    update              Update a profile with desired value
    get                 Get a profile key
    remove              Remove a profile key

optional arguments:
  -h, --help            show this help message and exit
```

However the second output seems weird to me. Are you sure your ``default2`` profile is not in the current working dir?

**Comment by jgsogo** [comment]
You are completely right, @danimtb. ``default2`` profile was in my working directory.

**Pull request merged**
