### PR TITLE
#6301 virtualenv from win to unix paths fix

### PR DESCRIPTION
**Pull request by kucerad**
Changelog: (Bugfix): Fixing the virtual env paths export in Windows to Unix .sh files
Docs: https://github.com/conan-io/docs/pull/XXXX

-  https://github.com/conan-io/conan/issues/6301
- fixes the #6301 issue

### CODE REVIEW

**Comment by jgsogo** [comment]
Hi, @kucerad , thanks a lot for the PR! I think that the `read -r` will be the way to go, so please, accept the CLA to move forward this changes (on the other hand, I'm working in #6308 trying to provide tests for our CI related to this bugfix, the idea will be to merge those tests into your PR and merge this one) 👍

**Comment by kucerad** [comment]
@jgsogo How do I make the license/cla to update? I've accepted it but it still doesn't update here in the PR...

**Comment by jgsogo** [comment]
Maybe it is a matter of time to get the update from the cla-assistant, let's wait a little bit. 

Meanwhile, is it needed to fix the slashes? I've been trying it (using the GNU bash installed with Git in Windows) and it works without that functions. Does it fail for you without those functions?

**Comment by jgsogo** [comment]
The problem with the CLA is user @ak185319, which is the actual author of the commits. You can follow the instructions in the CLA message (https://github.com/conan-io/conan/pull/6306#issuecomment-571622461), or you can open a new PR with those changes.

After that, I'll push to your branch the test I have already running in #6308

**Comment by kucerad** [comment]
@jgsogo well... I haven't tested, but since backslash is used as escape character in unix systems - how would you then handle that? We'd be able to export the string of "\newline\return\tab.txt", but the usage - what would make the consumer to find-out, that the '\n', '\r', '\t' should / shouldn't be escaped ? Proper way to represent paths in Unix is to use standard slash '/' - Conan should respect that...

**Comment by jgsogo** [comment]
Yes, I know, but it looks like shells running in Windows are able to handle paths properly. This is what I see in my own machine, in the tests in our CI and also it is commented here (https://github.com/conan-io/conan/issues/6301#issuecomment-571678133). So, if there is no evidence that this change is needed, we prefer to keep it untouched.

**Comment by kucerad** [comment]
ok, created new PR (https://github.com/conan-io/conan/pull/6314)

**Pull request closed without merging**
