### PR TITLE
Feature: Premake generator

### LINKED ISSUE #3693: Making premake generator built-in
There seems to be new interest in premake: https://github.com/conan-io/wishlist/issues/162

I think making the generator in https://github.com/memsharded/conan-premake built-in, would be useful.

Also, some open-source library package might need it: https://github.com/bincrafters/community/issues/474

To be discussed.

### PR DESCRIPTION
**Pull request by SSE4**
closes #3693 

uses premake generator from https://github.com/memsharded/conan-premake

Changelog: Feature: New `premake` generator incorporated to the Conan code base from the external generator at https://github.com/memsharded/conan-premake.

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [x] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one.

### CODE REVIEW

**Comment by SSE4** [comment]
seems to be infrastructure failure 
```python: can't open file '.ci/jenkins/runner.py': [Errno 2] No such file or directory```

**Comment by SSE4** [comment]
I've played a bit with it, and some thoughts: 

- it's probably worth to add multi-configuration packages support, just like qmake has
- it also worth providing `premake_multi` generator in addition to the `premake` (same way as `visual_studio_mutli` and `cmake_multi`)
- finally, it might be worth providing `conan_basic_setup` function/macro to automatically set all flags

**Comment by danimtb** [comment]
I think those are good ideas and would be helpful for premake users. I will keep them open in an issue and see if there is more feedback from people using it whne the generator is released. WDYT @SSE4 ?

**Comment by SSE4** [comment]
yes, let's keep them for a while, until there is a real demand for them. I am not a premake user, so it's hard to judge for me.

**Pull request merged**
