### PR TITLE
adds tests for virtualenv generator and fixes export inconsistency

### PR DESCRIPTION
**Pull request by niosHD**
As announced in #2556 this PR adds a simple test for the virtualenv generator and fixes the inconsistency regarding the export command. Given these tests, I will implement #2568 next. A little heads up, while doing so I will refactor the whole virtualenv generator which is very messy at the moment.

### CODE REVIEW

**Comment by niosHD** [comment]
Ok, this PR is in good shape now and can be reviewed. I used two commits to reflect the different work packages that have been implemented. Commit 4f67874 adds tests and fixes the export inconsistency that has been discussed in #2556. Commit d4d2428 rewrites the generator to be more consistent regarding formatting and should be easier to read and extend.

In summary, the following changes have been made to the output of the generator in this PR:

* [ps1] The current value is now directly concatenated into the value instead appended afterwards. (same as cmd and sh)
* [sh] `export` is now always used as separated command.
* [sh] The entries in the deactivate script are now quoted.
* [sh] The PS1 and OLD_PS1 values are now restored during deactivate in the same way as all other variables.
* The deactivate scripts now restore the current value also for variables that are fully replaced in the activate script.

Regarding #2568, the verdict of the discussion was more or less that it is sufficient to generate the sh files on Windows when conan is used from the MSYS/cygwin `bash`. This is implemented in this PR by gating the sh file generation behind a (admittedly imprecise) `is_posix` condition. The cmd and ps1 files on the other hand are not generated in this environment because they would not contain sensible paths anyway.

Best,
Mario

**Comment by memsharded** [comment]
This has quite a few interesting things, so this should be reviewed. Planning it for 1.4, though I will try to review it sooner if possible.

Thanks for the contribution!

**Comment by niosHD** [comment]
You are welcome! A small warning though, the behavior requested in #2568 has to be re-evaluated based on the information I collected in #2638. Namely, the used `is_posix` check only works for the msys subsystem that I used during development. More work is required to generalize the behavior. Anyway, a review and some guidance on how to proceed is greatly appreciated.

**Comment by lasote** [comment]
Hi, I've been reviewing this a little, and as there are some issues pending like the subsystems stuff I think we are finally assigning 1.4. 
I've merged the PR https://github.com/conan-io/conan/pull/2798 but for native conan running in a subsystem (msys or cygwin) a couple of more things should be done. 
Could you in the meantime check the PEP8 style of this PR? I see missing spaces in lists and things like that.
Thanks!

**Comment by danimtb** [comment]
Hi @niosHD 

I know it has been a long time with this PR open and finally we run out of time to merge it for 1.4 an we have already many features. I will review this as first priority for 1.5

Thanks for understanding

**Comment by danimtb** [comment]
Hi @niosHD,

I have opened a PR updated with develop to your branch with some minor changes. Could you please check it?

Thanks

**Comment by niosHD** [comment]
@danimtb Done. I rebased my two commits and your rework commit on top of conan develop.

**Comment by danimtb** [comment]
@niosHD I have opened a new PR #3001 with your changes that fixes the test for our CI environment. I have kept your changes in the history to preserve you authorship. I will be reviewed for next 1.5 release. Thank you!

**Comment by memsharded** [comment]
This has been merged together with the https://github.com/conan-io/conan/pull/3001 pull request.

Thanks very much for this great contribution!

**Pull request closed without merging**
