### PR TITLE
Feature/search table styles

### PR DESCRIPTION
**Pull request by lasote**
Changelog: Feature: Use Bootstrap in search table template style.
Docs: omit

Added bootstrap and adjusting some styles for better visualization. Try it on my branch and let me know if you like it.

### CODE REVIEW

**Comment by lasote** [comment]
image

**Review by memsharded — APPROVED** [review]
There are a couple of minor glitches, like "Visual Studio" doing a line break, which makes row height double. But I like the improvement, looks better.

**Comment by lasote** [comment]
I only see "visual studio" split when the window is not big enough. Screenshot? Which browser?

**Comment by jgsogo** [comment]
We can recover the CSS `white-space:nowrap;` property to those cells in the table.

**Comment by lasote** [comment]
done

**Pull request merged**
