### PR TITLE
fix cwd issues in set_version() evaluation

### PR DESCRIPTION
**Pull request by memsharded**
Changelog: Bugfix: Make sure ``set_version()`` runs in the ``conanfile.py`` folder, not in the current folder, so relative paths are not broken if executing from a different location.
Docs: https://github.com/conan-io/docs/pull/1490

Close: #6129

### CODE REVIEW

**Comment by memsharded** [comment]
> I'm aware about the python-requires issue, but it can be worked around passing the os.path.dirname(__file__) to the function

That is part of the issue, we don't want to have a custom method/function, we want to inherit the ``set_version()`` method, and you cannot pass arguments to it. Take into accounts that python_requires are going to be move to a declarative interface, where the module is no longer available at recipe parse time.

**Comment by jgsogo** [comment]
IMO it is never a good idea to change the _current-working-folder_. Why not use the same strategy as we do for the `source_folder` or the `build_folder` and provide a `xxxxx_folder` which is the path to the folder where the recipe being built is located? It would fulfill the requirement too.

**Comment by memsharded** [comment]
> IMO it is never a good idea to change the current-working-folder. Why not use the same strategy as we do for the source_folder or the build_folder and provide a xxxxx_folder which is the path to the folder where the recipe being built is located? It would fulfill the requirement too.

Conan already changes the working directory for other methods, like ``source()``, ``build()`` and ``package()``. This is nothing new, has been there since always.

For a python_require, it is not possible to use something like:

```python
def set_version(self):
     self.version = load(os.path.join(self.recipe_folder, "version.txt")
```

Because that ``self.recipe_folder`` would still be the folder of the python_require, not the consumer of the python_require. Python requires are shared among their consumers too.

I still need to figure out a use case in which the result of ``conan export`` or ``conan create`` will be different depending on your current location. As I see it, the behavior of the recipe should be completely invariant, the result should always be the same if you do ``conan export pkg_folder``, or ``conan export .`` or ``conan export path/to/myconanfile.py``. If you want to inject version information from the outside of the recipe, you should probably skip the ``set_version()`` method and use ``conan export <path> version@user/channel`` form.

**Comment by jgsogo** [comment]
> > IMO it is never a good idea to change the current-working-folder. Why not use the same strategy as we do for the source_folder or the build_folder and provide a xxxxx_folder which is the path to the folder where the recipe being built is located? It would fulfill the requirement too.
> 
> Conan already changes the working directory for other methods, like `source()`, `build()` and `package()`. This is nothing new, has been there since always.
> 

It doesn't mean it is a good idea to do it.

I don't come across many recipes with `os.getcwd()` ([zero matches in `conan-center-index`](https://github.com/conan-io/conan-center-index/search?q=os.getcwd&unscoped_q=os.getcwd)) and I find many with things like `self.souce_folder` or `self.build_folder`.

> For a python_require, it is not possible to use something like:
> 
> ```python
> def set_version(self):
>      self.version = load(os.path.join(self.recipe_folder, "version.txt")
> ```
> 
> Because that `self.recipe_folder` would still be the folder of the python_require, not the consumer of the python_require. Python requires are shared among their consumers too.
> 

The `self.recipe_folder` should be the folder of the package being built, exactly the same as the `self.source_folder` or the `slef.build_folder`. If we use a `python_requires` like:

```python

# Here it goes my python_requires recipe
class MyRecipe(ConanFile):
    ...

def get_conanfile():
    class BaseConan(ConanFile):

        def build(self):
            .... os.path.join(self.build_folder, "CMakeLists.txt")
```

it will use the `build_folder` of the package being built, it won't raise because a `python_requires` doesn't have the concept of _build_ or _package_ or _binaries_... and the `build_folder` doesn't make sense for it. 


> I still need to figure out a use case in which the result of `conan export` or `conan create` will be different depending on your current location. As I see it, the behavior of the recipe should be completely invariant, the result should always be the same if you do `conan export pkg_folder`, or `conan export .` or `conan export path/to/myconanfile.py`. If you want to inject version information from the outside of the recipe, you should probably skip the `set_version()` method and use `conan export <path> version@user/channel` form.

Totally agree, but let's do it with an explicit attribute that always has the same value rather than with a `os.getcwd()` call that returns different values depending on where it is written. That's my only point.

----

Full picture: explicit, no current working directory, lovely 😄 

```python

class MyRecipe(ConanFile):
    ...

def get_conanfile():

    class BaseConan(ConanFile):

        def set_version(self):
             self.version = load(os.path.join(self.recipe_folder, "version.txt")

        def build(self):
            .... os.path.join(self.build_folder, "CMakeLists.txt")


```

**Comment by memsharded** [comment]
Yes, I see the value of ``self.version = load(os.path.join(self.recipe_folder, "version.txt")``, lets make a decision @lasote to see if possible for 1.21

**Comment by memsharded** [comment]
Last changes contain the ``self.recipe_folder`` solution, but can be reverted if decided otherwise.

**Pull request merged**
