### PR TITLE
Build policy in conanfile

### PR DESCRIPTION
**Pull request by lasote**

### CODE REVIEW

**Comment by memsharded** [comment]
I like the idea and the approach with both missing and always. Just one detail, probably for policy=always, conan upload binaries should throw an error.

**Comment by lasote** [comment]
Updated PR with the upload check.

**Comment by memsharded** [comment]
Much better, thanks. I am reviewing some flows for conan install --update of these packages, I have some doubts.

**Comment by memsharded** [comment]
Merged, it is fine. I am checking the --update from develop, I will submit a new PR if necessary.

**Pull request merged**
