### PR TITLE
Print package folder when installing

### LINKED ISSUE #4543: [feature] package path in (console) output
hi there,
while developing serval conan recipes (which are inter-dependent) where I have to put something like the following

recipe:
```python
def package_info(self):
    self.output.info(f"providing cpp_info.rootpath: {self.cpp_info.rootpath}")
```
output:
```
package_name/version@user/channel: providing cpp_info.rootpath: C:\.conan\4eee01\1
```
into the recipe even if it does not need any custom ```package_info``` function. The reason is that this protocols the package source and I can quickly see where and what Conan actually uses as sources for CMake etc. and what is really available, in case I something went wrong with the compilation.

It is no big deal that I put the line above into every recipe by myself but this could be automated :).

Best regards

### PR DESCRIPTION
**Pull request by uilianries**
I'll wait for code review before updating the docs.

Real example, Folly:

```
conan install folly/2019.05.27.00@bincrafters/testing

Installing package: folly/2019.05.27.00@bincrafters/testing
Requirements
    OpenSSL/1.0.2r@conan/stable from 'conan-center' - Cache
    boost/1.67.0@conan/stable from 'conan-center' - Cache
    bzip2/1.0.6@conan/stable from local cache - Cache
    double-conversion/3.1.1@bincrafters/stable from 'conan-center' - Cache
    folly/2019.05.27.00@bincrafters/testing from local cache - Cache
    gflags/2.2.1@bincrafters/stable from 'conan-center' - Cache
    glog/20181109@bincrafters/stable from 'conan-center' - Cache
    libaio/0.3.111@bincrafters/stable from 'bincrafters' - Cache
    libdwarf/20190505@bincrafters/stable from local cache - Cache
    libelf/0.8.13@bincrafters/stable from 'conan-center' - Cache
    libevent/2.1.8@bincrafters/stable from 'conan-center' - Cache
    libiberty/9.1.0@bincrafters/stable from 'bincrafters' - Cache
    libsodium/1.0.16@bincrafters/stable from 'conan-center' - Cache
    libunwind/1.3.1@bincrafters/stable from local cache - Cache
    lz4/1.8.3@bincrafters/stable from 'conan-center' - Cache
    lzma/5.2.4@bincrafters/stable from 'conan-center' - Cache
    snappy/1.1.7@bincrafters/stable from 'conan-center' - Cache
    zlib/1.2.11@conan/stable from local cache - Cache
    zstd/1.3.5@bincrafters/stable from 'conan-center' - Cache
Packages
    OpenSSL/1.0.2r@conan/stable:444d1eb978f872e0f5e5a1a07145f79c475221ca - Missing
    boost/1.67.0@conan/stable:57a43be2869705613cd56abb91df4009d1998f69 - Missing
    bzip2/1.0.6@conan/stable:6af9cc7cb931c5ad942174fd7838eb655717c709 - Cache
    double-conversion/3.1.1@bincrafters/stable:b911f48570f9bb2902d9e83b2b9ebf9d376c8c56 - Missing
    folly/2019.05.27.00@bincrafters/testing:d59c28824bec2a593eadb41d3e4bdbce7c74e562 - Missing
    gflags/2.2.1@bincrafters/stable:21e1281916d3adf618b3bd57f3098f62f2674fd4 - Missing
    glog/20181109@bincrafters/stable:92f46611daf4fc8eae13b7228a9f2af28e669727 - Missing
    libaio/0.3.111@bincrafters/stable:6af9cc7cb931c5ad942174fd7838eb655717c709 - Missing
    libdwarf/20190505@bincrafters/stable:d087edc6b26646b3221356ac5df4f513da0aca47 - Missing
    libelf/0.8.13@bincrafters/stable:6af9cc7cb931c5ad942174fd7838eb655717c709 - Missing
    libevent/2.1.8@bincrafters/stable:978915c91c83af111dbac8be0361cd8839126326 - Missing
    libiberty/9.1.0@bincrafters/stable:6af9cc7cb931c5ad942174fd7838eb655717c709 - Missing
    libsodium/1.0.16@bincrafters/stable:6af9cc7cb931c5ad942174fd7838eb655717c709 - Missing
    libunwind/1.3.1@bincrafters/stable:c872285be6c1c0b7b07f69b8a36c8e301404ce8e - Missing
    lz4/1.8.3@bincrafters/stable:6af9cc7cb931c5ad942174fd7838eb655717c709 - Missing
    lzma/5.2.4@bincrafters/stable:6af9cc7cb931c5ad942174fd7838eb655717c709 - Download
    snappy/1.1.7@bincrafters/stable:b911f48570f9bb2902d9e83b2b9ebf9d376c8c56 - Missing
    zlib/1.2.11@conan/stable:6af9cc7cb931c5ad942174fd7838eb655717c709 - Cache
    zstd/1.3.5@bincrafters/stable:6af9cc7cb931c5ad942174fd7838eb655717c709 - Missing
Package Folders
    OpenSSL/1.0.2r@conan/stable: /home/uilian/.conan/data/OpenSSL/1.0.2r/conan/stable/package/444d1eb978f872e0f5e5a1a07145f79c475221ca
    boost/1.67.0@conan/stable: /home/uilian/.conan/data/boost/1.67.0/conan/stable/package/57a43be2869705613cd56abb91df4009d1998f69
    bzip2/1.0.6@conan/stable: /home/uilian/.conan/data/bzip2/1.0.6/conan/stable/package/6af9cc7cb931c5ad942174fd7838eb655717c709
    double-conversion/3.1.1@bincrafters/stable: /home/uilian/.conan/data/double-conversion/3.1.1/bincrafters/stable/package/b911f48570f9bb2902d9e83b2b9ebf9d376c8c56
    folly/2019.05.27.00@bincrafters/testing: /home/uilian/.conan/data/folly/2019.05.27.00/bincrafters/testing/package/d59c28824bec2a593eadb41d3e4bdbce7c74e562
    gflags/2.2.1@bincrafters/stable: /home/uilian/.conan/data/gflags/2.2.1/bincrafters/stable/package/21e1281916d3adf618b3bd57f3098f62f2674fd4
    glog/20181109@bincrafters/stable: /home/uilian/.conan/data/glog/20181109/bincrafters/stable/package/92f46611daf4fc8eae13b7228a9f2af28e669727
    libaio/0.3.111@bincrafters/stable: /home/uilian/.conan/data/libaio/0.3.111/bincrafters/stable/package/6af9cc7cb931c5ad942174fd7838eb655717c709
    libdwarf/20190505@bincrafters/stable: /home/uilian/.conan/data/libdwarf/20190505/bincrafters/stable/package/d087edc6b26646b3221356ac5df4f513da0aca47
    libelf/0.8.13@bincrafters/stable: /home/uilian/.conan/data/libelf/0.8.13/bincrafters/stable/package/6af9cc7cb931c5ad942174fd7838eb655717c709
    libevent/2.1.8@bincrafters/stable: /home/uilian/.conan/data/libevent/2.1.8/bincrafters/stable/package/978915c91c83af111dbac8be0361cd8839126326
    libiberty/9.1.0@bincrafters/stable: /home/uilian/.conan/data/libiberty/9.1.0/bincrafters/stable/package/6af9cc7cb931c5ad942174fd7838eb655717c709
    libsodium/1.0.16@bincrafters/stable: /home/uilian/.conan/data/libsodium/1.0.16/bincrafters/stable/package/6af9cc7cb931c5ad942174fd7838eb655717c709
    libunwind/1.3.1@bincrafters/stable: /home/uilian/.conan/data/libunwind/1.3.1/bincrafters/stable/package/c872285be6c1c0b7b07f69b8a36c8e301404ce8e
    lz4/1.8.3@bincrafters/stable: /home/uilian/.conan/data/lz4/1.8.3/bincrafters/stable/package/6af9cc7cb931c5ad942174fd7838eb655717c709
    lzma/5.2.4@bincrafters/stable: /home/uilian/.conan/data/lzma/5.2.4/bincrafters/stable/package/6af9cc7cb931c5ad942174fd7838eb655717c709
    snappy/1.1.7@bincrafters/stable: /home/uilian/.conan/data/snappy/1.1.7/bincrafters/stable/package/b911f48570f9bb2902d9e83b2b9ebf9d376c8c56
    zlib/1.2.11@conan/stable: /home/uilian/.conan/data/zlib/1.2.11/conan/stable/package/6af9cc7cb931c5ad942174fd7838eb655717c709
    zstd/1.3.5@bincrafters/stable: /home/uilian/.conan/data/zstd/1.3.5/bincrafters/stable/package/6af9cc7cb931c5ad942174fd7838eb655717c709

```

Changelog: Feature: Print package folder when installing
Docs: TODO
closes #4543

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

### CODE REVIEW

**Comment by uilianries** [comment]
> I'm not sure I like that output to appear always

We could add an env var/config like CONAN_SHOW_PACKAGE_FOLDER.

>  About this PR, you miss a test using short paths.

Good catch!

**Comment by memsharded** [comment]
Hi @uilianries 

I am having a second look to this, and to my previous comments in https://github.com/conan-io/conan/issues/4543. It seemed right at that moment, but the truth is that your PR and the example output is eye-opening.

I think this feature is adding too much extra information to the output, that will be mostly useless/irrelevant to most users. While the previous information is fine, as it provides relevant information, like the remote it comes from, or the binary ID, and the "expected" action over that ID (missing, build, download), the package folder is irrelevant in most cases. If everything works fine, and it should in most cases, the package folder is irrelevant. Even in cases that something fails, it might help or not. 

Besides, we already have a feature to show the path in case it is necessary for debugging, and actually not only the package path, but others:

```bash
conan info zlib/1.2.11@conan/stable --paths
zlib/1.2.11@conan/stable
    ID: 6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
    BuildID: None
    export_folder: C:\Users\memsharded\.conan\data\zlib\1.2.11\conan\stable\export
    source_folder: C:\Users\memsharded\.conan\data\zlib\1.2.11\conan\stable\source
    build_folder: C:\Users\memsharded\.conan\data\zlib\1.2.11\conan\stable\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
    package_folder: C:\Users\memsharded\.conan\data\zlib\1.2.11\conan\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
    Remote: conan-center=https://conan.bintray.com
    URL: http://github.com/conan-community/conan-zlib
    Homepage: https://zlib.net
    License: Zlib
    Author: Conan Community
    Recipe: Cache
    Binary: Download
    Binary remote: conan-center
    Creation date: 2019-06-21 10:50:37
```

This is even intended to be able to generate a json file if requested, that could be read by tools. So having this mechanism in place for exactly this use case, showing the output in every install, seems too much output for the value.

I vote for closing this PR, and the related issue pointing to that ``conan info`` suggestion.

**Comment by uilianries** [comment]
At least I've learned how to extract package folder from a reference 🤓 

Anyway, I agree. It sounds a bit duplicated with `conan info --path`. Of course, this feature is more verbose because it lists all packages related.

**Comment by uilianries** [comment]
@lasote could you please close https://github.com/conan-io/conan/issues/4543 ?

**Pull request closed without merging**
