### PR TITLE
- add toolset parameter to CMake helper

### PR DESCRIPTION
**Pull request by SSE4**
allow to specify custom toolset for CMake generator, mainly feature is targeted for Visual Studio generators, although there might be other generators supporting it, I just don't know em 
* one use case is to use Clang based toolset (such as LLVM one or Microsoft Clang/C2)
* another use case is to use toolsets with Windows XP support (e.g. v140_xp)
* Windows Driver Kit has its own toolset as well (not sure if any driver developers use conan btw)
* Intel compiler is another one (although not supported by Conan yet)

### CODE REVIEW

**Comment by skizzay** [comment]
:+1:

**Comment by lasote** [comment]
My question is, should it be modeled in the settings and automatically applied by the helper? If you specify the toolset v140_xp you are actually getting a different binary. Probably it's ok to keep it open but I'm wondering if we are missing real use cases not modeled with the current conan default settings.

**Comment by SSE4** [comment]
@lasote 
as for Windows development and XP support in particular, I guess **os_version** setting shall be added, because you could target different minimal OS requirements, and will be able to use only WinAPI certain functions.
MSDN [documents](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383745(v=vs.85).aspx) the process.
you basically will need to define a bunch of preprocessor definitions (such as NTDDI_VERSION, _WIN32_WINNT and WINVER). you also have to use corresponding tool-chain (regular or XP one).
same story applies to Mac OS, where you have **-mmacosx-version-min** macro and different SDKs for different OS versions.
Linux is different story, glibc version applies here.

for my personal use-case, I am currently building with Clang on Windows, and I just need ability to set toolchain **llvm-vs2014** for CMake.

**Comment by lasote** [comment]
And for your use case with Clang, what settings values are you specifying?

**Comment by SSE4** [comment]
-s os=Windows -s compiler=Clang -s compiler.version=5.0 -s compiler.libcxx=libc++
libc++ is dummy one just to silence the error (I believe new value is needed for MSVC stdlib)

**Comment by lasote** [comment]
I see. I'm ok with the PR. What do you think @memsharded?  Should we model the win clang somehow?

**Comment by memsharded** [comment]
I am fine with this PR, but we need to advance in the settings and common automation use cases. The ``CMake.toolset`` could be automatically deduced from the settings, if we manage to define something reasonable for clang in Win.

**Pull request merged**
