### PR TITLE
Feature: Prettify generated bazel files

### PR DESCRIPTION
**Pull request by Neeeflix**
Feature: Prettifies the generated bazel-files

**Actual changes**:
* Adding line-breaks between the list elements in define and linkopts
* Adding appropriate test-cases

- [ ] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one.

### CODE REVIEW

**Review by franramirez688 — COMMENTED** [review]
Hi @Neeeflix 

Thanks a lot for contributing!
It's great to see that you're interested in improving these, but let me point to a couple of thoughts:
* I'm working on improving the whole integration with Bazel ([Bazel + BazelToolchain](https://github.com/conan-io/conan/pull/14845) + [BazelDeps](https://github.com/conan-io/conan/pull/14880)), so I recommend you wait for it because of future conflicts.
* Bazel does not have a good battery of tests, so that makes me a bit careful in merging many more changes in Bazel before improving that part 😓 

Apart from that, we should always start opening new feature branches from `release/2.0`. PRs to Conan 1.x develop branch are welcome for sure, but we're actively trying to get Conan 2.x more and more robust, and all the new features should be there. Only critical/security glitches should point directly to Conan 1.x.

Again, thanks a lot for your efforts, it's highly appreciated, but let's wait a little bit to see all the upcoming changes 😄

**Comment by Neeeflix** [comment]
> Hi @Neeeflix 
> 
> 
> 
> Thanks a lot for contributing!
> 
> It's great to see that you're interested in improving these, but let me point to a couple of thoughts:
> 
> * I'm working on improving the whole integration with Bazel ([Bazel + BazelToolchain](https://github.com/conan-io/conan/pull/14845) + [BazelDeps](https://github.com/conan-io/conan/pull/14880)), so I recommend you wait for it because of future conflicts.
> 
> * Bazel does not have a good battery of tests, so that makes me a bit careful in merging many more changes in Bazel before improving that part 😓 
> 
> 
> 
> Apart from that, we should always start opening new feature branches from `release/2.0`. PRs to Conan 1.x develop branch are welcome for sure, but we're actively trying to get Conan 2.x more and more robust, and all the new features should be there. Only critical/security glitches should point directly to Conan 1.x.
> 
> 
> 
> Again, thanks a lot for your efforts, it's highly appreciated, but let's wait a little bit to see all the upcoming changes 😄
> 
> 

Hey @franramirez688,

Thanks for the quick reply.

Also some thoughts/questions from my end:
- As I understood you, you are doing your changes only for 2.X. Wouldn't it be okay if I bring my changes to 1.x then? Still might be useful for users which are not being able to migrate to 2.X soon
- Does it then may make sense when I focus on improving the test system, could be also used for your changes then. Or can we expect some intereference there as well?
- Also do you have a branch containing your changes? I would be highly interested. 
  - Maybe some background information: I am already using some adapted version of the generator and currently trying to bring some of the things I learned back to here.

**Comment by memsharded** [comment]
Quick note about 1.X and 2.0 development: The ``develop`` branch is merged periodically to ``release/2.0``. It means that independent development of both will be problematic in terms of conflicts. Development should be focused on 1 of both branches, then merged forward or backported.

Build system integrations are good to be done in 1.X as long as they are not breaking. If they are very breaking for 1.X, then we can consider other alternatives.

**Comment by franramirez688** [comment]
Hi @Neeeflix, sorry for the delay in replying to your comments, and thank you for your comments.

> * As I understood you, you are doing your changes only for 2.X. Wouldn't it be okay if I bring my changes to 1.x then? Still might be useful for users which are not being able to migrate to 2.X soon

Indeed, we could consider these changes to Conan 1.x. So, let's solve the conflicts for this branch, and we can start reviewing the PR.

> * Does it then may make sense when I focus on improving the test system, could be also used for your changes then. Or can we expect some intereference there as well?

It could be good to wait a bit to avoid wasting time adapting the new tests, but it's great to hear that. Thanks a lot!

> * Also do you have a branch containing your changes? I would be highly interested.

Sure! I'm so close to finishing the BazelDeps refactor, but the https://github.com/conan-io/conan/pull/14845 is under review, so I think it could be about to change more.

Bazel + BazelToolchain -> https://github.com/conan-io/conan/pull/14845
BazelDeps -> https://github.com/conan-io/conan/pull/14880

**Comment by Neeeflix** [comment]
> Indeed, we could consider these changes to Conan 1.x. So, let's solve the conflicts for this branch, and we can start reviewing the PR.

@franramirez688 done. Thanks.

**Comment by Neeeflix** [comment]
> Quick note about 1.X and 2.0 development: The `develop` branch is merged periodically to `release/2.0`. It means that independent development of both will be problematic in terms of conflicts. Development should be focused on 1 of both branches, then merged forward or backported.
> 
> Build system integrations are good to be done in 1.X as long as they are not breaking. If they are very breaking for 1.X, then we can consider other alternatives.

@memsharded can I target a different branch then for the 1.X release?

**Comment by Neeeflix** [comment]
Ping @memsharded, @franramirez688

**Comment by franramirez688** [comment]
Hi @Neeeflix 

Thanks for the ping!

It seems my branch https://github.com/conan-io/conan/pull/14880 solves that problem (needs more testing). Apart from that, we plan to point directly to the next Conan 1.x version. I need more time to push all the changes with their tests to see the result. I'll ping you when I have everything.

**Pull request closed without merging**
