### PR TITLE
[SCM] Capture branch and commit with `tools.Git`

### LINKED ISSUE #3052: [SCM][revisions] Supporting the `scm revsion` as package `version`
Disclaimer: I discussed this issue on Slack and post it now here to keep track of it. Thank you @lasote for the great discussion!

Problem
-------
I currently have several recipes which "manually" capture the git revision based on [James' idea](https://github.com/memsharded/sourcegit/blob/master/conanfile.py) when exporting/creating the package. Given that conan now has `scm` support I want to get rid of my custom code and use the upstream feature instead.

However, the way I use my `scm revision` is apparently not supported by the current `scm` implementation. Namely, when building packages from the development branch, I directly use the `scm revision` as package `version`. See https://gist.github.com/niosHD/dc669dcb6c8d92b51e3d9c6bab774e90 for a sketch of one of my conanfiles.

Background
----------
My reasoning on why I want to use the `scm revision` as `version` in non-release packages is as follows. For me a version should uniquely identify a package. However, version numbers are only assigned when a release is made. Subsequently, non-release builds (e.g., CI, builds on the developer machine of a certain feature branch, ...) typically have no real `version`.

Sill, as conan really needs a `version`, some kind of version has to be generated. This can either be done by generating a new unique version (e.g., something like a build number) or by using some arbitrary fixed string (e.g., branch name, the next expected version as working title, ...) which results in continuously replacing the package. (Note that `package revisions` will dramatically improve the usefulness/reproducibility of the second option.)

We opted for the first approach since it enables us to also package/test/distribute non-release versions in a reproducible way via conan. However, instead of generating an arbitrary build number, which again does not directly convey what has been packaged, we use the `scm revision` which states exactly what is in the respective package.

Given this approach, we basically then use two types of dependency management. The first one is similar to a git submodule approach where a very specific `(scm) version` is required by a package. An example for such a dependency is `clang`'s dependency on `llvm` where both repositories are typically always incremented in lockstep. Using the `scm version` as package `version` enables us to easily manage these kind of dependencies. Of course CI builds are used to verify that we get working results.

The second dependency type is more dynamic. For some libraries, where the API is more or less stable, we simple want to depend on the latest sucessfully CI tested version of this library (in a certain git branch). There we use conan's package alias, which gets updated by our CI server after each successful build, with the branch name as version. The using such an alias target is then done requiring `libfoo/develop@...` or `libfoo/feature-x@...` (we use gitflow on some projects) and means that the actually used version depends on the build time of the consuming package. However, given that the alias packages are transparently resolved, the resulting package is still fully reproducible and records the actual versions. Furthermore, CI is used again to ensure that we get working results anyway.

### PR DESCRIPTION
**Pull request by lasote**
- [x] Refer to the issue that supports this Pull Request. Closes #3052

Pending docs and @niosHD validation

### CODE REVIEW

**Comment by niosHD** [comment]
Thank you very much! I tested this PR on one of my repositories in combination with the scm module and the general approach seems to work. However, I have some observations/remarks that may be of interest for you.

1. `Git.get_branch()` returns a "bogus" branch name. In my test repository, the branch is currently called `feature/residue`, it tracks `origin/feature/residue`, and `get_branch()` returns `feature/residue...origin/feature/residue`. I would expect to get `feature/residue` which still has to be sanitized before it is usable as version (e.g., replace all non alphanumeric characters).
2. Git's error message (i.e., `fatal: Not a git repository...`), is shown when the recipe is used inside the cache (e.g., during `conan create`). I think that we can suppress these kind off errors as we actually expect them to happen.

Best,
Mario

P.S. For completeness, my test system uses Ubuntu 16.04 and has git version 2.7.4.

**Comment by lasote** [comment]
Thanks for the feedback!

**Comment by lasote** [comment]
Review again.

**Comment by lasote** [comment]
Hi @niosHD, we realized that the `branch = re.sub('[^0-9a-zA-Z]+', '_', branch)` that is performed in the `get_branch()` shouldn't be there. Because one thing is getting the current branch from a Git repository and a different one clean it up to be used as a version. Probably if you are using non-alphanumeric characters for the branch name you would need to escape them yourself in the function you are using to assign the version.

**Comment by niosHD** [comment]
Hi @lasote, thank you for the ping!

I fully agree that the caller is responsible for sanitizing the output from `get_branch()` according to the use case.

**Pull request merged**
