### PR TITLE
Remove Exceptions on empty user/channel

### LINKED ISSUE #5749: [bug] Conan supports empty user/channel, but throws on access
> I'm not sure what's the motivation for it right now that we can use references in the name/version@ form. Is it safe to omit that? It throws an Exception on inspect.getmembers otherwise and I'd like to avoid it.

Needed for https://github.com/conan-io/hooks/pull/76

### PR DESCRIPTION
**Pull request by Minimonium**
Changelog: Bugfix: Allow access to `user`/`channel` when they're empty.
Docs: omit

Closes #5749

### CODE REVIEW

**Comment by uilianries** [comment]
Hmm, Jenkins is not happy: 

```
Traceback (most recent call last):

  File "/tmp/source/cd29/py27/disabled_revisions/conans/test/integration/same_userchannel_test.py", line 97, in test_local_commands

    "Error in requirements() method, line 10", self.client.out)

AssertionError: 'ERROR: conanfile.py (Hello/0.1): Error in requirements() method, line 10' not found in Auto detecting your dev setup to initialize the default profile (/tmp/tmpFG9xsvconans/path with spaces/profiles/default)
```

Or is it just because 13th friday? 

Jason

**Comment by Minimonium** [comment]
I see. It requires a change in tests. 
https://github.com/conan-io/conan/blob/develop/conans/test/integration/same_userchannel_test.py#L94

**Comment by Minimonium** [comment]
Related: 
https://github.com/conan-io/docs/issues/1368#issuecomment-515905595
I'm not sure how it should be handled though. 🤔

**Comment by Minimonium** [comment]
@jgsogo It's kinda unfortunate since it blocks the reflection over the base Conanfile for the hook I mentioned above. I'm not sure why, but `inspect.getmembers` seems to read members.

**Comment by jgsogo** [comment]
I'm sure we will be able to find a different implementation for the hook to work 😉

**Comment by Minimonium** [comment]
The change to environment variables is out of the scope of this PR so I'll close it.

**Pull request closed without merging**
