### PR TITLE
minor fixes and worarounds around node-semver

### PR DESCRIPTION
**Pull request by memsharded**
This improves the behavior of the node-semver library used for version ranges, removing the annoying, version "2.1" not being solution for "<=2.1", plus avoid crashing for versions not semver, as "master".

It seems that with this we could avoid forking the upstream lib. Plus it is not fully clear to me a fix to such lib, without messing too much, as the source of the problem seems the prerelease part of the version being automatically added, might break things if removed or modified?

cc/ @DEGoodmanWilson

### CODE REVIEW

**Comment by DEGoodmanWilson** [comment]
Just to clear up a confusion I have: We have tests around this case:
```
result = satisfying(["1.1.1", "1.1.2", "1.2", "1.2.1", "1.3", "2.1"], "<1.3", output)
self.assertEqual(result, "1.2.1")
```

What does `SemVer` do for:
```
result = satisfying(["1.3", "1.3.1"], "<1.3", output)
self.assertEqual(result, "???")
```

or

```
result = satisfying(["1.30", "1.3.1"], "<1.3", output)
self.assertEqual(result, "???")
```

More to the point: What _should_ happen here? Is the missing patchlevel equivalent to a wildcard? (Give me the latest 1.3 release)? Or an implicit '0'?

Just want to get the convention out explicitly and early, is all. My own intuition is that it should be treated as an implicit '0', but I can see arguments either way. And we should have tests around that case ;)

**Comment by lasote** [comment]
Add a test for [2.1], >2 . It didn't work if you don't specify [2.1], >2.0

@DEGoodmanWilson About your comments, I agree about the implicit '0' :+1:

**Comment by memsharded** [comment]
Those checks are as follows:
```python
        result = satisfying(["1.3", "1.3.1"], "<1.3", output)
        self.assertEqual(result, None)
        result = satisfying(["1.3.0", "1.3.1"], "<1.3", output)
        self.assertEqual(result, None)
        result = satisfying(["1.3", "1.3.1"], "<=1.3", output)
        self.assertEqual(result, "1.3")
        result = satisfying(["1.3.0", "1.3.1"], "<=1.3", output)
        self.assertEqual(result, "1.3.0")
        # >2 means >=3.0.0-0
        result = satisfying(["2.1"], ">2", output)
        self.assertEqual(result, None)
        result = satisfying(["2.1"], ">2.0", output)
        self.assertEqual(result, "2.1")
        # >2.1 means >=2.2.0-0
        result = satisfying(["2.1.1"], ">2.1", output)
        self.assertEqual(result, None)
        result = satisfying(["2.1.1"], ">2.1.0", output)
        self.assertEqual(result, "2.1.1")
```

The first 2 as proposed by @DEGoodmanWilson , are fine in my opinion, it doesn't find a solution, as it is strictly "<".
The case proposed by @lasote is a bit unexpected. Internally ">2" means (is translated in the library) ">=3.0.0-0". If seems the semantics are, if you dont specify minor or patch, you are referencing the defined part. So ">2.1" is equivalent to ">=2.2.0-0".  Fixing this would require to fork the library, probably will not be easy without breaking it. 

My suggestion would be just properly documenting its current state (as in the PR)

**Comment by lasote** [comment]
Did you changed something related to:

[>1.0,<2.0] Works
[>1.0,  <2.0] Do not work

?

**Comment by memsharded** [comment]
Yes, spaces are not allowed anymore, they are confusing, and actually removed when the ``ConanFileReference`` is created.

**Pull request merged**
