### PR TITLE
Feature/double dependency

### PR DESCRIPTION
**Pull request by wahlm**
Implements #2583 

This is a proposal of a fix for both resolution errors reported in the issue. Instead of only checking the whole requirement(s), the range_reference(s) are compared, too.

- [x] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ ] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. Also adding a description of the changes in the ``changelog.rst`` file. https://github.com/conan-io/docs

### CODE REVIEW

**Comment by memsharded** [comment]
I have added some more comprenhensive tests, that took me to a somewhat simpler implementation that seems to address those new tests. Please have a look to the PR: https://github.com/conan-io/conan/pull/2597

It would be great if you could run from my source branch against your use case, to check it if is also valid.

I would need to understand also the checks in conans/model/requires.py -> add() method. In which use case are they necessary? Are they related to this failure or to another related one, but not exactly this? If you could please propose some case that I can translate to a test, that would help a lot. Many thanks!

**Comment by wahlm** [comment]
The changes in conans/model/requires.py -> add() were needed if the requirement was put into the configure()-method:

>     def configure(self):
>         self.requires("libD/0.1.latest@mawa/test")
> 

In addition I added a check here to just overwrite the existing requirement if the new requirement is better suited (new requirement is resolved, old one is not resolved). Otherwise an additional resolve cycle is needed unnecessarily (at least as I understood the code...).

My other changes in conans/client/deps_builder.py were needed if the requirement was put into the requirements()-method:

>     def requirements(self):
>         self.requires("libD/0.1.latest@mawa/test")
> 

Anyway, I will check your PR #2597 in our real world example and let you know of the results.

Many thanks for working on these issue!

**Comment by memsharded** [comment]
Thanks to you for your help and working on this too!

Regarding:

> def configure(self):
    self.requires("libD/0.1.latest@mawa/test")

The thing is that requires shouldn't be defined in the ``configure()`` method, it shouldn't be even possible. I mean, right now it kind of work, because it hasn't been restricted, but it can be restricted in the future. Please use only the ``requirements()`` method for this.

Looking forward to your feedback about the PR, many thanks!

**Comment by wahlm** [comment]
Thanks for your feedback!
Our real world example fails in add() in conans/model/requires.py with the newest commits in PR #2597, but it still uses the wrong configure() definition. My add()-fix is still needed here. Surprisingly my stripped down example with configure() works, but add() is not called anymore with a filled old requirement like it was before, probably caused by your fix. I'll try to update my stripped down example (and additionally ask the maintainer of the failing library to move from configure() to requirements()).
I'll keep you informed about the further results.

**Comment by memsharded** [comment]
Thanks @wahlm, let me know then how it goes.
I am also going to have a look if it is possible and makes sense to fix the ``add()`` too.

**Comment by wahlm** [comment]
I have updated my stripped down example to show the error:

> ERROR: libC/0.1.0@mawa/test: Error in configure() method, line 10
>         self.requires("libD/0.1.latest@mawa/test")
>         ConanException: Duplicated requirement libD/0.1.0@mawa/test != libD/0.1.latest@mawa/test

The example is the newest commit in master branch of https://github.com/wahlm/MyTest
(cexport.bat exports all recipes and cinstall.bat installs the main project (testing) conanfile.)
Sorry, it is not a reusable testcase, but you may get an idea of the problem.
Thanks for looking into the add()-case!

**Comment by memsharded** [comment]
Hi @wahlm 

I have been checking the code, and it doesn't seem possible to fix it in a general way by modifying the ``add()`` method, because it is inherently a problem of multiple evaluation of the ``configure()`` or ``requirements()`` method when there are diamonds in the graph. The ``requirements()`` method have implemented a re-initilization of ``requires`` and a further comparison, that is why it shouldn't fail. But such re-initialization cannot be applied too to ``configure()`` without destroying the data.

Please try to move that code to the ``requirements()`` method, I see no other good solution. Many thanks!

**Comment by wahlm** [comment]
Hi @memsharded ,

yes, if there is a possibility to define the wanted dependency, it doesn't matter where it is located. So I think the requires should easily be moved from configure() to requirements().

To reduce the occurance of such (mis-)configuration in the future: What about rejecting requires in configure() as part of a semantic check? This will force the usage of requirements() for it.

So this PR is obsolete as your solution solves the problem and there is no possibility/need for a fix for the add()-case.

**Comment by memsharded** [comment]
This should be already addressed by https://github.com/conan-io/conan/pull/2597

Thanks very much for your contribution and feedback, it really helped!

**Pull request closed without merging**
